#!/bin/bash
# OxysOS fsscript — runs INSIDE the live chroot during livecd-stage2.
# ---------------------------------------------------------------------------
# Responsibilities:
#   1. Remove build-only offline Git source policy.
#   2. Assert the Oxys CLI is installed and owned by app-admin/oxys.
#   3. Make the injected installer binary executable.
#   4. Ensure the ZFS kernel module is loaded BEFORE the installer runs.
#   5. Autologin root on tty1 and exec the installer there.
#   6. Assert live networking and enable the QEMU recovery console.
#
# catalyst copies this script into the chroot and executes it, so all paths
# below are relative to the live root filesystem.
# ---------------------------------------------------------------------------
set -euo pipefail

INSTALLER=/usr/local/bin/oxys-installer
OXYS_CLI=/usr/bin/oxys
LEGACY_OXYS_CLI=/usr/local/bin/oxys
FASTFETCH=/usr/bin/fastfetch
FASTFETCH_CONFIG=/etc/xdg/fastfetch/config.jsonc
FASTFETCH_LOGO=/etc/xdg/fastfetch/oxysos.txt

# Brand the live kernel nodename. Gentoo/OpenRC reads /etc/conf.d/hostname;
# /etc/hostname is written too for tools that follow the cross-distro path.
printf 'OxysOS\n' > /etc/hostname
printf '# generated by OxysOS\nhostname="OxysOS"\n' > /etc/conf.d/hostname

# Replace the stage3's Gentoo identity with the OxysOS release identity. The
# installer rsyncs this live root to the target, so one canonical file brands
# both the ISO session and the installed system.
cat > /etc/os-release <<'EOF'
NAME="OxysOS"
ID=oxys
ID_LIKE=gentoo
PRETTY_NAME="OxysOS v0.1"
HOME_URL="https://oxysos.org"
BUG_REPORT_URL="https://github.com/oxydizer/oxys/issues"
EOF
chmod 0644 /etc/os-release

# Persist OpenRC service output in /var/log/rc.log on the live medium. Replace
# the stage3 default when present, while still handling an unusually minimal
# rc.conf without creating competing assignments.
if grep -qE '^[[:space:]#]*rc_logger=' /etc/rc.conf; then
	sed -i -E 's|^[[:space:]#]*rc_logger=.*$|rc_logger="YES"|' /etc/rc.conf
else
	printf '\n# OxysOS: retain OpenRC service logs\nrc_logger="YES"\n' >> /etc/rc.conf
fi

# Start independent OpenRC services concurrently. This file is rsynced into
# the installed target, so parallel startup applies to both environments.
if grep -qE '^[[:space:]#]*rc_parallel=' /etc/rc.conf; then
	sed -i -E 's|^[[:space:]#]*rc_parallel=.*$|rc_parallel="YES"|' /etc/rc.conf
else
	printf '\n# OxysOS: start independent OpenRC services concurrently\nrc_parallel="YES"\n' >> /etc/rc.conf
fi

# --- 0. Assert OpenRC/sysvinit is PID 1 (fail LOUD if systemd crept in) ------
# The entire live ISO assumes OpenRC: autologin is wired via /etc/inittab and
# every live service is an OpenRC rcadd. If a USE/dependency change pulls
# sys-apps/systemd (e.g. as a logind backend for dbus/polkit/NetworkManager),
# systemd seizes /sbin/init and the ISO silently boots systemd -- which ignores
# /etc/inittab (no autologin, drops to a bare `login:`) and starts no OpenRC
# service. Catch that here in the build instead of shipping a dead ISO. Fix is
# USE="-systemd elogind" (see specs + portage_confdir/make.conf).
init_tgt="$(readlink -f /sbin/init 2>/dev/null || echo /sbin/init)"
case "${init_tgt}" in
	*systemd*)
		echo "fsscript: FATAL: systemd is PID 1 (/sbin/init -> ${init_tgt})." >&2
		echo "  Expected OpenRC/sysvinit. A package pulled sys-apps/systemd as the" >&2
		echo "  logind backend. Set USE=\"-systemd elogind\" and rebuild." >&2
		exit 1
		;;
esac
# Also catch a *dormant* systemd install. USE="-systemd" stops packages enabling
# their systemd integration, but it does NOT stop an unconditional dependency (or
# a `|| ( sys-apps/systemd ... )` any-of) from pulling sys-apps/systemd in. When
# that happens OpenRC can still win /sbin/init (so the check above passes), yet
# the installed systemd still ships systemd-tmpfiles, pam_systemd and
# user@.service -- which then misfire on the rsync'd target (failed `systemd
# --user` sessions, tmpfiles "unsafe path transition /var" warnings). Key on the
# PID 1 manager binary: sys-apps/systemd-utils (the udev/tmpfiles provider an
# OpenRC system legitimately ships) does NOT install /usr/lib/systemd/systemd.
if [[ -e /usr/lib/systemd/systemd || -e /lib/systemd/systemd ]]; then
	echo "fsscript: FATAL: sys-apps/systemd is installed (found its PID 1 manager binary)." >&2
	echo "  OxysOS is OpenRC-only; something pulled it in transitively despite USE=-systemd." >&2
	echo "  It is hard-masked in portage_confdir/package.mask -- rebuild and read the emerge" >&2
	echo "  failure ('masked by ... required by <pkg>') to find the package that pulls it." >&2
	exit 1
fi

# The Gentoo seatd ebuild always installs libseat, but its daemon and OpenRC
# service are conditional on USE=server. The installed OS enables seatd and is
# an rsync copy of this root, so accepting a library-only build produces a
# broken /etc/runlevels/default/seatd link and Niri cannot acquire the seat.
if [[ ! -x /etc/init.d/seatd ]]; then
	echo "fsscript: FATAL: /etc/init.d/seatd is missing." >&2
	echo "  sys-auth/seatd must be built with USE=server for the OpenRC desktop." >&2
	exit 1
fi

# The installed system is rsync'd from the live root and may have no network
# during installation. Keep the configured GTK icon theme in the ISO itself so
# the desktop never depends on a post-install package download.
if [[ ! -s /usr/share/icons/Adwaita/index.theme ]]; then
	echo "fsscript: FATAL: the Adwaita icon theme is missing." >&2
	echo "  x11-themes/adwaita-icon-theme must be merged during livecd-stage1." >&2
	exit 1
fi

# Swap policy is applied on the installed OpenRC system by zram-init. Shipping
# only the kernel driver (or the systemd-only zram-generator wrapper) would
# leave the generated /etc/conf.d/zram-init unused at boot.
if [[ ! -x /etc/init.d/zram-init ]]; then
	echo "fsscript: FATAL: /etc/init.d/zram-init is missing." >&2
	echo "  sys-block/zram-init must be installed for OpenRC zram swap." >&2
	exit 1
fi

# Fastfetch is part of the live and installed base experience. Its XDG config
# points at a separate logo file, so assert the package and both branding files
# together rather than allowing an image with a missing or fallback logo.
if [[ ! -x ${FASTFETCH} ]]; then
	echo "fsscript: FATAL: ${FASTFETCH} is missing or not executable." >&2
	exit 1
fi
for branding_file in "${FASTFETCH_CONFIG}" "${FASTFETCH_LOGO}"; do
	if [[ ! -s ${branding_file} ]]; then
		echo "fsscript: FATAL: Fastfetch branding file ${branding_file} is missing or empty." >&2
		exit 1
	fi
done

KERNEL_CONFIG=/usr/src/oxysos/kernel.config
for option in SWAP ZRAM ZRAM_BACKEND_ZSTD; do
	if ! grep -qE "^CONFIG_${option}=[ym]$" "${KERNEL_CONFIG}"; then
		echo "fsscript: FATAL: CONFIG_${option} is missing from ${KERNEL_CONFIG}." >&2
		exit 1
	fi
done

# Intel CPU microcode is not part of sys-kernel/linux-firmware (unlike AMD's
# payload). The package must install a generic split payload, tell dracut to
# prepend early microcode, and actually make it into the live initramfs that is
# later copied to normal ext4 targets. Checking only the VDB entry would allow
# a hostonly build on a non-Intel ISO builder to ship no useful Intel payload.
# iucode_tool is only a BDEPEND here, so Catalyst would normally remove it
# after building intel-microcode. The target installer can need it again when
# Portage rebuilds intel-microcode; require the explicitly staged copy now.
mapfile -t iucode_tool_vdb_entries < <(
	find /var/db/pkg/sys-apps -mindepth 1 -maxdepth 1 -type d \
		-name 'iucode_tool-[0-9]*' -print 2>/dev/null || true
)
if (( ${#iucode_tool_vdb_entries[@]} != 1 )) \
	|| [[ ! -x /usr/sbin/iucode_tool ]]; then
	echo "fsscript: FATAL: sys-apps/iucode_tool must remain installed for target intel-microcode rebuilds." >&2
	exit 1
fi

# The oxys-generated target make.conf defaults to LDFLAGS="-fuse-ld=mold" and
# FEATURES="ccache" (oxys/src/manifest/compiler.rs). The target root is
# rsync'd from this live root, so gcc on the target finds the linker only if
# mold ships here; without it every on-target source build fails configure
# with "C compiler cannot create executables" (collect2: cannot find 'ld').
if [[ ! -x /usr/bin/mold ]]; then
	echo "fsscript: FATAL: sys-devel/mold must be installed; the target make.conf links with -fuse-ld=mold." >&2
	exit 1
fi
if [[ ! -x /usr/bin/ccache ]]; then
	echo "fsscript: FATAL: dev-util/ccache must be installed; the target make.conf enables FEATURES=ccache." >&2
	exit 1
fi
for option in BLK_DEV_INITRD MICROCODE CPU_SUP_INTEL; do
	if ! grep -q "^CONFIG_${option}=y$" "${KERNEL_CONFIG}"; then
		echo "fsscript: FATAL: CONFIG_${option}=y is required for Intel early microcode." >&2
		exit 1
	fi
done
mapfile -t intel_microcode_vdb_entries < <(
	find /var/db/pkg/sys-firmware -mindepth 1 -maxdepth 1 -type d \
		-name 'intel-microcode-[0-9]*' -print 2>/dev/null || true
)
if (( ${#intel_microcode_vdb_entries[@]} != 1 )); then
	echo "fsscript: FATAL: expected exactly one sys-firmware/intel-microcode VDB entry, found ${#intel_microcode_vdb_entries[@]}." >&2
	exit 1
fi
intel_microcode_use=" $(<"${intel_microcode_vdb_entries[0]}/USE") "
for required_use in initramfs split-ucode; do
	if [[ ${intel_microcode_use} != *" ${required_use} "* ]]; then
		echo "fsscript: FATAL: sys-firmware/intel-microcode is missing USE=${required_use}." >&2
		exit 1
	fi
done
if [[ ${intel_microcode_use} == *' hostonly '* ]]; then
	echo "fsscript: FATAL: sys-firmware/intel-microcode was built with USE=hostonly." >&2
	echo "  A live image must carry microcode for arbitrary supported Intel CPUs." >&2
	exit 1
fi
if ! find /lib/firmware/intel-ucode -mindepth 1 -maxdepth 1 -type f -print -quit \
	2>/dev/null | grep -q .; then
	echo "fsscript: FATAL: /lib/firmware/intel-ucode has no split microcode payload." >&2
	echo "  Build sys-firmware/intel-microcode with USE=split-ucode and -hostonly." >&2
	exit 1
fi
INTEL_DRACUT_CONF=/usr/lib/dracut/dracut.conf.d/15-intel-microcode.conf
if ! grep -qx 'early_microcode=yes' "${INTEL_DRACUT_CONF}" 2>/dev/null; then
	echo "fsscript: FATAL: ${INTEL_DRACUT_CONF} does not enable early microcode." >&2
	echo "  Build sys-firmware/intel-microcode with USE=initramfs." >&2
	exit 1
fi
live_initramfs="$({ find /boot -maxdepth 1 -type f -name 'initramfs*' -print 2>/dev/null || true; } | sort -V | tail -n 1)"
if [[ -z ${live_initramfs} ]]; then
	echo "fsscript: FATAL: no live initramfs found under /boot for microcode verification." >&2
	exit 1
fi
if ! lsinitrd "${live_initramfs}" \
	| awk '$NF == "kernel/x86/microcode/GenuineIntel.bin" { found = 1 } END { exit found ? 0 : 1 }'; then
	echo "fsscript: FATAL: ${live_initramfs} lacks early Intel microcode (GenuineIntel.bin)." >&2
	echo "  Ensure the package is merged before stage2 runs dracut with early_microcode=yes." >&2
	exit 1
fi
echo "OxysOS fsscript: verified generic Intel microcode payload and early initramfs."

# Requiring the userspace compressor is not enough: the injected guest kernel
# must be able to mount the XZ live root before any userspace or installer
# checks can run.
for option in SQUASHFS SQUASHFS_XZ; do
	if ! grep -q "^CONFIG_${option}=y$" "${KERNEL_CONFIG}"; then
		echo "fsscript: FATAL: CONFIG_${option}=y is required for the XZ live root." >&2
		exit 1
	fi
done
echo "OxysOS fsscript: verified kernel support for the XZ live root."

# --- Firewall: the installed-system nftables stack must be complete ----------
# The ephemeral live medium deliberately does not start nftables. Installed
# profiles independently enable it and render this file from the manifest's
# typed Firewall policy, so an image missing any piece would still produce an
# installed system whose enabled service fails at boot. Reject that at build
# time while retaining a valid seed ruleset for the copied target.
NFT_BIN=""
for nft_candidate in /sbin/nft /usr/sbin/nft; do
	if [[ -x ${nft_candidate} ]]; then
		NFT_BIN=${nft_candidate}
		break
	fi
done
if [[ -z ${NFT_BIN} ]]; then
	echo "fsscript: FATAL: nft is missing (checked /sbin/nft, /usr/sbin/nft)." >&2
	echo "  net-firewall/nftables must be merged during livecd-stage1." >&2
	exit 1
fi
if [[ ! -x /etc/init.d/nftables ]]; then
	echo "fsscript: FATAL: /etc/init.d/nftables is missing." >&2
	echo "  The OpenRC service ships with net-firewall/nftables." >&2
	exit 1
fi
NFT_RULES=/var/lib/nftables/rules-save
if [[ ! -s ${NFT_RULES} ]]; then
	echo "fsscript: FATAL: ${NFT_RULES} is missing or empty." >&2
	echo "  The locked-down live ruleset ships via the root overlay." >&2
	exit 1
fi
# The overlay rides through git + rsync, neither of which guarantees these
# modes; the ruleset is root-only policy.
chmod 0700 /var/lib/nftables
chmod 0600 "${NFT_RULES}"
NFT_CONF=/etc/conf.d/nftables
if ! grep -qx 'SAVE_ON_STOP="no"' "${NFT_CONF}" 2>/dev/null; then
	echo "fsscript: FATAL: ${NFT_CONF} does not pin SAVE_ON_STOP=\"no\"." >&2
	echo "  Without it, shutdown overwrites the Oxys-managed ruleset with" >&2
	echo "  whatever transient rules were live." >&2
	exit 1
fi
# The rules only matter if the injected kernel can actually evaluate them.
for option in NETFILTER NF_CONNTRACK NF_TABLES NF_TABLES_INET NFT_CT; do
	if ! grep -qE "^CONFIG_${option}=[ym]$" "${KERNEL_CONFIG}"; then
		echo "fsscript: FATAL: CONFIG_${option} is missing from ${KERNEL_CONFIG}." >&2
		echo "  The nftables firewall cannot load; rebuild the oxys-build kernel" >&2
		echo "  (kernel/hardware.fragment) before rebuilding the ISO." >&2
		exit 1
	fi
done
# Full semantic validation of the shipped ruleset. Requires netlink
# (CAP_NET_ADMIN), which the rootful --privileged catalyst container has.
if ! "${NFT_BIN}" -c -f "${NFT_RULES}"; then
	echo "fsscript: FATAL: ${NFT_RULES} failed ${NFT_BIN} -c -f validation." >&2
	echo "  (If the error is 'Operation not permitted', the build container" >&2
	echo "  lacks CAP_NET_ADMIN or the build host kernel lacks nf_tables.)" >&2
	exit 1
fi
echo "OxysOS fsscript: verified installed-system nftables stack and seed ruleset."

# A virtio GPU still exposes card0/renderD128 when Mesa lacks its virgl driver,
# which makes QEMU look healthy while Niri cannot create an accelerated EGL
# renderer. Assert the actual driver rather than trusting VIDEO_CARDS or the
# binpkg selection log.
if [[ ! -e /usr/lib64/dri/virtio_gpu_dri.so && ! -e /usr/lib/dri/virtio_gpu_dri.so ]]; then
	echo "fsscript: FATAL: Mesa's virtio_gpu_dri.so (video_cards_virgl) is missing." >&2
	echo "  Rebuild media-libs/mesa with video_cards_virgl; do not accept an incompatible binpkg." >&2
	exit 1
fi

# Do not rely on NetworkManager's implicit auto-default connection. A concrete
# wildcard Ethernet profile gives QEMU's virtio NIC (and normal wired hardware)
# a deterministic DHCP path in both the live root and the rsync'd target.
NM_WIRED=/etc/NetworkManager/system-connections/oxys-wired.nmconnection
if [[ ! -x /etc/init.d/NetworkManager || ! -x /usr/bin/NetworkManager ]]; then
	echo "fsscript: FATAL: NetworkManager or its OpenRC service is missing." >&2
	exit 1
fi
if [[ ! -x /etc/init.d/modemmanager || ! -x /usr/sbin/ModemManager ]]; then
	echo "fsscript: FATAL: ModemManager or its OpenRC service is missing." >&2
	exit 1
fi
MODEMMANAGER_CONF=/etc/conf.d/modemmanager
if [[ ! -f ${MODEMMANAGER_CONF} ]]; then
	echo "fsscript: FATAL: /etc/conf.d/modemmanager log redirection is missing." >&2
	exit 1
fi
if ! grep -qx 'rc_before="NetworkManager"' "${MODEMMANAGER_CONF}" \
	|| ! grep -qx 'output_log="/var/log/modemmanager.log"' "${MODEMMANAGER_CONF}" \
	|| ! grep -qx 'error_log="/var/log/modemmanager.log"' "${MODEMMANAGER_CONF}"; then
	echo "fsscript: FATAL: ${MODEMMANAGER_CONF} does not isolate ModemManager from tty1." >&2
	exit 1
fi
if [[ ! -f ${NM_WIRED} ]]; then
	echo "fsscript: FATAL: ${NM_WIRED} is missing." >&2
	exit 1
fi
# NetworkManager ignores keyfiles that are readable by non-root users.
chmod 0600 "${NM_WIRED}"

# --- 1. remove build-only Git source policy ---------------------------------
# catalyst no longer mounts its DISTDIR after the ISO is built. Leaving these
# files in the live root would force later user-initiated emerges offline while
# the prefetched git3 stores are absent.
rm -f /etc/portage/package.env/prefetched-git-sources \
	/etc/portage/env/prefetched-git-source.conf

# --- 1b. Normalize /etc/portage ownership ------------------------------------
# portage_confdir originates from the bind-mounted monorepo checkout (host uid
# 1000) and catalyst's portage_confdir key rsyncs it into the chroot verbatim,
# with no chown. build.sh now normalizes its staged copy before catalyst runs
# (see oxys-iso/build.sh), but assert it again here against the actual
# finished squashfs: the installer rsyncs live->target with --numeric-ids, so
# a uid-1000-owned package.use/mask/accept_keywords/license/env would let the
# installed system's first user (normally also uid 1000) own its own Portage
# policy.
chown -R root:root /etc/portage
if find /etc/portage \( ! -user root -o ! -group root \) -print -quit | grep -q .; then
	echo "fsscript: FATAL: non-root-owned Portage policy under /etc/portage." >&2
	exit 1
fi

# Catalyst has the selected Gentoo snapshot mounted here while fsscript runs,
# but unmounts and cleans that location before creating image.squashfs. Preserve
# the exact mounted tree under a sibling name which Catalyst does not manage.
# A boot-stage OpenRC service exposes it as /var/db/repos/gentoo before the live
# installer starts; rsync then carries both the relative symlink and repository
# into the target's /var/db/repos dataset.
GENTOO_REPO=/var/db/repos/gentoo
if [[ ! -d "${GENTOO_REPO}/metadata/md5-cache/sys-apps" ]] \
	|| [[ ! -s "${GENTOO_REPO}/profiles/categories" ]]; then
	echo "fsscript: FATAL: Gentoo repository is missing or incomplete at ${GENTOO_REPO}." >&2
	echo "  Catalyst must mount the selected snapshot while running fsscript." >&2
	exit 1
fi
if [[ ! -s "${GENTOO_REPO}/profiles/repo_name" ]] \
	|| [[ "$(<"${GENTOO_REPO}/profiles/repo_name")" != gentoo ]]; then
	echo "fsscript: FATAL: ${GENTOO_REPO}/profiles/repo_name is missing or invalid." >&2
	exit 1
fi
PRESERVED_REPOS=/var/db/repos/.oxys-repositories
PRESERVED_GENTOO_REPO=${PRESERVED_REPOS}/gentoo
rm -rf "${PRESERVED_REPOS}"
mkdir -p "${PRESERVED_GENTOO_REPO}"
cp -a "${GENTOO_REPO}/." "${PRESERVED_GENTOO_REPO}/"
if [[ ! -d "${PRESERVED_GENTOO_REPO}/metadata/md5-cache/sys-apps" ]] \
	|| [[ ! -s "${PRESERVED_GENTOO_REPO}/profiles/categories" ]] \
	|| [[ ! -s "${PRESERVED_GENTOO_REPO}/profiles/repo_name" ]] \
	|| [[ "$(<"${PRESERVED_GENTOO_REPO}/profiles/repo_name")" != gentoo ]]; then
	echo "fsscript: FATAL: failed to preserve the Gentoo snapshot at ${PRESERVED_GENTOO_REPO}." >&2
	exit 1
fi
if [[ ! -x /etc/init.d/oxys-gentoo-repo ]]; then
	echo "fsscript: FATAL: /etc/init.d/oxys-gentoo-repo is missing or not executable." >&2
	exit 1
fi
echo "OxysOS fsscript: preserved target-ready Gentoo repository snapshot."

# The first-party and GURU overlays arrive as ordinary ebuild repositories.
# Portage itself can evaluate those ebuilds directly, but the Oxys config
# compiler and USE resolver deliberately consume pregenerated md5-cache data so
# planning stays deterministic and does not execute repository code. Generate
# that metadata while the build chroot still has a working Portage environment;
# without it every overlay package is incorrectly reported as unknown on the
# installer's config-validation screen.
if ! command -v egencache >/dev/null 2>&1; then
	echo "fsscript: FATAL: egencache is required to prepare installer repository metadata." >&2
	exit 1
fi
for overlay_repo in guru oxys; do
	overlay_root="/var/db/repos/${overlay_repo}"
	if [[ ! -s "${overlay_root}/profiles/repo_name" ]] \
		|| [[ "$(<"${overlay_root}/profiles/repo_name")" != "${overlay_repo}" ]]; then
		echo "fsscript: FATAL: ${overlay_root} is missing or has the wrong repository identity." >&2
		exit 1
	fi
	echo "OxysOS fsscript: generating ${overlay_repo} md5-cache metadata."
	# Never let a matching _md5_ preserve cache data transplanted from the
	# installed-package VDB. Built slot operators such as :0/10= are valid in
	# /var/db/pkg but make an ebuild invalid when copied into repository DEPEND.
	rm -rf "${overlay_root}/metadata/md5-cache"
	if ! egencache --update --repo="${overlay_repo}" --jobs=4; then
		echo "fsscript: FATAL: failed to generate metadata for ${overlay_repo}." >&2
		exit 1
	fi
done

required_overlay_atoms=(
	"oxys app-admin oxys"
	"oxys gui-shells noctalia"
	"guru gui-wm niri"
	"guru gui-apps xwayland-satellite"
	"guru gui-apps wlsunset"
)
for required in "${required_overlay_atoms[@]}"; do
	read -r repo category package <<<"${required}"
	cache_category="/var/db/repos/${repo}/metadata/md5-cache/${category}"
	mapfile -t cache_files < <(
		find "${cache_category}" -maxdepth 1 -type f -name "${package}-*" -print 2>/dev/null
	)
	if (( ${#cache_files[@]} == 0 )); then
		echo "fsscript: FATAL: generated ${repo} metadata has no ${category}/${package}." >&2
		exit 1
	fi
	if grep -EH '^(BDEPEND|DEPEND|IDEPEND|PDEPEND|RDEPEND)=.*:[^[:space:]()/]+/[^[:space:]()]+=' \
		"${cache_files[@]}"; then
		echo "fsscript: FATAL: generated ${repo} metadata for ${category}/${package}" >&2
		echo "  contains a VDB-only built slot operator." >&2
		exit 1
	fi
done

# These trees are authoritative package-manager input copied verbatim onto the
# target. The host checkout and Catalyst snapshot can otherwise leave them
# owned by a non-root container uid, so normalize them before rsync ever sees
# them and fail rather than give a future local user write access to ebuilds.
chown -R root:root "${PRESERVED_REPOS}" /var/db/repos/guru /var/db/repos/oxys
if find "${PRESERVED_REPOS}" /var/db/repos/guru /var/db/repos/oxys \
	\( ! -user root -o ! -group root \) -print -quit | grep -q .; then
	echo "fsscript: FATAL: non-root-owned Portage repository content remains." >&2
	exit 1
fi
echo "OxysOS fsscript: verified target-ready overlay metadata and ownership."

# repos.conf governs which VCS/URI each package repo trusts as its source;
# make.conf carries PORTAGE_BINHOST. A group/other-writable copy of either
# would let any unprivileged user on the installed system redirect what
# root's emerge treats as authoritative (e.g. repoint sync-uri or
# PORTAGE_BINHOST at an attacker-controlled source) -- ownership alone
# doesn't catch a stray 0666 from a bad umask or a package postinst.
for trust_file in /etc/portage/make.conf /etc/portage/repos.conf/*.conf; do
	if [[ -e ${trust_file} ]] && find "${trust_file}" -perm /022 -print -quit | grep -q .; then
		echo "fsscript: FATAL: ${trust_file} is group- or other-writable." >&2
		exit 1
	fi
done

# --- 2. Portage-owned Oxys CLI ----------------------------------------------
if [[ ! -x ${OXYS_CLI} ]]; then
	echo "fsscript: FATAL: ${OXYS_CLI} is missing or not executable." >&2
	echo "  app-admin/oxys must be emerged during livecd-stage1." >&2
	exit 1
fi
if [[ -e ${LEGACY_OXYS_CLI} ]]; then
	echo "fsscript: FATAL: obsolete ${LEGACY_OXYS_CLI} is present." >&2
	echo "  It would shadow the Portage-owned ${OXYS_CLI} after self-update." >&2
	exit 1
fi

mapfile -t oxys_vdb_entries < <(
	find /var/db/pkg/app-admin -mindepth 1 -maxdepth 1 -type d -name 'oxys-[0-9]*' -print 2>/dev/null || true
)
if (( ${#oxys_vdb_entries[@]} != 1 )); then
	echo "fsscript: FATAL: expected exactly one app-admin/oxys VDB entry, found ${#oxys_vdb_entries[@]}." >&2
	exit 1
fi
if ! awk '$1 == "obj" && $2 == "/usr/bin/oxys" { found = 1 } END { exit found ? 0 : 1 }' \
	"${oxys_vdb_entries[0]}/CONTENTS"; then
	echo "fsscript: FATAL: app-admin/oxys does not own /usr/bin/oxys in VDB CONTENTS." >&2
	exit 1
fi
oxys_pf="${oxys_vdb_entries[0]##*/}"
oxys_package_version="${oxys_pf#oxys-}"
# Gentoo package revisions (-r1, -r2, ...) rebuild the same upstream version,
# so the CLI embeds PV while the VDB directory records PVR.
if [[ ${oxys_package_version} =~ ^(.+)-r[0-9]+$ ]]; then
	oxys_package_version="${BASH_REMATCH[1]}"
fi
if [[ -z ${oxys_package_version} || ${oxys_pf} == "${oxys_package_version}" ]]; then
	echo "fsscript: FATAL: cannot derive app-admin/oxys version from VDB entry '${oxys_pf}'." >&2
	exit 1
fi
if ! oxys_version="$("${OXYS_CLI}" --version)"; then
	echo "fsscript: FATAL: ${OXYS_CLI} cannot report its version." >&2
	exit 1
fi
if [[ ${oxys_version} != "oxys ${oxys_package_version}" ]]; then
	echo "fsscript: FATAL: ${OXYS_CLI} reports '${oxys_version}', but VDB owns app-admin/${oxys_pf}." >&2
	exit 1
fi
echo "OxysOS fsscript: verified Portage-owned ${oxys_version}."

# --- 2b. pre-warm the on-target config compile cache ------------------------
# `oxys compile` builds a scaffold crate that depends on /usr/src/oxys; a cold
# cache means compiling the oxys library plus its vendored dependency tree,
# which costs minutes on modest hardware. Run one stock-config compile here so
# /root/.cache/oxys/build ships warm in the squashfs: same chroot paths, same
# rust-bin toolchain, and rsync (-a, no /root/.cache exclusion) carries the
# still-valid cache onto the installed target. Afterwards only the config's
# main.rs recompiles, so live-ISO and first-boot compiles are near-instant.
for prewarm_dep in /usr/src/oxys/Cargo.toml /usr/src/oxys/vendor \
	/root/.cargo/config.toml /root/configs/base.fe2o3; do
	if [[ ! -e ${prewarm_dep} ]]; then
		echo "fsscript: FATAL: ${prewarm_dep} is missing; cannot pre-warm the config compile cache." >&2
		exit 1
	fi
done
if ! command -v cargo >/dev/null; then
	echo "fsscript: FATAL: cargo is missing; dev-lang/rust-bin must be in the livecd package list." >&2
	exit 1
fi
prewarm_dir="$(mktemp -d)"
if ! (cd "${prewarm_dir}" && HOME=/root "${OXYS_CLI}" compile /root/configs/base.fe2o3); then
	echo "fsscript: FATAL: pre-warm compile of /root/configs/base.fe2o3 failed." >&2
	exit 1
fi
rm -rf "${prewarm_dir}"
# The compile succeeding proves little if a future change redirects the cache;
# require the artifact this exists to provide: the compiled oxys rlib.
if ! find /root/.cache/oxys/build/target -name 'liboxys-*.rlib' -print -quit \
	| grep -q .; then
	echo "fsscript: FATAL: pre-warm compile left no cached oxys rlib under /root/.cache/oxys/build." >&2
	exit 1
fi
echo "OxysOS fsscript: pre-warmed config compile cache ($(du -sh /root/.cache/oxys/build 2>/dev/null | cut -f1))."

# --- 3. installer binary (delivered via livecd/root_overlay) ----------------
if [[ ! -x ${INSTALLER} ]]; then
	chmod 0755 "${INSTALLER}"
fi

# --- 4. ZFS module load ordering -------------------------------------------
# Two complementary mechanisms, so the module is guaranteed present before the
# installer touches any pool:
#
#   (a) OpenRC's `modules` service (runs in the *boot* runlevel, which always
#       completes before the *default* runlevel / the tty1 getty) loads it
#       early. This is the system-wide, declarative path.
#   (b) An explicit `modprobe zfs` immediately before `exec`-ing the installer
#       in /root/.bash_profile. This is synchronous and authoritative — even if
#       getty races the boot runlevel, the module is loaded right before use.
#
# (a): declare the module for /etc/conf.d/modules (consumed by OpenRC).
if ! grep -q '^modules=.*zfs' /etc/conf.d/modules 2>/dev/null; then
	printf '\n# OxysOS: load ZFS early (boot runlevel)\nmodules="${modules} zfs"\n' \
		>> /etc/conf.d/modules
fi

# --- 5. Make root loginable on the live medium ------------------------------
# The base stage3 ships root LOCKED (`*` in /etc/shadow). tty1 autologins via
# `login -f` (which bypasses auth), so it doesn't need this -- but tty2..tty6
# (and any recovery if the installer wedges) are dead ends without a password.
# Set a known throwaway password on the ephemeral live medium so those consoles
# work. `chpasswd` is used rather than an empty password because Gentoo's PAM
# stack isn't guaranteed to allow nullok logins. NOTE: live-media only; the
# installed system sets its own credentials.
echo 'root:oxys' | chpasswd

# --- 6. Autologin root on tty1 (Gentoo OpenRC uses sysvinit + /etc/inittab) --
# Rewrite the tty1 agetty line to auto-login root. Other ttys are untouched, so
# tty2-6 still give a normal login prompt (handy if the installer wedges).
if grep -qE '^c1:' /etc/inittab; then
	sed -i -E \
		's|^c1:.*tty1.*$|c1:12345:respawn:/sbin/agetty --autologin root --noclear 38400 tty1 linux|' \
		/etc/inittab
else
	printf 'c1:12345:respawn:/sbin/agetty --autologin root --noclear 38400 tty1 linux\n' \
		>> /etc/inittab
fi

# The QEMU runner multiplexes ttyS0 and its monitor onto the host terminal.
# Provide a real guest login there; Ctrl-A c switches between serial and the
# QEMU monitor. This is the recovery path when graphics or networking fails.
if grep -qE '^#?s0:' /etc/inittab; then
	sed -i -E \
		's|^#?s0:.*$|s0:12345:respawn:/sbin/agetty -L 115200 ttyS0 vt100|' \
		/etc/inittab
else
	printf 's0:12345:respawn:/sbin/agetty -L 115200 ttyS0 vt100\n' >> /etc/inittab
fi

# (6 cont.) On tty1, root's login shell launches the installer. The modprobe
# here is the authoritative ordering guarantee from (b) above. We deliberately
# do NOT `exec` it: when the installer quits — whether it finished or failed —
# the login shell falls through to an interactive prompt instead of agetty
# respawning the installer. That keeps the live system debuggable (read
# /var/log/oxys-install.log, re-run `oxys-installer`) rather than a locked kiosk
# loop you can't escape from tty1.
cat > /root/.bash_profile <<'PROFILE'
# OxysOS: launch the installer on the primary console only.
if [[ "$(tty)" == "/dev/tty1" ]]; then
	# Authoritative: ensure ZFS is ready before the installer runs.
	modprobe zfs 2>/dev/null || true
	# Run (not exec) so quitting the installer drops to this shell instead of
	# respawning it. `|| true` keeps the shell alive even on a non-zero exit.
	/usr/local/bin/oxys-installer || true
	echo
	echo "oxys-installer exited. Full install log: /var/log/oxys-install.log"
	echo "Re-run it any time with:  oxys-installer"
fi
PROFILE
chmod 0644 /root/.bash_profile

# --- 7. Pre-warm the config compile cache ------------------------------------
# The installer compiles the user's Rust config into a manifest on first use
# (oxys::compile). Building the oxys dependency tree from cold would take
# minutes; do it once here — in the stage2 chroot, which has the native
# toolchain and the vendored deps shipped via the overlay — so a live compile
# only recompiles the user's single edited file. This mirrors oxys::compile's
# scaffold layout exactly ($HOME/.cache/oxys/build + crate "oxys-config-scaffold"),
# so cargo reuses this target cache verbatim at runtime.
#
# Configs are always executed on the installation machine: stock profiles use
# hardware detection, so a manifest executed on the ISO builder is not valid
# for an arbitrary target. The dependency cache remains safe to reuse.
if command -v cargo >/dev/null 2>&1 && [[ -f /usr/src/oxys/Cargo.toml ]]; then
	export HOME=/root
	WARM=/root/.cache/oxys/build
	mkdir -p "${WARM}/src"
	cat > "${WARM}/Cargo.toml" <<'SCAFFOLD'
[package]
name = "oxys-config-scaffold"
version = "0.0.0"
edition = "2021"

[dependencies]
oxys = { path = "/usr/src/oxys" }
SCAFFOLD
	# Seed the warm cache with desktop (also the default profile).
	cp /root/configs/desktop.fe2o3 "${WARM}/src/main.rs"
	if ( cd "${WARM}" && cargo build ); then
		echo "OxysOS fsscript: pre-warmed config compile cache."
	else
		echo "OxysOS fsscript: config compile pre-warm failed (non-fatal)." >&2
	fi
fi

# --- 8. Record the graphics capabilities of the finished image --------------
# This is generated from installed VDB metadata, real driver artifacts, and
# the injected kernel config. The installer consumes this contract before it
# mutates a target. Older images without it can still be inspected directly.
CAPABILITY_DIR=/usr/share/oxys
CAPABILITY_FILE=${CAPABILITY_DIR}/image-capabilities.toml
mkdir -p "${CAPABILITY_DIR}"

toml_array() {
	local -n values=$1
	local separator="" value
	printf '['
	for value in "${values[@]}"; do
		printf '%s"%s"' "${separator}" "${value}"
		separator=', '
	done
	printf ']'
}

find_graphics_artifact() {
	local name root found
	for name in "$@"; do
		for root in /usr/lib64 /usr/lib; do
			# Match regular files AND symlinks: since Mesa 25/26 every per-driver
			# *_dri.so is a symlink into the single "dril" megadriver
			# (libdril_dri.so), so a bare `-type f` finds none of them.
			found="$(find "${root}" \( -type f -o -type l \) -name "${name}" -print -quit 2>/dev/null || true)"
			if [[ -n "${found}" ]]; then
				printf '%s\n' "${found#/}"
				return 0
			fi
		done
	done
	return 1
}

mesa_vdb="$({ find /var/db/pkg/media-libs -mindepth 1 -maxdepth 1 -type d -name 'mesa-*' -print 2>/dev/null || true; } | sort -V | tail -n 1)"
mesa_version="${mesa_vdb##*/mesa-}"
mesa_cards=()
mesa_artifacts=()

# The installed DRI driver artifact is ground truth: it exists only if that
# gallium driver was actually built into this Mesa. Do NOT additionally gate on
# the VDB USE flag -- some policy cards have no matching Mesa USE flag at all
# (e.g. `amdgpu`, whose Mesa driver IS radeonsi), so a USE gate would wrongly
# reject a capability that is genuinely present on disk.
record_mesa_capability() {
	local flag=$1
	shift
	local artifact
	if artifact="$(find_graphics_artifact "$@")"; then
		mesa_cards+=("${flag}")
		mesa_artifacts+=("${artifact}")
	fi
}

record_mesa_capability video_cards_intel iris_dri.so crocus_dri.so
record_mesa_capability video_cards_amdgpu radeonsi_dri.so
record_mesa_capability video_cards_radeonsi radeonsi_dri.so
record_mesa_capability video_cards_radeon r600_dri.so radeon_dri.so
record_mesa_capability video_cards_nouveau nouveau_dri.so
record_mesa_capability video_cards_virgl virtio_gpu_dri.so
record_mesa_capability video_cards_vmware vmwgfx_dri.so
record_mesa_capability video_cards_lavapipe libvulkan_lvp.so libvulkan_lvp.so.1

# A different-policy binpackage must never silently define the finished image.
# The catalyst config excludes Mesa binpackages, and this independent check
# proves both the requested USE_EXPAND flags and their runtime artifacts made
# it into the actual filesystem.
#
# The source of truth is the build policy that build.sh stages into the image
# (see oxys-iso/build.sh), NOT `portageq envvar VIDEO_CARDS`: our VIDEO_CARDS
# policy lives only in the build-time portage_confdir, which catalyst discards,
# so inside this finished chroot portageq returns the seed stage3's PROFILE
# DEFAULT (amdgpu fbdev intel nouveau radeon radeonsi vesa dummy) -- cards Mesa
# was deliberately not built for -- and the check would false-FATAL on them.
GRAPHICS_POLICY_FILE=/usr/share/oxys/graphics-build-policy.env
if [[ ! -f "${GRAPHICS_POLICY_FILE}" ]]; then
	echo "fsscript: FATAL: ${GRAPHICS_POLICY_FILE} is missing." >&2
	echo "  build.sh must stage the graphics build policy into the root overlay." >&2
	exit 1
fi
# shellcheck source=/dev/null
requested_video_cards="$(. "${GRAPHICS_POLICY_FILE}" && printf '%s' "${VIDEO_CARDS}")"
missing_mesa=()
for card in ${requested_video_cards}; do
	flag="video_cards_${card}"
	if [[ " ${mesa_cards[*]} " != *" ${flag} "* ]]; then
		missing_mesa+=("${flag}")
	fi
done
if (( ${#missing_mesa[@]} > 0 )); then
	echo "fsscript: FATAL: built Mesa does not satisfy VIDEO_CARDS: ${missing_mesa[*]}" >&2
	echo "  Cached/incompatible Mesa packages must be rejected and rebuilt from source." >&2
	exit 1
fi

kernel_config="$({ find /boot -maxdepth 1 -type f -name 'config-*' -print 2>/dev/null || true; } | sort -V | tail -n 1)"
kernel_release="${kernel_config##*/config-}"
kernel_enabled=()
drm_drivers=()
if [[ -f "${kernel_config}" ]]; then
	mapfile -t kernel_enabled < <(awk -F= '$1 ~ /^CONFIG_/ && $2 ~ /^(y|m)$/ { print $1 }' "${kernel_config}" | sort)
	declare -A drm_options=(
		[intel]=CONFIG_DRM_I915
		[amdgpu]=CONFIG_DRM_AMDGPU
		[radeon]=CONFIG_DRM_RADEON
		[nouveau]=CONFIG_DRM_NOUVEAU
		[virtio_gpu]=CONFIG_DRM_VIRTIO_GPU
		[vmwgfx]=CONFIG_DRM_VMWGFX
	)
	for driver in intel amdgpu radeon nouveau virtio_gpu vmwgfx; do
		if grep -qE "^${drm_options[${driver}]}=[ym]$" "${kernel_config}"; then
			drm_drivers+=("${driver}")
		fi
	done
fi

build_id="unknown"
if [[ -f /usr/src/oxysos/build-metadata.env ]]; then
	build_id="$(awk -F= '$1 == "build_id" { sub(/^[^=]*=/, ""); print; exit }' /usr/src/oxysos/build-metadata.env)"
fi
nvidia_vdb="$({ find /var/db/pkg/x11-drivers -mindepth 1 -maxdepth 1 -type d -name 'nvidia-drivers-*' -print 2>/dev/null || true; } | sort -V | tail -n 1)"
nvidia_version="${nvidia_vdb##*/nvidia-drivers-}"
nvidia_proprietary=false
nvidia_kernel_abi=""
if [[ -n "${nvidia_vdb}" ]]; then
	nvidia_proprietary=true
	if find "/lib/modules/${kernel_release}" -type f \( -name 'nvidia_drm.ko' -o -name 'nvidia_drm.ko.*' \) -print -quit 2>/dev/null | grep -q .; then
		nvidia_kernel_abi="${kernel_release}"
	fi
fi

{
	printf 'format_version = 1\n'
	printf 'build_id = "%s"\n' "${build_id:-unknown}"
	printf 'created_utc = "%s"\n\n' "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
	printf '[graphics.mesa]\nversion = "%s"\nvideo_cards = ' "${mesa_version}"
	toml_array mesa_cards
	printf '\nartifacts = '
	toml_array mesa_artifacts
	printf '\n\n[graphics.kernel]\nrelease = "%s"\nconfig_path = "%s"\ndrm_drivers = ' "${kernel_release}" "${kernel_config#/}"
	toml_array drm_drivers
	printf '\nenabled = '
	toml_array kernel_enabled
	printf '\n\n[graphics.nvidia]\nproprietary = %s\n' "${nvidia_proprietary}"
	[[ -n "${nvidia_version}" ]] && printf 'driver_version = "%s"\n' "${nvidia_version}"
	[[ -n "${nvidia_kernel_abi}" ]] && printf 'kernel_abi = "%s"\n' "${nvidia_kernel_abi}"
	printf '\n[graphics.vm]\nvirgl = %s\nvmware = %s\n' \
		"$([[ " ${mesa_cards[*]} " == *' video_cards_virgl '* ]] && printf true || printf false)" \
		"$([[ " ${mesa_cards[*]} " == *' video_cards_vmware '* ]] && printf true || printf false)"
	if [[ " ${mesa_cards[*]} " == *' video_cards_virgl '* ]]; then
		printf 'virgl_launch_device = "virtio-vga-gl"\n'
	fi
	if [[ " ${mesa_cards[*]} " == *' video_cards_vmware '* ]]; then
		printf 'vmware_launch_device = "vmware-svga"\n'
	fi
} > "${CAPABILITY_FILE}"
sha256sum "${CAPABILITY_FILE}" > "${CAPABILITY_FILE}.sha256"
echo "OxysOS fsscript: wrote checksummed image graphics capability contract."

# NOTE: the GURU + oxys overlays are shipped via the ISO root overlay (rsynced
# into /var/db/repos by catalyst), not cloned here -- see
# scripts/build-installer-overlay.sh (GURU checkout) and overlay/var/db/repos/.

echo "OxysOS fsscript: installer + autologin + zfs autoload wired up."
