#!/bin/bash
# OxysOS fsscript — runs INSIDE the live chroot during livecd-stage2.
# ---------------------------------------------------------------------------
# Responsibilities:
#   1. Remove build-only offline Git source policy.
#   2. Make the injected installer binary executable.
#   3. Ensure the ZFS kernel module is loaded BEFORE the installer runs.
#   4. Autologin root on tty1 and exec the installer there.
#   5. Assert live networking and enable the QEMU recovery console.
#
# catalyst copies this script into the chroot and executes it, so all paths
# below are relative to the live root filesystem.
# ---------------------------------------------------------------------------
set -euo pipefail

INSTALLER=/usr/local/bin/oxys-installer

# Brand the live kernel nodename. Gentoo/OpenRC reads /etc/conf.d/hostname;
# /etc/hostname is written too for tools that follow the cross-distro path.
printf 'OxysOS\n' > /etc/hostname
printf '# generated by OxysOS\nhostname="OxysOS"\n' > /etc/conf.d/hostname

# --- 0. Assert OpenRC/sysvinit is PID 1 (fail LOUD if systemd crept in) ------
# The entire live ISO assumes OpenRC: autologin is wired via /etc/inittab and
# every live service is an OpenRC rcadd. If a USE/dependency change pulls
# sys-apps/systemd (e.g. as a logind backend for dbus/polkit/NetworkManager),
# systemd seizes /sbin/init and the ISO silently boots systemd -- which ignores
# /etc/inittab (no autologin, drops to a bare `login:`) and starts no OpenRC
# service. Catch that here in the build instead of shipping a dead ISO. Fix is
# USE="-systemd elogind" (see specs + portage_confdir/make.conf).
init_tgt="$(readlink -f /sbin/init 2>/dev/null || echo /sbin/init)"
case "${init_tgt}" in
	*systemd*)
		echo "fsscript: FATAL: systemd is PID 1 (/sbin/init -> ${init_tgt})." >&2
		echo "  Expected OpenRC/sysvinit. A package pulled sys-apps/systemd as the" >&2
		echo "  logind backend. Set USE=\"-systemd elogind\" and rebuild." >&2
		exit 1
		;;
esac
# Also catch a *dormant* systemd install. USE="-systemd" stops packages enabling
# their systemd integration, but it does NOT stop an unconditional dependency (or
# a `|| ( sys-apps/systemd ... )` any-of) from pulling sys-apps/systemd in. When
# that happens OpenRC can still win /sbin/init (so the check above passes), yet
# the installed systemd still ships systemd-tmpfiles, pam_systemd and
# user@.service -- which then misfire on the rsync'd target (failed `systemd
# --user` sessions, tmpfiles "unsafe path transition /var" warnings). Key on the
# PID 1 manager binary: sys-apps/systemd-utils (the udev/tmpfiles provider an
# OpenRC system legitimately ships) does NOT install /usr/lib/systemd/systemd.
if [[ -e /usr/lib/systemd/systemd || -e /lib/systemd/systemd ]]; then
	echo "fsscript: FATAL: sys-apps/systemd is installed (found its PID 1 manager binary)." >&2
	echo "  OxysOS is OpenRC-only; something pulled it in transitively despite USE=-systemd." >&2
	echo "  It is hard-masked in portage_confdir/package.mask -- rebuild and read the emerge" >&2
	echo "  failure ('masked by ... required by <pkg>') to find the package that pulls it." >&2
	exit 1
fi

# The Gentoo seatd ebuild always installs libseat, but its daemon and OpenRC
# service are conditional on USE=server. The installed OS enables seatd and is
# an rsync copy of this root, so accepting a library-only build produces a
# broken /etc/runlevels/default/seatd link and Niri cannot acquire the seat.
if [[ ! -x /etc/init.d/seatd ]]; then
	echo "fsscript: FATAL: /etc/init.d/seatd is missing." >&2
	echo "  sys-auth/seatd must be built with USE=server for the OpenRC desktop." >&2
	exit 1
fi

# A virtio GPU still exposes card0/renderD128 when Mesa lacks its virgl driver,
# which makes QEMU look healthy while Niri cannot create an accelerated EGL
# renderer. Assert the actual driver rather than trusting VIDEO_CARDS or the
# binpkg selection log.
if [[ ! -e /usr/lib64/dri/virtio_gpu_dri.so && ! -e /usr/lib/dri/virtio_gpu_dri.so ]]; then
	echo "fsscript: FATAL: Mesa's virtio_gpu_dri.so (video_cards_virgl) is missing." >&2
	echo "  Rebuild media-libs/mesa with video_cards_virgl; do not accept an incompatible binpkg." >&2
	exit 1
fi

# Do not rely on NetworkManager's implicit auto-default connection. A concrete
# wildcard Ethernet profile gives QEMU's virtio NIC (and normal wired hardware)
# a deterministic DHCP path in both the live root and the rsync'd target.
NM_WIRED=/etc/NetworkManager/system-connections/oxys-wired.nmconnection
if [[ ! -x /etc/init.d/NetworkManager || ! -x /usr/bin/NetworkManager ]]; then
	echo "fsscript: FATAL: NetworkManager or its OpenRC service is missing." >&2
	exit 1
fi
if [[ ! -f ${NM_WIRED} ]]; then
	echo "fsscript: FATAL: ${NM_WIRED} is missing." >&2
	exit 1
fi
# NetworkManager ignores keyfiles that are readable by non-root users.
chmod 0600 "${NM_WIRED}"

# --- 1. remove build-only Git source policy ---------------------------------
# catalyst no longer mounts its DISTDIR after the ISO is built. Leaving these
# files in the live root would force later user-initiated emerges offline while
# the prefetched git3 stores are absent.
rm -f /etc/portage/package.env/prefetched-git-sources \
	/etc/portage/env/prefetched-git-source.conf

# --- 2. installer binary (delivered via livecd/overlay) ---------------------
if [[ ! -x ${INSTALLER} ]]; then
	chmod 0755 "${INSTALLER}"
fi

# --- 3. ZFS module load ordering -------------------------------------------
# Two complementary mechanisms, so the module is guaranteed present before the
# installer touches any pool:
#
#   (a) OpenRC's `modules` service (runs in the *boot* runlevel, which always
#       completes before the *default* runlevel / the tty1 getty) loads it
#       early. This is the system-wide, declarative path.
#   (b) An explicit `modprobe zfs` immediately before `exec`-ing the installer
#       in /root/.bash_profile. This is synchronous and authoritative — even if
#       getty races the boot runlevel, the module is loaded right before use.
#
# (a): declare the module for /etc/conf.d/modules (consumed by OpenRC).
if ! grep -q '^modules=.*zfs' /etc/conf.d/modules 2>/dev/null; then
	printf '\n# OxysOS: load ZFS early (boot runlevel)\nmodules="${modules} zfs"\n' \
		>> /etc/conf.d/modules
fi

# --- 3b. Make root loginable on the live medium -----------------------------
# The base stage3 ships root LOCKED (`*` in /etc/shadow). tty1 autologins via
# `login -f` (which bypasses auth), so it doesn't need this -- but tty2..tty6
# (and any recovery if the installer wedges) are dead ends without a password.
# Set a known throwaway password on the ephemeral live medium so those consoles
# work. `chpasswd` is used rather than an empty password because Gentoo's PAM
# stack isn't guaranteed to allow nullok logins. NOTE: live-media only; the
# installed system sets its own credentials.
echo 'root:oxys' | chpasswd

# --- 4. Autologin root on tty1 (Gentoo OpenRC uses sysvinit + /etc/inittab) -
# Rewrite the tty1 agetty line to auto-login root. Other ttys are untouched, so
# tty2-6 still give a normal login prompt (handy if the installer wedges).
if grep -qE '^c1:' /etc/inittab; then
	sed -i -E \
		's|^c1:.*tty1.*$|c1:12345:respawn:/sbin/agetty --autologin root --noclear 38400 tty1 linux|' \
		/etc/inittab
else
	printf 'c1:12345:respawn:/sbin/agetty --autologin root --noclear 38400 tty1 linux\n' \
		>> /etc/inittab
fi

# The QEMU runner multiplexes ttyS0 and its monitor onto the host terminal.
# Provide a real guest login there; Ctrl-A c switches between serial and the
# QEMU monitor. This is the recovery path when graphics or networking fails.
if grep -qE '^#?s0:' /etc/inittab; then
	sed -i -E \
		's|^#?s0:.*$|s0:12345:respawn:/sbin/agetty -L 115200 ttyS0 vt100|' \
		/etc/inittab
else
	printf 's0:12345:respawn:/sbin/agetty -L 115200 ttyS0 vt100\n' >> /etc/inittab
fi

# (4 cont.) On tty1, root's login shell launches the installer. The modprobe
# here is the authoritative ordering guarantee from (b) above. We deliberately
# do NOT `exec` it: when the installer quits — whether it finished or failed —
# the login shell falls through to an interactive prompt instead of agetty
# respawning the installer. That keeps the live system debuggable (read
# /var/log/oxys-install.log, re-run `oxys-installer`) rather than a locked kiosk
# loop you can't escape from tty1.
cat > /root/.bash_profile <<'PROFILE'
# OxysOS: launch the installer on the primary console only.
if [[ "$(tty)" == "/dev/tty1" ]]; then
	# Authoritative: ensure ZFS is ready before the installer runs.
	modprobe zfs 2>/dev/null || true
	# Run (not exec) so quitting the installer drops to this shell instead of
	# respawning it. `|| true` keeps the shell alive even on a non-zero exit.
	/usr/local/bin/oxys-installer || true
	echo
	echo "oxys-installer exited. Full install log: /var/log/oxys-install.log"
	echo "Re-run it any time with:  oxys-installer"
fi
PROFILE
chmod 0644 /root/.bash_profile

# --- 5. Pre-warm the config compile cache ----------------------------------
# The installer compiles the user's Rust config into a manifest ON first use
# (oxys::compile). Building the oxys dependency tree from cold would take
# minutes; do it once here — in the stage2 chroot, which has the native
# toolchain and the vendored deps shipped via the overlay — so the live compile
# only recompiles the user's single edited file. This mirrors oxys::compile's
# scaffold layout exactly ($HOME/.cache/oxys/build + crate "oxys-config-scaffold"),
# so cargo reuses this target cache verbatim at runtime. Non-fatal on failure.
if command -v cargo >/dev/null 2>&1 && [[ -f /usr/src/oxys/Cargo.toml ]]; then
	export HOME=/root
	WARM=/root/.cache/oxys/build
	mkdir -p "${WARM}/src"
	cp /root/configs/desktop.fe2o3 "${WARM}/src/main.rs"
	cat > "${WARM}/Cargo.toml" <<'SCAFFOLD'
[package]
name = "oxys-config-scaffold"
version = "0.0.0"
edition = "2021"

[dependencies]
oxys = { path = "/usr/src/oxys" }
SCAFFOLD
	if ( cd "${WARM}" && cargo build ); then
		echo "OxysOS fsscript: pre-warmed config compile cache."
	else
		echo "OxysOS fsscript: config compile pre-warm failed (non-fatal)." >&2
	fi
fi

# NOTE: the GURU + oxys overlays are shipped via the ISO root overlay (rsynced
# into /var/db/repos by catalyst), not cloned here -- see
# scripts/build-installer-overlay.sh (GURU checkout) and overlay/var/db/repos/.

echo "OxysOS fsscript: installer + autologin + zfs autoload wired up."
