#!/bin/bash
# OxysOS fsscript — runs INSIDE the live chroot during livecd-stage2.
# ---------------------------------------------------------------------------
# Responsibilities:
#   1. Remove build-only offline Git source policy.
#   2. Make the injected installer binary executable.
#   3. Ensure the ZFS kernel module is loaded BEFORE the installer runs.
#   4. Autologin root on tty1 and exec the installer there.
#   5. Assert live networking and enable the QEMU recovery console.
#
# catalyst copies this script into the chroot and executes it, so all paths
# below are relative to the live root filesystem.
# ---------------------------------------------------------------------------
set -euo pipefail

INSTALLER=/usr/local/bin/oxys-installer

# Brand the live kernel nodename. Gentoo/OpenRC reads /etc/conf.d/hostname;
# /etc/hostname is written too for tools that follow the cross-distro path.
printf 'OxysOS\n' > /etc/hostname
printf '# generated by OxysOS\nhostname="OxysOS"\n' > /etc/conf.d/hostname

# --- 0. Assert OpenRC/sysvinit is PID 1 (fail LOUD if systemd crept in) ------
# The entire live ISO assumes OpenRC: autologin is wired via /etc/inittab and
# every live service is an OpenRC rcadd. If a USE/dependency change pulls
# sys-apps/systemd (e.g. as a logind backend for dbus/polkit/NetworkManager),
# systemd seizes /sbin/init and the ISO silently boots systemd -- which ignores
# /etc/inittab (no autologin, drops to a bare `login:`) and starts no OpenRC
# service. Catch that here in the build instead of shipping a dead ISO. Fix is
# USE="-systemd elogind" (see specs + portage_confdir/make.conf).
init_tgt="$(readlink -f /sbin/init 2>/dev/null || echo /sbin/init)"
case "${init_tgt}" in
	*systemd*)
		echo "fsscript: FATAL: systemd is PID 1 (/sbin/init -> ${init_tgt})." >&2
		echo "  Expected OpenRC/sysvinit. A package pulled sys-apps/systemd as the" >&2
		echo "  logind backend. Set USE=\"-systemd elogind\" and rebuild." >&2
		exit 1
		;;
esac
# Also catch a *dormant* systemd install. USE="-systemd" stops packages enabling
# their systemd integration, but it does NOT stop an unconditional dependency (or
# a `|| ( sys-apps/systemd ... )` any-of) from pulling sys-apps/systemd in. When
# that happens OpenRC can still win /sbin/init (so the check above passes), yet
# the installed systemd still ships systemd-tmpfiles, pam_systemd and
# user@.service -- which then misfire on the rsync'd target (failed `systemd
# --user` sessions, tmpfiles "unsafe path transition /var" warnings). Key on the
# PID 1 manager binary: sys-apps/systemd-utils (the udev/tmpfiles provider an
# OpenRC system legitimately ships) does NOT install /usr/lib/systemd/systemd.
if [[ -e /usr/lib/systemd/systemd || -e /lib/systemd/systemd ]]; then
	echo "fsscript: FATAL: sys-apps/systemd is installed (found its PID 1 manager binary)." >&2
	echo "  OxysOS is OpenRC-only; something pulled it in transitively despite USE=-systemd." >&2
	echo "  It is hard-masked in portage_confdir/package.mask -- rebuild and read the emerge" >&2
	echo "  failure ('masked by ... required by <pkg>') to find the package that pulls it." >&2
	exit 1
fi

# The Gentoo seatd ebuild always installs libseat, but its daemon and OpenRC
# service are conditional on USE=server. The installed OS enables seatd and is
# an rsync copy of this root, so accepting a library-only build produces a
# broken /etc/runlevels/default/seatd link and Niri cannot acquire the seat.
if [[ ! -x /etc/init.d/seatd ]]; then
	echo "fsscript: FATAL: /etc/init.d/seatd is missing." >&2
	echo "  sys-auth/seatd must be built with USE=server for the OpenRC desktop." >&2
	exit 1
fi

# A virtio GPU still exposes card0/renderD128 when Mesa lacks its virgl driver,
# which makes QEMU look healthy while Niri cannot create an accelerated EGL
# renderer. Assert the actual driver rather than trusting VIDEO_CARDS or the
# binpkg selection log.
if [[ ! -e /usr/lib64/dri/virtio_gpu_dri.so && ! -e /usr/lib/dri/virtio_gpu_dri.so ]]; then
	echo "fsscript: FATAL: Mesa's virtio_gpu_dri.so (video_cards_virgl) is missing." >&2
	echo "  Rebuild media-libs/mesa with video_cards_virgl; do not accept an incompatible binpkg." >&2
	exit 1
fi

# Do not rely on NetworkManager's implicit auto-default connection. A concrete
# wildcard Ethernet profile gives QEMU's virtio NIC (and normal wired hardware)
# a deterministic DHCP path in both the live root and the rsync'd target.
NM_WIRED=/etc/NetworkManager/system-connections/oxys-wired.nmconnection
if [[ ! -x /etc/init.d/NetworkManager || ! -x /usr/bin/NetworkManager ]]; then
	echo "fsscript: FATAL: NetworkManager or its OpenRC service is missing." >&2
	exit 1
fi
if [[ ! -f ${NM_WIRED} ]]; then
	echo "fsscript: FATAL: ${NM_WIRED} is missing." >&2
	exit 1
fi
# NetworkManager ignores keyfiles that are readable by non-root users.
chmod 0600 "${NM_WIRED}"

# --- 1. remove build-only Git source policy ---------------------------------
# catalyst no longer mounts its DISTDIR after the ISO is built. Leaving these
# files in the live root would force later user-initiated emerges offline while
# the prefetched git3 stores are absent.
rm -f /etc/portage/package.env/prefetched-git-sources \
	/etc/portage/env/prefetched-git-source.conf

# --- 2. installer binary (delivered via livecd/overlay) ---------------------
if [[ ! -x ${INSTALLER} ]]; then
	chmod 0755 "${INSTALLER}"
fi

# --- 3. ZFS module load ordering -------------------------------------------
# Two complementary mechanisms, so the module is guaranteed present before the
# installer touches any pool:
#
#   (a) OpenRC's `modules` service (runs in the *boot* runlevel, which always
#       completes before the *default* runlevel / the tty1 getty) loads it
#       early. This is the system-wide, declarative path.
#   (b) An explicit `modprobe zfs` immediately before `exec`-ing the installer
#       in /root/.bash_profile. This is synchronous and authoritative — even if
#       getty races the boot runlevel, the module is loaded right before use.
#
# (a): declare the module for /etc/conf.d/modules (consumed by OpenRC).
if ! grep -q '^modules=.*zfs' /etc/conf.d/modules 2>/dev/null; then
	printf '\n# OxysOS: load ZFS early (boot runlevel)\nmodules="${modules} zfs"\n' \
		>> /etc/conf.d/modules
fi

# --- 3b. Make root loginable on the live medium -----------------------------
# The base stage3 ships root LOCKED (`*` in /etc/shadow). tty1 autologins via
# `login -f` (which bypasses auth), so it doesn't need this -- but tty2..tty6
# (and any recovery if the installer wedges) are dead ends without a password.
# Set a known throwaway password on the ephemeral live medium so those consoles
# work. `chpasswd` is used rather than an empty password because Gentoo's PAM
# stack isn't guaranteed to allow nullok logins. NOTE: live-media only; the
# installed system sets its own credentials.
echo 'root:oxys' | chpasswd

# --- 4. Autologin root on tty1 (Gentoo OpenRC uses sysvinit + /etc/inittab) -
# Rewrite the tty1 agetty line to auto-login root. Other ttys are untouched, so
# tty2-6 still give a normal login prompt (handy if the installer wedges).
if grep -qE '^c1:' /etc/inittab; then
	sed -i -E \
		's|^c1:.*tty1.*$|c1:12345:respawn:/sbin/agetty --autologin root --noclear 38400 tty1 linux|' \
		/etc/inittab
else
	printf 'c1:12345:respawn:/sbin/agetty --autologin root --noclear 38400 tty1 linux\n' \
		>> /etc/inittab
fi

# The QEMU runner multiplexes ttyS0 and its monitor onto the host terminal.
# Provide a real guest login there; Ctrl-A c switches between serial and the
# QEMU monitor. This is the recovery path when graphics or networking fails.
if grep -qE '^#?s0:' /etc/inittab; then
	sed -i -E \
		's|^#?s0:.*$|s0:12345:respawn:/sbin/agetty -L 115200 ttyS0 vt100|' \
		/etc/inittab
else
	printf 's0:12345:respawn:/sbin/agetty -L 115200 ttyS0 vt100\n' >> /etc/inittab
fi

# (4 cont.) On tty1, root's login shell launches the installer. The modprobe
# here is the authoritative ordering guarantee from (b) above. We deliberately
# do NOT `exec` it: when the installer quits — whether it finished or failed —
# the login shell falls through to an interactive prompt instead of agetty
# respawning the installer. That keeps the live system debuggable (read
# /var/log/oxys-install.log, re-run `oxys-installer`) rather than a locked kiosk
# loop you can't escape from tty1.
cat > /root/.bash_profile <<'PROFILE'
# OxysOS: launch the installer on the primary console only.
if [[ "$(tty)" == "/dev/tty1" ]]; then
	# Authoritative: ensure ZFS is ready before the installer runs.
	modprobe zfs 2>/dev/null || true
	# Run (not exec) so quitting the installer drops to this shell instead of
	# respawning it. `|| true` keeps the shell alive even on a non-zero exit.
	/usr/local/bin/oxys-installer || true
	echo
	echo "oxys-installer exited. Full install log: /var/log/oxys-install.log"
	echo "Re-run it any time with:  oxys-installer"
fi
PROFILE
chmod 0644 /root/.bash_profile

# --- 5. Pre-warm the config compile cache ----------------------------------
# The installer compiles the user's Rust config into a manifest ON first use
# (oxys::compile). Building the oxys dependency tree from cold would take
# minutes; do it once here — in the stage2 chroot, which has the native
# toolchain and the vendored deps shipped via the overlay — so the live compile
# only recompiles the user's single edited file. This mirrors oxys::compile's
# scaffold layout exactly ($HOME/.cache/oxys/build + crate "oxys-config-scaffold"),
# so cargo reuses this target cache verbatim at runtime. Non-fatal on failure.
if command -v cargo >/dev/null 2>&1 && [[ -f /usr/src/oxys/Cargo.toml ]]; then
	export HOME=/root
	WARM=/root/.cache/oxys/build
	mkdir -p "${WARM}/src"
	cp /root/configs/desktop.fe2o3 "${WARM}/src/main.rs"
	cat > "${WARM}/Cargo.toml" <<'SCAFFOLD'
[package]
name = "oxys-config-scaffold"
version = "0.0.0"
edition = "2021"

[dependencies]
oxys = { path = "/usr/src/oxys" }
SCAFFOLD
	if ( cd "${WARM}" && cargo build ); then
		echo "OxysOS fsscript: pre-warmed config compile cache."
	else
		echo "OxysOS fsscript: config compile pre-warm failed (non-fatal)." >&2
	fi
fi

# --- 6. Record the graphics capabilities of the finished image -------------
# This is generated from installed VDB metadata, real driver artifacts, and
# the injected kernel config. The installer consumes this contract before it
# mutates a target. Older images without it can still be inspected directly.
CAPABILITY_DIR=/usr/share/oxys
CAPABILITY_FILE=${CAPABILITY_DIR}/image-capabilities.toml
mkdir -p "${CAPABILITY_DIR}"

toml_array() {
	local -n values=$1
	local separator="" value
	printf '['
	for value in "${values[@]}"; do
		printf '%s"%s"' "${separator}" "${value}"
		separator=', '
	done
	printf ']'
}

find_graphics_artifact() {
	local name root found
	for name in "$@"; do
		for root in /usr/lib64 /usr/lib; do
			# Match regular files AND symlinks: since Mesa 25/26 every per-driver
			# *_dri.so is a symlink into the single "dril" megadriver
			# (libdril_dri.so), so a bare `-type f` finds none of them.
			found="$(find "${root}" \( -type f -o -type l \) -name "${name}" -print -quit 2>/dev/null || true)"
			if [[ -n "${found}" ]]; then
				printf '%s\n' "${found#/}"
				return 0
			fi
		done
	done
	return 1
}

mesa_vdb="$({ find /var/db/pkg/media-libs -mindepth 1 -maxdepth 1 -type d -name 'mesa-*' -print 2>/dev/null || true; } | sort -V | tail -n 1)"
mesa_version="${mesa_vdb##*/mesa-}"
mesa_cards=()
mesa_artifacts=()

# The installed DRI driver artifact is ground truth: it exists only if that
# gallium driver was actually built into this Mesa. Do NOT additionally gate on
# the VDB USE flag -- some policy cards have no matching Mesa USE flag at all
# (e.g. `amdgpu`, whose Mesa driver IS radeonsi), so a USE gate would wrongly
# reject a capability that is genuinely present on disk.
record_mesa_capability() {
	local flag=$1
	shift
	local artifact
	if artifact="$(find_graphics_artifact "$@")"; then
		mesa_cards+=("${flag}")
		mesa_artifacts+=("${artifact}")
	fi
}

record_mesa_capability video_cards_intel iris_dri.so crocus_dri.so
record_mesa_capability video_cards_amdgpu radeonsi_dri.so
record_mesa_capability video_cards_radeonsi radeonsi_dri.so
record_mesa_capability video_cards_radeon r600_dri.so radeon_dri.so
record_mesa_capability video_cards_nouveau nouveau_dri.so
record_mesa_capability video_cards_virgl virtio_gpu_dri.so
record_mesa_capability video_cards_vmware vmwgfx_dri.so
record_mesa_capability video_cards_lavapipe libvulkan_lvp.so libvulkan_lvp.so.1

# A different-policy binpackage must never silently define the finished image.
# The catalyst config excludes Mesa binpackages, and this independent check
# proves both the requested USE_EXPAND flags and their runtime artifacts made
# it into the actual filesystem.
#
# The source of truth is the build policy that build.sh stages into the image
# (see oxys-iso/build.sh), NOT `portageq envvar VIDEO_CARDS`: our VIDEO_CARDS
# policy lives only in the build-time portage_confdir, which catalyst discards,
# so inside this finished chroot portageq returns the seed stage3's PROFILE
# DEFAULT (amdgpu fbdev intel nouveau radeon radeonsi vesa dummy) -- cards Mesa
# was deliberately not built for -- and the check would false-FATAL on them.
GRAPHICS_POLICY_FILE=/usr/share/oxys/graphics-build-policy.env
if [[ ! -f "${GRAPHICS_POLICY_FILE}" ]]; then
	echo "fsscript: FATAL: ${GRAPHICS_POLICY_FILE} is missing." >&2
	echo "  build.sh must stage the graphics build policy into the root overlay." >&2
	exit 1
fi
# shellcheck source=/dev/null
requested_video_cards="$(. "${GRAPHICS_POLICY_FILE}" && printf '%s' "${VIDEO_CARDS}")"
missing_mesa=()
for card in ${requested_video_cards}; do
	flag="video_cards_${card}"
	if [[ " ${mesa_cards[*]} " != *" ${flag} "* ]]; then
		missing_mesa+=("${flag}")
	fi
done
if (( ${#missing_mesa[@]} > 0 )); then
	echo "fsscript: FATAL: built Mesa does not satisfy VIDEO_CARDS: ${missing_mesa[*]}" >&2
	echo "  Cached/incompatible Mesa packages must be rejected and rebuilt from source." >&2
	exit 1
fi

kernel_config="$({ find /boot -maxdepth 1 -type f -name 'config-*' -print 2>/dev/null || true; } | sort -V | tail -n 1)"
kernel_release="${kernel_config##*/config-}"
kernel_enabled=()
drm_drivers=()
if [[ -f "${kernel_config}" ]]; then
	mapfile -t kernel_enabled < <(awk -F= '$1 ~ /^CONFIG_/ && $2 ~ /^(y|m)$/ { print $1 }' "${kernel_config}" | sort)
	declare -A drm_options=(
		[intel]=CONFIG_DRM_I915
		[amdgpu]=CONFIG_DRM_AMDGPU
		[radeon]=CONFIG_DRM_RADEON
		[nouveau]=CONFIG_DRM_NOUVEAU
		[virtio_gpu]=CONFIG_DRM_VIRTIO_GPU
		[vmwgfx]=CONFIG_DRM_VMWGFX
	)
	for driver in intel amdgpu radeon nouveau virtio_gpu vmwgfx; do
		if grep -qE "^${drm_options[${driver}]}=[ym]$" "${kernel_config}"; then
			drm_drivers+=("${driver}")
		fi
	done
fi

build_id="unknown"
if [[ -f /usr/src/oxysos/build-metadata.env ]]; then
	build_id="$(awk -F= '$1 == "build_id" { sub(/^[^=]*=/, ""); print; exit }' /usr/src/oxysos/build-metadata.env)"
fi
nvidia_vdb="$({ find /var/db/pkg/x11-drivers -mindepth 1 -maxdepth 1 -type d -name 'nvidia-drivers-*' -print 2>/dev/null || true; } | sort -V | tail -n 1)"
nvidia_version="${nvidia_vdb##*/nvidia-drivers-}"
nvidia_proprietary=false
nvidia_kernel_abi=""
if [[ -n "${nvidia_vdb}" ]]; then
	nvidia_proprietary=true
	if find "/lib/modules/${kernel_release}" -type f \( -name 'nvidia_drm.ko' -o -name 'nvidia_drm.ko.*' \) -print -quit 2>/dev/null | grep -q .; then
		nvidia_kernel_abi="${kernel_release}"
	fi
fi

{
	printf 'format_version = 1\n'
	printf 'build_id = "%s"\n' "${build_id:-unknown}"
	printf 'created_utc = "%s"\n\n' "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
	printf '[graphics.mesa]\nversion = "%s"\nvideo_cards = ' "${mesa_version}"
	toml_array mesa_cards
	printf '\nartifacts = '
	toml_array mesa_artifacts
	printf '\n\n[graphics.kernel]\nrelease = "%s"\nconfig_path = "%s"\ndrm_drivers = ' "${kernel_release}" "${kernel_config#/}"
	toml_array drm_drivers
	printf '\nenabled = '
	toml_array kernel_enabled
	printf '\n\n[graphics.nvidia]\nproprietary = %s\n' "${nvidia_proprietary}"
	[[ -n "${nvidia_version}" ]] && printf 'driver_version = "%s"\n' "${nvidia_version}"
	[[ -n "${nvidia_kernel_abi}" ]] && printf 'kernel_abi = "%s"\n' "${nvidia_kernel_abi}"
	printf '\n[graphics.vm]\nvirgl = %s\nvmware = %s\n' \
		"$([[ " ${mesa_cards[*]} " == *' video_cards_virgl '* ]] && printf true || printf false)" \
		"$([[ " ${mesa_cards[*]} " == *' video_cards_vmware '* ]] && printf true || printf false)"
	if [[ " ${mesa_cards[*]} " == *' video_cards_virgl '* ]]; then
		printf 'virgl_launch_device = "virtio-vga-gl"\n'
	fi
	if [[ " ${mesa_cards[*]} " == *' video_cards_vmware '* ]]; then
		printf 'vmware_launch_device = "vmware-svga"\n'
	fi
} > "${CAPABILITY_FILE}"
sha256sum "${CAPABILITY_FILE}" > "${CAPABILITY_FILE}.sha256"
echo "OxysOS fsscript: wrote checksummed image graphics capability contract."

# NOTE: the GURU + oxys overlays are shipped via the ISO root overlay (rsynced
# into /var/db/repos by catalyst), not cloned here -- see
# scripts/build-installer-overlay.sh (GURU checkout) and overlay/var/db/repos/.

echo "OxysOS fsscript: installer + autologin + zfs autoload wired up."
