use std::path::Path;

use crate::manifest::{Disk, DiskLayout};

use super::{blkid_value, write_file, DiskPartitionMap, SystemInstallError};

pub(super) fn write_fstab(disk: &Disk, target_mount: &Path) -> Result<(), SystemInstallError> {
    let parts = DiskPartitionMap::from_disk(disk);
    let mut lines = vec![
        "# generated by oxys".to_owned(),
        "# <fs> <mountpoint> <type> <opts> <dump/pass>".to_owned(),
    ];

    match disk.layout {
        DiskLayout::Ext4 => {
            let root_uuid = blkid_value(&parts.root, "UUID")?;
            lines.push(format!("UUID={root_uuid} / ext4 defaults,noatime 0 1"));
            if let Some(home) = &parts.home {
                let home_uuid = blkid_value(home, "UUID")?;
                lines.push(format!("UUID={home_uuid} /home ext4 defaults,noatime 0 2"));
            }
        }
        DiskLayout::Zfs => {
            lines.push("# ZFS datasets provide their own root/home mountpoints.".to_owned());
        }
        layout => return Err(SystemInstallError::UnsupportedLayout(layout)),
    }

    let efi_uuid = blkid_value(&parts.efi, "UUID")?;
    lines.push(format!(
        "UUID={efi_uuid} {} vfat umask=0077 0 2",
        disk.partitions.efi.mount
    ));

    if let Some(swap) = &parts.swap {
        let swap_uuid = blkid_value(swap, "UUID")?;
        lines.push(format!("UUID={swap_uuid} none swap sw 0 0"));
    }

    lines.push(String::new());
    write_file(&target_mount.join("etc/fstab"), &lines.join("\n"))
}

pub(super) fn reset_machine_id(target_mount: &Path) -> Result<(), SystemInstallError> {
    write_file(&target_mount.join("etc/machine-id"), "")
}
