use std::os::unix::fs::MetadataExt;
use std::path::Path;
use std::sync::mpsc::Sender;

use crate::manifest::{Disk, DiskLayout, ResolvedSwap, SystemManifest};

use super::{DiskPartitionMap, SystemInstallError, SystemInstallEvent, blkid_value, write_file};

/// Seed the target's declarative state under `/etc/oxys`:
///   * `current-manifest.toml` -- the applied state, always written so
///     `oxys apply`/`diff`/`install` have a baseline (without it they error
///     "current oxys manifest not found" on a freshly installed system), and
///   * `config.fe2o3` -- the authoritative declarative *source* that
///     `oxys install <pkg>` edits, copied when the installer knows which source
///     was compiled.
pub(super) fn seed_oxys_config(
    source_fe2o3: Option<&Path>,
    manifest: &SystemManifest,
    target_mount: &Path,
) -> Result<(), SystemInstallError> {
    let toml = crate::manifest_to_toml(manifest).map_err(|err| {
        SystemInstallError::InvalidPlan(format!("failed to serialize manifest: {err}"))
    })?;
    write_file(&target_mount.join("etc/oxys/current-manifest.toml"), &toml)?;

    if let Some(src) = source_fe2o3 {
        let source = std::fs::read_to_string(src).map_err(|err| {
            SystemInstallError::InvalidPlan(format!(
                "cannot read config source {}: {err}",
                src.display()
            ))
        })?;
        write_file(&target_mount.join("etc/oxys/config.fe2o3"), &source)?;
    }
    Ok(())
}

/// Post-copy sanity check on the freshly rsync'd target root. Catches two
/// failure classes that otherwise only surface at first boot:
///   * a truncated copy (a full target disk aborts rsync partway, leaving
///     whole subtrees like /var/db/pkg missing), and
///   * missing wired-networking runtime files that would leave the installed
///     system offline on first boot, and
///   * mis-owned system directories (e.g. /var owned by a uid other than root,
///     which trips systemd-tmpfiles' "unsafe path transition" check).
/// Runs before we chroot in, so a broken root fails loud instead of being built
/// upon. Ownership is only asserted for dirs that are root:root on every stock
/// system; /home and mount stubs are deliberately excluded.
pub(super) fn verify_target_layout(
    target_mount: &Path,
    sender: &Sender<SystemInstallEvent>,
) -> Result<(), SystemInstallError> {
    // Must exist as directories after a complete copy.
    const REQUIRED_DIRS: &[&str] = &[
        "etc",
        "usr",
        "var",
        "var/tmp",
        "bin",
        "sbin",
        "lib",
        "root",
        "var/db/pkg",
    ];
    const REQUIRED_FILES: &[&str] = &[
        "etc/init.d/NetworkManager",
        "etc/NetworkManager/system-connections/oxys-wired.nmconnection",
    ];
    // Must be owned by root:root (uid 0 / gid 0) on any stock system.
    const ROOT_OWNED: &[&str] = &["", "etc", "usr", "var", "var/tmp", "bin", "sbin", "root"];

    let mut problems = Vec::new();

    for rel in REQUIRED_DIRS {
        let path = target_mount.join(rel);
        if !path.is_dir() {
            problems.push(format!("missing directory /{rel} (copy incomplete?)"));
        }
    }

    for rel in REQUIRED_FILES {
        let path = target_mount.join(rel);
        if !path.is_file() {
            problems.push(format!(
                "missing file /{rel} (wired networking unavailable)"
            ));
        }
    }

    for rel in ROOT_OWNED {
        let path = target_mount.join(rel);
        match path.symlink_metadata() {
            Ok(meta) => {
                let (uid, gid) = (meta.uid(), meta.gid());
                if uid != 0 || gid != 0 {
                    let shown = if rel.is_empty() { "/" } else { rel };
                    problems.push(format!(
                        "/{} is owned by {uid}:{gid}, expected root (0:0)",
                        shown.trim_start_matches('/')
                    ));
                }
            }
            // A missing entry here is already reported by the REQUIRED_DIRS pass
            // (or is a path like "" that always exists); don't double-count.
            Err(_) => {}
        }
    }

    if problems.is_empty() {
        let _ = sender.send(SystemInstallEvent::StepOutput {
            line: "target layout OK: critical dirs present and root-owned".to_owned(),
        });
        return Ok(());
    }

    for problem in &problems {
        let _ = sender.send(SystemInstallEvent::StepOutput {
            line: format!("target check: {problem}"),
        });
    }
    Err(SystemInstallError::TargetValidationFailed(
        problems.join("; "),
    ))
}

pub(super) fn write_fstab(
    disk: &Disk,
    resolved_swap: &ResolvedSwap,
    target_mount: &Path,
) -> Result<(), SystemInstallError> {
    let parts = DiskPartitionMap::from_disk_with_swap(disk, resolved_swap);
    let mut lines = vec![
        "# generated by oxys".to_owned(),
        "# <fs> <mountpoint> <type> <opts> <dump/pass>".to_owned(),
    ];

    match disk.layout {
        DiskLayout::Ext4 => {
            let root_uuid = blkid_value(&parts.root, "UUID")?;
            lines.push(format!("UUID={root_uuid} / ext4 defaults,noatime 0 1"));
            if let Some(home) = &parts.home {
                let home_uuid = blkid_value(home, "UUID")?;
                lines.push(format!("UUID={home_uuid} /home ext4 defaults,noatime 0 2"));
            }
        }
        DiskLayout::Zfs => {
            lines.push("# ZFS datasets provide their own root/home mountpoints.".to_owned());
        }
        layout => return Err(SystemInstallError::UnsupportedLayout(layout)),
    }

    let efi_uuid = blkid_value(&parts.efi, "UUID")?;
    lines.push(format!(
        "UUID={efi_uuid} {} vfat umask=0077 0 2",
        disk.partitions.efi.mount
    ));

    if let Some(swap) = &parts.swap {
        let swap_uuid = blkid_value(swap, "UUID")?;
        let priority = resolved_swap
            .disk
            .as_ref()
            .map(|swap| swap.priority)
            .unwrap_or_default();
        lines.push(format!("UUID={swap_uuid} none swap sw,pri={priority} 0 0"));
    }

    lines.push(String::new());
    write_file(&target_mount.join("etc/fstab"), &lines.join("\n"))
}

pub(super) fn reset_machine_id(target_mount: &Path) -> Result<(), SystemInstallError> {
    write_file(&target_mount.join("etc/machine-id"), "")
}

/// Write both the conventional hostname file and Gentoo OpenRC's hostname
/// service configuration. The latter is what sets the kernel nodename shown
/// by `uname -a`; writing only /etc/hostname leaves Gentoo's `livecd` value in
/// place after the live root is copied to the installed system.
pub(super) fn write_hostname(
    hostname: &str,
    target_mount: &Path,
) -> Result<(), SystemInstallError> {
    let hostname = hostname.trim();
    let valid = !hostname.is_empty()
        && hostname.len() <= 64
        && hostname
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'.'))
        && !matches!(hostname.as_bytes().first(), Some(b'-' | b'.'))
        && !matches!(hostname.as_bytes().last(), Some(b'-' | b'.'));
    if !valid {
        return Err(SystemInstallError::InvalidPlan(format!(
            "invalid hostname {hostname:?}: use 1-64 letters, digits, dots, or hyphens"
        )));
    }

    write_file(&target_mount.join("etc/hostname"), &format!("{hostname}\n"))?;
    write_file(
        &target_mount.join("etc/conf.d/hostname"),
        &format!("# generated by oxys\nhostname=\"{hostname}\"\n"),
    )
}

/// Point /etc/localtime at the target's zoneinfo entry and record the zone
/// name in /etc/timezone (where sys-libs/timezone-data reads it back on
/// updates). The rsync'd live root ships its own localtime (UTC), so an
/// existing link/file is replaced.
pub(super) fn write_timezone(
    timezone: &str,
    target_mount: &Path,
) -> Result<(), SystemInstallError> {
    let timezone = timezone.trim();
    let zoneinfo = target_mount.join("usr/share/zoneinfo");
    if !crate::timezones::timezone_exists(&zoneinfo, timezone) {
        return Err(SystemInstallError::InvalidPlan(format!(
            "invalid timezone {timezone:?}: no such entry under {}",
            zoneinfo.display()
        )));
    }

    write_file(&target_mount.join("etc/timezone"), &format!("{timezone}\n"))?;
    let localtime = target_mount.join("etc/localtime");
    if localtime.symlink_metadata().is_ok() {
        std::fs::remove_file(&localtime)?;
    }
    std::os::unix::fs::symlink(format!("../usr/share/zoneinfo/{timezone}"), &localtime)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn seed_writes_source_and_manifest() {
        let tmp = tempfile::tempdir().unwrap();
        let target = tmp.path();
        let src = tmp.path().join("chosen.fe2o3");
        std::fs::write(&src, "pub fn config() -> Oxys { Oxys::default() }\n").unwrap();

        seed_oxys_config(Some(&src), &SystemManifest::default(), target).unwrap();

        let copied = std::fs::read_to_string(target.join("etc/oxys/config.fe2o3")).unwrap();
        assert!(copied.contains("pub fn config()"));
        let toml = std::fs::read_to_string(target.join("etc/oxys/current-manifest.toml")).unwrap();
        assert!(
            toml.contains("oxys_checksum_sha256"),
            "applied state must be checksummed"
        );
    }

    #[test]
    fn seed_without_source_still_writes_manifest() {
        let tmp = tempfile::tempdir().unwrap();
        let target = tmp.path();

        seed_oxys_config(None, &SystemManifest::default(), target).unwrap();

        assert!(!target.join("etc/oxys/config.fe2o3").exists());
        assert!(target.join("etc/oxys/current-manifest.toml").exists());
    }
}
