use std::{collections::HashMap, fs, path::Path};

use super::{generate_make_conf, gpu_to_video_cards, should_enable_pgo, write_portage_config};
use crate::{
    manifest::{
        BuildOptimisation, Compiler, Gpu, GpuVendor, Graphics, Hardware, March, MesaGraphics, Oxys,
        Package, SystemManifest, VideoCard, VideoCards,
    },
    use_resolver::{Conflict, PortagePlan, UseResolution, Warning},
};

#[test]
fn writes_exact_portage_config_files() -> Result<(), Box<dyn std::error::Error>> {
    let root = test_root("write_portage_config");
    let config_dir = root.join("etc/portage");

    let mut package_use = HashMap::new();
    package_use.insert(
        "gui-wm/niri".to_owned(),
        vec![
            "systemd".to_owned(),
            "dbus".to_owned(),
            "screencast".to_owned(),
            "-debug".to_owned(),
            "-llvm_slot_19".to_owned(),
            "-llvm_slot_18".to_owned(),
            "-llvm_slot_20".to_owned(),
            "dbus".to_owned(),
        ],
    );
    package_use.insert(
        "x11-libs/mesa".to_owned(),
        vec!["wayland".to_owned(), "-X".to_owned()],
    );
    package_use.insert(
        "media-video/pipewire".to_owned(),
        vec!["bluetooth".to_owned(), "-jack".to_owned()],
    );

    let resolution = UseResolution {
        package_use,
        global_use: vec![
            "wayland".to_owned(),
            "-telemetry".to_owned(),
            "systemd".to_owned(),
            "-openrc".to_owned(),
            "-X".to_owned(),
            "-X".to_owned(),
        ],
        accept_keywords: vec![
            "=gui-wm/niri-25.11-r1 ~amd64".to_owned(),
            "=gui-apps/waybar-0.10.3 ~amd64".to_owned(),
            "=gui-wm/niri-25.11-r1 ~amd64".to_owned(),
        ],
        accept_licenses: vec!["GPL-3 gui-wm/niri".to_owned()],
        conflicts: Vec::<Conflict>::new(),
        warnings: Vec::<Warning>::new(),
        decisions: Vec::new(),
    };

    write_portage_config(&resolution, &config_dir)?;

    let jobs = std::thread::available_parallelism()
        .map(|parallelism| parallelism.get())
        .unwrap_or(1);

    let package_use_contents = fs::read_to_string(config_dir.join("package.use"))?;
    let accept_keywords_contents = fs::read_to_string(config_dir.join("package.accept_keywords"))?;
    let accept_licenses_contents = fs::read_to_string(config_dir.join("package.license"))?;
    let make_conf_contents = fs::read_to_string(config_dir.join("make.conf"))?;

    assert_eq!(
        package_use_contents,
        concat!(
            "# generated by oxys - do not edit manually\n",
            "gui-wm/niri -debug -llvm_slot_18 -llvm_slot_19 -llvm_slot_20 dbus screencast systemd\n",
            "media-video/pipewire -jack bluetooth\n",
            "x11-libs/mesa -X wayland\n"
        )
    );
    assert_eq!(
        accept_keywords_contents,
        concat!(
            "# generated by oxys - do not edit manually\n",
            "~amd64 gui-apps/waybar\n",
            "~amd64 gui-wm/niri\n"
        )
    );
    assert_eq!(
        accept_licenses_contents,
        concat!(
            "# generated by oxys - do not edit manually\n",
            "gui-wm/niri GPL-3\n"
        )
    );
    assert_eq!(
        make_conf_contents,
        format!(
            "# generated by oxys - do not edit manually\nUSE=\"-X -openrc -telemetry systemd wayland\"\nMAKEOPTS=\"-j{jobs} -l{jobs}\"\n"
        )
    );

    cleanup(&root)?;
    Ok(())
}

#[test]
fn creates_target_directory_and_overwrites_files() -> Result<(), Box<dyn std::error::Error>> {
    let root = test_root("create_dir");
    let config_dir = root.join("etc/portage");
    let resolution = UseResolution {
        package_use: HashMap::new(),
        global_use: Vec::new(),
        accept_keywords: Vec::new(),
        accept_licenses: Vec::new(),
        conflicts: Vec::new(),
        warnings: Vec::new(),
        decisions: Vec::new(),
    };

    write_portage_config(&resolution, &config_dir)?;

    assert!(config_dir.join("package.use").exists());
    assert!(config_dir.join("package.accept_keywords").exists());
    assert!(config_dir.join("package.license").exists());
    assert!(config_dir.join("make.conf").exists());

    cleanup(&root)?;
    Ok(())
}

#[test]
fn empty_outputs_still_include_required_header() -> Result<(), Box<dyn std::error::Error>> {
    let root = test_root("headers_only");
    let config_dir = root.join("etc/portage");
    let resolution = UseResolution {
        package_use: HashMap::new(),
        global_use: Vec::new(),
        accept_keywords: Vec::new(),
        accept_licenses: Vec::new(),
        conflicts: Vec::new(),
        warnings: Vec::new(),
        decisions: Vec::new(),
    };

    write_portage_config(&resolution, &config_dir)?;

    assert_eq!(
        fs::read_to_string(config_dir.join("package.use"))?,
        "# generated by oxys - do not edit manually\n"
    );
    assert_eq!(
        fs::read_to_string(config_dir.join("package.accept_keywords"))?,
        "# generated by oxys - do not edit manually\n"
    );
    assert_eq!(
        fs::read_to_string(config_dir.join("package.license"))?,
        "# generated by oxys - do not edit manually\n"
    );
    assert!(
        fs::read_to_string(config_dir.join("make.conf"))?
            .starts_with("# generated by oxys - do not edit manually\n")
    );

    cleanup(&root)?;
    Ok(())
}

#[test]
fn gpu_to_video_cards_omits_nvidia() {
    assert_eq!(gpu_to_video_cards(&Gpu::Single(GpuVendor::Nvidia)), None);
}

#[test]
fn gpu_to_video_cards_maps_amd() {
    assert_eq!(
        gpu_to_video_cards(&Gpu::Single(GpuVendor::Amd)),
        Some("amdgpu radeonsi")
    );
}

#[test]
fn gpu_to_video_cards_omits_auto() {
    assert_eq!(gpu_to_video_cards(&Gpu::Auto), None);
}

#[test]
fn balanced_pgo_enables_firefox() {
    assert!(should_enable_pgo(
        "www-client/firefox",
        &BuildOptimisation::Balanced
    ));
}

#[test]
fn balanced_pgo_skips_waybar() {
    assert!(!should_enable_pgo(
        "gui-apps/waybar",
        &BuildOptimisation::Balanced
    ));
}

#[test]
fn fast_pgo_strategy_disables_all_packages() {
    assert!(!should_enable_pgo("anything", &BuildOptimisation::Fast));
}

#[test]
fn performance_pgo_strategy_enables_all_packages() {
    assert!(should_enable_pgo(
        "anything",
        &BuildOptimisation::Performance
    ));
}

#[test]
fn generated_make_conf_contains_core_fields() {
    let output = generate_make_conf(
        &SystemManifest {
            hardware: Hardware {
                graphics: Graphics::from(Gpu::Single(GpuVendor::Nvidia)),
                ..Hardware::default()
            },
            compiler: Compiler {
                binhost: None,
                ..Compiler::default()
            },
            ..SystemManifest::default()
        },
        &["wayland".to_owned()],
        &[],
    );

    assert!(output.make_conf.contains("CFLAGS="));
    assert!(output.make_conf.contains("VIDEO_CARDS=\"nvidia\""));
    assert!(output.make_conf.contains("MAKEOPTS="));
}

#[test]
fn march_is_appended_to_c_and_cxx_flags() {
    let output = generate_make_conf(
        &SystemManifest {
            compiler: Compiler {
                march: March::X86_64V3,
                ..Compiler::default()
            },
            ..SystemManifest::default()
        },
        &[],
        &[],
    );

    assert!(
        output
            .make_conf
            .contains("CFLAGS=\"-O2 -pipe -march=x86-64-v3\"")
    );
    assert!(
        output
            .make_conf
            .contains("CXXFLAGS=\"-O2 -pipe -march=x86-64-v3\"")
    );
}

#[test]
fn configured_binhost_is_emitted_in_make_conf() {
    let output = generate_make_conf(
        &SystemManifest {
            compiler: Compiler {
                march: March::X86_64V3,
                binhost: March::X86_64V3.binhost_url(),
                ..Compiler::default()
            },
            ..SystemManifest::default()
        },
        &[],
        &[],
    );

    assert!(output.make_conf.contains(
            "PORTAGE_BINHOST=\"https://distfiles.gentoo.org/releases/amd64/binpackages/23.0/x86-64-v3/\""
        ));
    assert!(output.make_conf.contains("FEATURES=\"ccache getbinpkg\""));
    assert!(output.make_conf.contains(
            "USE=\"-elogind X alsa dbus fontconfig gtk harfbuzz jpeg opengl pipewire png policykit pulseaudio ssl svg systemd threads udev unicode vulkan wayland webp\""
        ));
    assert!(
        output
            .make_conf
            .contains("VIDEO_CARDS=\"intel radeon radeonsi amdgpu virgl\"")
    );
    assert!(output.make_conf.contains("INPUT_DEVICES=\"libinput\""));
    assert!(output.make_conf.contains("LLVM_TARGETS=\"AMDGPU X86\""));
}

#[test]
fn explicit_graphics_policy_overrides_binhost_video_cards_baseline() {
    let output = generate_make_conf(
        &SystemManifest {
            hardware: Hardware {
                graphics: Graphics {
                    mesa: MesaGraphics {
                        video_cards: VideoCards::Explicit(vec![VideoCard::Virgl]),
                        ..MesaGraphics::default()
                    },
                    ..Graphics::default()
                },
                ..Hardware::default()
            },
            compiler: Compiler {
                march: March::X86_64V3,
                binhost: March::X86_64V3.binhost_url(),
                ..Compiler::default()
            },
            ..SystemManifest::default()
        },
        &[],
        &[],
    );

    assert!(output.make_conf.contains("VIDEO_CARDS=\"virgl\""));
    assert!(
        !output
            .make_conf
            .contains("VIDEO_CARDS=\"intel radeon radeonsi amdgpu virgl\"")
    );
}

#[test]
fn no_binhost_configured_omits_portage_binhost() {
    let output = generate_make_conf(
        &SystemManifest {
            compiler: Compiler {
                binhost: None,
                ..Compiler::default()
            },
            ..SystemManifest::default()
        },
        &[],
        &[],
    );

    assert!(!output.make_conf.contains("PORTAGE_BINHOST"));
    assert!(!output.make_conf.contains("getbinpkg"));
    assert!(!output.make_conf.contains("INPUT_DEVICES="));
    assert!(!output.make_conf.contains("LLVM_TARGETS="));
}

#[test]
fn march_overrides_any_march_in_base_flags() {
    let output = generate_make_conf(
        &SystemManifest {
            compiler: Compiler {
                cflags: "-O3 -march=native -pipe".to_owned(),
                march: March::X86_64V4,
                ..Compiler::default()
            },
            ..SystemManifest::default()
        },
        &[],
        &[],
    );

    assert!(
        output
            .make_conf
            .contains("CFLAGS=\"-O3 -pipe -march=x86-64-v4\"")
    );
    assert!(!output.make_conf.contains("-march=native"));
}

#[test]
fn fast_make_conf_does_not_enable_global_pgo() {
    let output = generate_make_conf(
        &SystemManifest {
            compiler: Compiler {
                optimisation: BuildOptimisation::Fast,
                binhost: None,
                ..Compiler::default()
            },
            ..SystemManifest::default()
        },
        &["wayland".to_owned()],
        &[],
    );

    assert!(output.make_conf.contains("USE=\"wayland\""));
    assert!(!output.make_conf.contains(" pgo"));
    assert!(!output.make_conf.contains("USE=\"pgo"));
}

#[test]
fn auto_gpu_make_conf_omits_video_cards() {
    let output = generate_make_conf(
        &SystemManifest {
            compiler: Compiler {
                binhost: None,
                ..Compiler::default()
            },
            ..SystemManifest::default()
        },
        &[],
        &[],
    );

    assert!(!output.make_conf.contains("VIDEO_CARDS="));
}

#[test]
fn generated_make_conf_header_contains_checksum_line() {
    let output = generate_make_conf(&SystemManifest::default(), &[], &[]);

    assert!(output.make_conf.contains("# checksum: "));
    assert!(
        output
            .make_conf
            .starts_with("# Generated by Oxys — do not edit manually\n")
    );
}

#[test]
fn plan_writer_emits_directory_backed_package_use_files() -> Result<(), Box<dyn std::error::Error>>
{
    let root = test_root("plan_writer");
    let config_dir = root.join("etc/portage");
    let mut package_use = HashMap::new();
    package_use.insert("gui-wm/niri".to_owned(), vec!["wayland".to_owned()]);

    let plan = PortagePlan {
        targets: vec!["=gui-wm/niri-1.0.0".to_owned()],
        manifest: Oxys {
            packages: vec![
                Package::new("www-client/firefox"),
                Package::new("gui-wm/niri"),
            ],
            compiler: Compiler {
                optimisation: BuildOptimisation::Balanced,
                ..Compiler::default()
            },
            ..Oxys::default()
        },
        resolution: UseResolution {
            package_use,
            global_use: vec!["wayland".to_owned()],
            accept_keywords: vec!["=gui-wm/niri-1.0.0 ~amd64".to_owned()],
            accept_licenses: Vec::new(),
            conflicts: Vec::new(),
            warnings: Vec::new(),
            decisions: Vec::new(),
        },
        use_binpkgs: false,
    };

    super::write_portage_plan_config(&plan, &config_dir)?;

    assert_eq!(
        fs::read_to_string(config_dir.join("package.use").join("oxys"))?,
        concat!(
            "# generated by oxys - do not edit manually\n",
            "gui-wm/niri wayland\n"
        )
    );
    assert_eq!(
        fs::read_to_string(config_dir.join("package.use").join("pgo"))?,
        concat!(
            "# generated by oxys - do not edit manually\n",
            "www-client/firefox pgo\n"
        )
    );

    cleanup(&root)?;
    Ok(())
}

fn test_root(name: &str) -> std::path::PathBuf {
    let unique = format!(
        "oxys_portage_generate_{name}_{}_{}",
        std::process::id(),
        chrono::Utc::now().timestamp_nanos_opt().unwrap_or_default()
    );
    std::env::temp_dir().join(unique)
}

fn cleanup(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    if path.exists() {
        fs::remove_dir_all(path)?;
    }
    Ok(())
}
