use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::Path,
    thread,
};

use crate::manifest::{BuildOptimisation, Gpu, GpuVendor, Oxys};

use super::{
    path::split_versioned_package, util::sibling_temp_path, PortagePlan, UseResolution,
    UseResolverError,
};

const GENERATED_HEADER: &str = "# generated by oxys - do not edit manually\n";
const MAKE_CONF_HEADER_PREFIX: &str =
    "# Generated by Oxys — do not edit manually\n# oxys compile regenerates this file\n";
const ZERO_CHECKSUM: &str = "0000000000000000000000000000000000000000000000000000000000000000";
const BINHOST_BASELINE_USE_FLAGS: &[&str] = &[
    "X",
    "wayland",
    "dbus",
    "systemd",
    "-elogind",
    "policykit",
    "alsa",
    "pipewire",
    "pulseaudio",
    "vulkan",
    "opengl",
    "gtk",
    "jpeg",
    "png",
    "webp",
    "svg",
    "fontconfig",
    "harfbuzz",
    "udev",
    "ssl",
    "threads",
    "unicode",
];
const BINHOST_BASELINE_VIDEO_CARDS: &str = "intel radeon radeonsi amdgpu virgl";
const BINHOST_BASELINE_INPUT_DEVICES: &str = "libinput";
const BINHOST_BASELINE_LLVM_TARGETS: &str = "AMDGPU X86";

/// Packages where PGO provides meaningful runtime benefit.
/// Used by BuildOptimisation::Balanced to selectively enable PGO.
const HIGH_VALUE_PGO_PACKAGES: &[&str] = &[
    "www-client/firefox",
    "www-client/chromium",
    "sys-devel/llvm",
    "sys-devel/clang",
    "dev-lang/python",
    "dev-lang/rust",
];

/// Content for generated make.conf and related PGO package.use files.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MakeConfOutput {
    /// Content for /etc/portage/make.conf
    pub make_conf: String,
    /// Content for the active PGO-related package.use file.
    pub package_use_pgo: String,
}

/// Writes generated Portage configuration files for a resolved Portage plan.
pub fn write_portage_config(
    resolution: &UseResolution,
    portage_config_dir: &Path,
) -> Result<(), UseResolverError> {
    fs::create_dir_all(portage_config_dir).map_err(|source| UseResolverError::Io {
        path: portage_config_dir.to_path_buf(),
        source,
    })?;

    write_generated_file(
        &portage_config_dir.join("package.use"),
        &render_package_use(&resolution.package_use),
    )?;
    write_generated_file(
        &portage_config_dir.join("package.accept_keywords"),
        &render_accept_keywords(&resolution.accept_keywords)?,
    )?;
    write_generated_file(
        &portage_config_dir.join("package.license"),
        &render_accept_licenses(&resolution.accept_licenses)?,
    )?;
    write_generated_file(
        &portage_config_dir.join("make.conf"),
        &render_make_conf(&resolution.global_use),
    )?;

    Ok(())
}

/// Writes generated Portage configuration files for the supplied Portage plan.
pub fn write_portage_plan_config(
    plan: &PortagePlan,
    portage_config_dir: &Path,
) -> Result<(), UseResolverError> {
    fs::create_dir_all(portage_config_dir).map_err(|source| UseResolverError::Io {
        path: portage_config_dir.to_path_buf(),
        source,
    })?;

    let package_use_dir = portage_config_dir.join("package.use");
    ensure_generated_directory(&package_use_dir)?;

    write_generated_file(
        &package_use_dir.join("oxys"),
        &render_package_use(&plan.resolution.package_use),
    )?;
    write_generated_file(
        &portage_config_dir.join("package.accept_keywords"),
        &render_accept_keywords(&plan.resolution.accept_keywords)?,
    )?;
    write_generated_file(
        &portage_config_dir.join("package.license"),
        &render_accept_licenses(&plan.resolution.accept_licenses)?,
    )?;

    let make_conf_output = generate_make_conf(
        &plan.manifest,
        &plan.resolution.global_use,
        &plan.resolution.accept_keywords,
    );
    write_generated_file(
        &portage_config_dir.join("make.conf"),
        &make_conf_output.make_conf,
    )?;

    write_generated_file(
        &package_use_dir.join("pgo"),
        &package_use_pgo_contents(&plan.manifest),
    )?;
    write_generated_file(
        &package_use_dir.join("no-pgo"),
        &package_use_no_pgo_contents(&plan.manifest),
    )?;

    Ok(())
}

/// Generates /etc/portage/make.conf content from the Oxys config plus resolved Portage policy.
pub fn generate_make_conf(
    config: &Oxys,
    global_use: &[String],
    accept_keywords: &[String],
) -> MakeConfOutput {
    let mut use_flags = global_use.to_vec();
    if config.compiler.binhost.is_some() {
        use_flags.extend(
            BINHOST_BASELINE_USE_FLAGS
                .iter()
                .map(|flag| (*flag).to_owned()),
        );
    }
    let negative_overrides = use_flags
        .iter()
        .filter_map(|flag| flag.strip_prefix('-'))
        .collect::<BTreeSet<_>>();
    let mut use_flags = dedupe_sorted(&use_flags);
    use_flags.retain(|flag| flag.starts_with('-') || !negative_overrides.contains(flag.as_str()));
    match config.compiler.optimisation {
        BuildOptimisation::Performance => {
            use_flags.push("pgo".to_owned());
            use_flags = dedupe_sorted(&use_flags);
        }
        BuildOptimisation::Fast | BuildOptimisation::Balanced => {}
    }

    let accept_keywords_value = if accept_keywords
        .iter()
        .any(|entry| entry.split_whitespace().any(|token| token == "~amd64"))
    {
        "amd64 ~amd64"
    } else {
        "amd64"
    };

    let mut features = Vec::new();
    if config.compiler.ccache {
        features.push("ccache");
    }
    if config.compiler.binhost.is_some() {
        features.push("getbinpkg");
    }

    let mut lines = vec![
        format!("CFLAGS={}", shell_quote(&config.compiler.resolved_cflags())),
        format!(
            "CXXFLAGS={}",
            shell_quote(&config.compiler.resolved_cxxflags())
        ),
        format!("LDFLAGS={}", shell_quote(&config.compiler.ldflags)),
        format!(
            "MAKEOPTS={}",
            shell_quote(&format!(
                "-j{} -l{}",
                config.compiler.makeopts_jobs, config.compiler.makeopts_jobs
            ))
        ),
        format!(
            "EMERGE_DEFAULT_OPTS={}",
            shell_quote(&format!(
                "--jobs={} --load-average={}",
                config.compiler.emerge_jobs, config.compiler.emerge_jobs
            ))
        ),
        format!("FEATURES={}", shell_quote(&features.join(" "))),
    ];

    if config.compiler.binhost.is_some() {
        lines.push(format!(
            "VIDEO_CARDS={}",
            shell_quote(BINHOST_BASELINE_VIDEO_CARDS)
        ));
        lines.push(format!(
            "INPUT_DEVICES={}",
            shell_quote(BINHOST_BASELINE_INPUT_DEVICES)
        ));
        lines.push(format!(
            "LLVM_TARGETS={}",
            shell_quote(BINHOST_BASELINE_LLVM_TARGETS)
        ));
    } else if let Some(video_cards) = gpu_to_video_cards(&config.hardware.gpu) {
        lines.push(format!("VIDEO_CARDS={}", shell_quote(video_cards)));
    }

    if let Some(binhost) = &config.compiler.binhost {
        lines.push(format!("PORTAGE_BINHOST={}", shell_quote(binhost)));
    }

    lines.extend([
        format!("USE={}", shell_quote(&use_flags.join(" "))),
        format!("ACCEPT_KEYWORDS={}", shell_quote(accept_keywords_value)),
        format!("ACCEPT_LICENSE={}", shell_quote("* -@EULA")),
        format!("GRUB_PLATFORMS={}", shell_quote("efi-64")),
        format!("LC_MESSAGES={}", shell_quote("C")),
    ]);
    let body = format!("{}\n", lines.join("\n"));
    let make_conf = with_make_conf_checksum(&body);

    MakeConfOutput {
        make_conf,
        package_use_pgo: match config.compiler.optimisation {
            BuildOptimisation::Fast => package_use_no_pgo_contents(config),
            BuildOptimisation::Balanced => package_use_pgo_contents(config),
            BuildOptimisation::Performance => String::new(),
        },
    }
}

/// Maps detected GPU to Portage VIDEO_CARDS make.conf value.
pub fn gpu_to_video_cards(gpu: &Gpu) -> Option<&'static str> {
    match gpu {
        Gpu::Auto => None,
        Gpu::Single(GpuVendor::Nvidia) => None,
        Gpu::Single(vendor) => Some(video_cards_for_vendor(*vendor)),
        Gpu::Hybrid { igpu, dgpu } => match (igpu, dgpu) {
            // TODO: Consider exposing explicit hybrid policy instead of flattening to combined VIDEO_CARDS.
            (GpuVendor::Intel, GpuVendor::Nvidia) | (GpuVendor::Nvidia, GpuVendor::Intel) => {
                Some("intel i965")
            }
            (GpuVendor::Amd, GpuVendor::Nvidia) | (GpuVendor::Nvidia, GpuVendor::Amd) => {
                Some("amdgpu radeonsi")
            }
            (GpuVendor::Intel, GpuVendor::Amd) | (GpuVendor::Amd, GpuVendor::Intel) => {
                Some("intel i965 amdgpu radeonsi")
            }
            _ => None,
        },
    }
}

/// Returns true if PGO should be enabled for this package
/// given the current optimisation strategy.
pub fn should_enable_pgo(package: &str, optimisation: &BuildOptimisation) -> bool {
    match optimisation {
        BuildOptimisation::Fast => false,
        BuildOptimisation::Performance => true,
        BuildOptimisation::Balanced => HIGH_VALUE_PGO_PACKAGES
            .iter()
            .any(|candidate| package.starts_with(candidate)),
    }
}

fn video_cards_for_vendor(vendor: GpuVendor) -> &'static str {
    match vendor {
        GpuVendor::Nvidia => unreachable!("NVIDIA drivers are configured post-install"),
        GpuVendor::Amd => "amdgpu radeonsi",
        GpuVendor::Intel => "intel i965",
    }
}

fn package_use_pgo_contents(config: &Oxys) -> String {
    match config.compiler.optimisation {
        BuildOptimisation::Balanced => render_package_use_entries(
            config
                .packages
                .iter()
                .filter(|package| {
                    should_enable_pgo(&package.package, &config.compiler.optimisation)
                })
                .map(|package| format!("{} pgo", package.package)),
        ),
        _ => header_only_generated_file(),
    }
}

fn package_use_no_pgo_contents(config: &Oxys) -> String {
    match config.compiler.optimisation {
        BuildOptimisation::Fast => render_package_use_entries(
            config
                .packages
                .iter()
                .map(|package| format!("{} -pgo", package.package)),
        ),
        _ => header_only_generated_file(),
    }
}

fn render_package_use(package_use: &std::collections::HashMap<String, Vec<String>>) -> String {
    let normalized = package_use
        .iter()
        .map(|(package, flags)| (package.clone(), dedupe_sorted(flags)))
        .filter(|(_, flags)| !flags.is_empty())
        .collect::<BTreeMap<_, _>>();

    let mut output = String::from(GENERATED_HEADER);
    for (package, flags) in normalized {
        output.push_str(&package);
        output.push(' ');
        output.push_str(&flags.join(" "));
        output.push('\n');
    }

    output
}

fn render_accept_keywords(entries: &[String]) -> Result<String, UseResolverError> {
    let mut normalized = BTreeSet::new();

    for entry in entries {
        if let Some((keyword, package)) = normalize_accept_keyword_entry(entry)? {
            normalized.insert((package, keyword));
        }
    }

    let mut output = String::from(GENERATED_HEADER);
    for (package, keyword) in normalized {
        output.push_str(&keyword);
        output.push(' ');
        output.push_str(&package);
        output.push('\n');
    }

    Ok(output)
}

fn render_accept_licenses(entries: &[String]) -> Result<String, UseResolverError> {
    let mut normalized = BTreeSet::new();

    for entry in entries {
        if let Some((license, package)) = normalize_accept_keyword_entry(entry)? {
            normalized.insert((package, license));
        }
    }

    let mut output = String::from(GENERATED_HEADER);
    for (package, license) in normalized {
        output.push_str(&package);
        output.push(' ');
        output.push_str(&license);
        output.push('\n');
    }

    Ok(output)
}

fn normalize_accept_keyword_entry(
    entry: &str,
) -> Result<Option<(String, String)>, UseResolverError> {
    let trimmed = entry.trim();
    if trimmed.is_empty() {
        return Ok(None);
    }

    let mut parts = trimmed.split_whitespace();
    let first = if let Some(value) = parts.next() {
        value
    } else {
        return Ok(None);
    };
    let second = if let Some(value) = parts.next() {
        value
    } else {
        return Ok(None);
    };

    if first.starts_with('=') {
        let (package, _) = split_versioned_package(first.trim_start_matches('='))?;
        return Ok(Some((second.to_owned(), package)));
    }

    if second.starts_with('=') {
        let (package, _) = split_versioned_package(second.trim_start_matches('='))?;
        return Ok(Some((first.to_owned(), package)));
    }

    Ok(Some((first.to_owned(), second.to_owned())))
}

fn render_make_conf(global_use: &[String]) -> String {
    let flags = dedupe_sorted(global_use);
    let jobs = makeopts_jobs();

    let mut output = String::from(GENERATED_HEADER);
    output.push_str("USE=\"");
    output.push_str(&flags.join(" "));
    output.push_str("\"\n");
    output.push_str("MAKEOPTS=\"-j");
    output.push_str(&jobs.to_string());
    output.push_str(" -l");
    output.push_str(&jobs.to_string());
    output.push_str("\"\n");
    output
}

fn render_package_use_entries<I>(entries: I) -> String
where
    I: IntoIterator<Item = String>,
{
    let normalized = entries
        .into_iter()
        .map(|entry| entry.trim().to_owned())
        .filter(|entry| !entry.is_empty())
        .collect::<BTreeSet<_>>();

    let mut output = String::from(GENERATED_HEADER);
    for entry in normalized {
        output.push_str(&entry);
        output.push('\n');
    }
    output
}

fn header_only_generated_file() -> String {
    GENERATED_HEADER.to_owned()
}

fn dedupe_sorted(values: &[String]) -> Vec<String> {
    values
        .iter()
        .map(|value| value.trim())
        .filter(|value| !value.is_empty())
        .map(ToOwned::to_owned)
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect()
}

fn shell_quote(value: &str) -> String {
    crate::util::portage_quote(value)
}

fn with_make_conf_checksum(body: &str) -> String {
    let placeholder = format!("{MAKE_CONF_HEADER_PREFIX}# checksum: {ZERO_CHECKSUM}\n{body}");
    let checksum = sha256_hex(placeholder.as_bytes());
    placeholder.replacen(ZERO_CHECKSUM, &checksum, 1)
}

fn sha256_hex(bytes: &[u8]) -> String {
    crate::util::sha256_hex(bytes)
}

fn makeopts_jobs() -> usize {
    match thread::available_parallelism() {
        Ok(parallelism) => parallelism.get(),
        Err(_) => 1,
    }
}

fn ensure_generated_directory(path: &Path) -> Result<(), UseResolverError> {
    if path.is_file() {
        fs::remove_file(path).map_err(|source| UseResolverError::Io {
            path: path.to_path_buf(),
            source,
        })?;
    }

    fs::create_dir_all(path).map_err(|source| UseResolverError::Io {
        path: path.to_path_buf(),
        source,
    })?;

    Ok(())
}

fn write_generated_file(path: &Path, contents: &str) -> Result<(), UseResolverError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| UseResolverError::Io {
            path: parent.to_path_buf(),
            source,
        })?;
    }

    let temp_path = sibling_temp_path(path, "generated.tmp");
    fs::write(&temp_path, contents).map_err(|source| UseResolverError::Io {
        path: temp_path.clone(),
        source,
    })?;
    fs::rename(&temp_path, path).map_err(|source| UseResolverError::Io {
        path: path.to_path_buf(),
        source,
    })?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use std::{collections::HashMap, fs, path::Path};

    use super::{generate_make_conf, gpu_to_video_cards, should_enable_pgo, write_portage_config};
    use crate::{
        manifest::{
            BuildOptimisation, Compiler, Gpu, GpuVendor, Hardware, March, Oxys, Package,
            SystemManifest,
        },
        use_resolver::{Conflict, PortagePlan, UseResolution, Warning},
    };

    #[test]
    fn writes_exact_portage_config_files() -> Result<(), Box<dyn std::error::Error>> {
        let root = test_root("write_portage_config");
        let config_dir = root.join("etc/portage");

        let mut package_use = HashMap::new();
        package_use.insert(
            "gui-wm/niri".to_owned(),
            vec![
                "systemd".to_owned(),
                "dbus".to_owned(),
                "screencast".to_owned(),
                "-debug".to_owned(),
                "-llvm_slot_19".to_owned(),
                "-llvm_slot_18".to_owned(),
                "-llvm_slot_20".to_owned(),
                "dbus".to_owned(),
            ],
        );
        package_use.insert(
            "x11-libs/mesa".to_owned(),
            vec!["wayland".to_owned(), "-X".to_owned()],
        );
        package_use.insert(
            "media-video/pipewire".to_owned(),
            vec!["bluetooth".to_owned(), "-jack".to_owned()],
        );

        let resolution = UseResolution {
            package_use,
            global_use: vec![
                "wayland".to_owned(),
                "-telemetry".to_owned(),
                "systemd".to_owned(),
                "-openrc".to_owned(),
                "-X".to_owned(),
                "-X".to_owned(),
            ],
            accept_keywords: vec![
                "=gui-wm/niri-25.11-r1 ~amd64".to_owned(),
                "=gui-apps/waybar-0.10.3 ~amd64".to_owned(),
                "=gui-wm/niri-25.11-r1 ~amd64".to_owned(),
            ],
            accept_licenses: vec!["GPL-3 gui-wm/niri".to_owned()],
            conflicts: Vec::<Conflict>::new(),
            warnings: Vec::<Warning>::new(),
            decisions: Vec::new(),
        };

        write_portage_config(&resolution, &config_dir)?;

        let jobs = std::thread::available_parallelism()
            .map(|parallelism| parallelism.get())
            .unwrap_or(1);

        let package_use_contents = fs::read_to_string(config_dir.join("package.use"))?;
        let accept_keywords_contents =
            fs::read_to_string(config_dir.join("package.accept_keywords"))?;
        let accept_licenses_contents = fs::read_to_string(config_dir.join("package.license"))?;
        let make_conf_contents = fs::read_to_string(config_dir.join("make.conf"))?;

        assert_eq!(
            package_use_contents,
            concat!(
                "# generated by oxys - do not edit manually\n",
                "gui-wm/niri -debug -llvm_slot_18 -llvm_slot_19 -llvm_slot_20 dbus screencast systemd\n",
                "media-video/pipewire -jack bluetooth\n",
                "x11-libs/mesa -X wayland\n"
            )
        );
        assert_eq!(
            accept_keywords_contents,
            concat!(
                "# generated by oxys - do not edit manually\n",
                "~amd64 gui-apps/waybar\n",
                "~amd64 gui-wm/niri\n"
            )
        );
        assert_eq!(
            accept_licenses_contents,
            concat!(
                "# generated by oxys - do not edit manually\n",
                "gui-wm/niri GPL-3\n"
            )
        );
        assert_eq!(
            make_conf_contents,
            format!(
                "# generated by oxys - do not edit manually\nUSE=\"-X -openrc -telemetry systemd wayland\"\nMAKEOPTS=\"-j{jobs} -l{jobs}\"\n"
            )
        );

        cleanup(&root)?;
        Ok(())
    }

    #[test]
    fn creates_target_directory_and_overwrites_files() -> Result<(), Box<dyn std::error::Error>> {
        let root = test_root("create_dir");
        let config_dir = root.join("etc/portage");
        let resolution = UseResolution {
            package_use: HashMap::new(),
            global_use: Vec::new(),
            accept_keywords: Vec::new(),
            accept_licenses: Vec::new(),
            conflicts: Vec::new(),
            warnings: Vec::new(),
            decisions: Vec::new(),
        };

        write_portage_config(&resolution, &config_dir)?;

        assert!(config_dir.join("package.use").exists());
        assert!(config_dir.join("package.accept_keywords").exists());
        assert!(config_dir.join("package.license").exists());
        assert!(config_dir.join("make.conf").exists());

        cleanup(&root)?;
        Ok(())
    }

    #[test]
    fn empty_outputs_still_include_required_header() -> Result<(), Box<dyn std::error::Error>> {
        let root = test_root("headers_only");
        let config_dir = root.join("etc/portage");
        let resolution = UseResolution {
            package_use: HashMap::new(),
            global_use: Vec::new(),
            accept_keywords: Vec::new(),
            accept_licenses: Vec::new(),
            conflicts: Vec::new(),
            warnings: Vec::new(),
            decisions: Vec::new(),
        };

        write_portage_config(&resolution, &config_dir)?;

        assert_eq!(
            fs::read_to_string(config_dir.join("package.use"))?,
            "# generated by oxys - do not edit manually\n"
        );
        assert_eq!(
            fs::read_to_string(config_dir.join("package.accept_keywords"))?,
            "# generated by oxys - do not edit manually\n"
        );
        assert_eq!(
            fs::read_to_string(config_dir.join("package.license"))?,
            "# generated by oxys - do not edit manually\n"
        );
        assert!(fs::read_to_string(config_dir.join("make.conf"))?
            .starts_with("# generated by oxys - do not edit manually\n"));

        cleanup(&root)?;
        Ok(())
    }

    #[test]
    fn gpu_to_video_cards_omits_nvidia() {
        assert_eq!(gpu_to_video_cards(&Gpu::Single(GpuVendor::Nvidia)), None);
    }

    #[test]
    fn gpu_to_video_cards_maps_amd() {
        assert_eq!(
            gpu_to_video_cards(&Gpu::Single(GpuVendor::Amd)),
            Some("amdgpu radeonsi")
        );
    }

    #[test]
    fn gpu_to_video_cards_omits_auto() {
        assert_eq!(gpu_to_video_cards(&Gpu::Auto), None);
    }

    #[test]
    fn balanced_pgo_enables_firefox() {
        assert!(should_enable_pgo(
            "www-client/firefox",
            &BuildOptimisation::Balanced
        ));
    }

    #[test]
    fn balanced_pgo_skips_waybar() {
        assert!(!should_enable_pgo(
            "gui-apps/waybar",
            &BuildOptimisation::Balanced
        ));
    }

    #[test]
    fn fast_pgo_strategy_disables_all_packages() {
        assert!(!should_enable_pgo("anything", &BuildOptimisation::Fast));
    }

    #[test]
    fn performance_pgo_strategy_enables_all_packages() {
        assert!(should_enable_pgo(
            "anything",
            &BuildOptimisation::Performance
        ));
    }

    #[test]
    fn generated_make_conf_contains_core_fields() {
        let output = generate_make_conf(
            &SystemManifest {
                hardware: Hardware {
                    gpu: Gpu::Single(GpuVendor::Nvidia),
                    ..Hardware::default()
                },
                compiler: Compiler {
                    binhost: None,
                    ..Compiler::default()
                },
                ..SystemManifest::default()
            },
            &["wayland".to_owned()],
            &[],
        );

        assert!(output.make_conf.contains("CFLAGS="));
        assert!(!output.make_conf.contains("VIDEO_CARDS="));
        assert!(output.make_conf.contains("MAKEOPTS="));
    }

    #[test]
    fn march_is_appended_to_c_and_cxx_flags() {
        let output = generate_make_conf(
            &SystemManifest {
                compiler: Compiler {
                    march: March::X86_64V3,
                    ..Compiler::default()
                },
                ..SystemManifest::default()
            },
            &[],
            &[],
        );

        assert!(output
            .make_conf
            .contains("CFLAGS=\"-O2 -pipe -march=x86-64-v3\""));
        assert!(output
            .make_conf
            .contains("CXXFLAGS=\"-O2 -pipe -march=x86-64-v3\""));
    }

    #[test]
    fn configured_binhost_is_emitted_in_make_conf() {
        let output = generate_make_conf(
            &SystemManifest {
                compiler: Compiler {
                    march: March::X86_64V3,
                    binhost: March::X86_64V3.binhost_url(),
                    ..Compiler::default()
                },
                ..SystemManifest::default()
            },
            &[],
            &[],
        );

        assert!(output.make_conf.contains(
            "PORTAGE_BINHOST=\"https://distfiles.gentoo.org/releases/amd64/binpackages/23.0/x86-64-v3/\""
        ));
        assert!(output.make_conf.contains("FEATURES=\"ccache getbinpkg\""));
        assert!(output.make_conf.contains(
            "USE=\"-elogind X alsa dbus fontconfig gtk harfbuzz jpeg opengl pipewire png policykit pulseaudio ssl svg systemd threads udev unicode vulkan wayland webp\""
        ));
        assert!(output
            .make_conf
            .contains("VIDEO_CARDS=\"intel radeon radeonsi amdgpu virgl\""));
        assert!(output.make_conf.contains("INPUT_DEVICES=\"libinput\""));
        assert!(output.make_conf.contains("LLVM_TARGETS=\"AMDGPU X86\""));
    }

    #[test]
    fn no_binhost_configured_omits_portage_binhost() {
        let output = generate_make_conf(
            &SystemManifest {
                compiler: Compiler {
                    binhost: None,
                    ..Compiler::default()
                },
                ..SystemManifest::default()
            },
            &[],
            &[],
        );

        assert!(!output.make_conf.contains("PORTAGE_BINHOST"));
        assert!(!output.make_conf.contains("getbinpkg"));
        assert!(!output.make_conf.contains("INPUT_DEVICES="));
        assert!(!output.make_conf.contains("LLVM_TARGETS="));
    }

    #[test]
    fn march_overrides_any_march_in_base_flags() {
        let output = generate_make_conf(
            &SystemManifest {
                compiler: Compiler {
                    cflags: "-O3 -march=native -pipe".to_owned(),
                    march: March::X86_64V4,
                    ..Compiler::default()
                },
                ..SystemManifest::default()
            },
            &[],
            &[],
        );

        assert!(output
            .make_conf
            .contains("CFLAGS=\"-O3 -pipe -march=x86-64-v4\""));
        assert!(!output.make_conf.contains("-march=native"));
    }

    #[test]
    fn fast_make_conf_does_not_enable_global_pgo() {
        let output = generate_make_conf(
            &SystemManifest {
                compiler: Compiler {
                    optimisation: BuildOptimisation::Fast,
                    binhost: None,
                    ..Compiler::default()
                },
                ..SystemManifest::default()
            },
            &["wayland".to_owned()],
            &[],
        );

        assert!(output.make_conf.contains("USE=\"wayland\""));
        assert!(!output.make_conf.contains(" pgo"));
        assert!(!output.make_conf.contains("USE=\"pgo"));
    }

    #[test]
    fn auto_gpu_make_conf_omits_video_cards() {
        let output = generate_make_conf(
            &SystemManifest {
                compiler: Compiler {
                    binhost: None,
                    ..Compiler::default()
                },
                ..SystemManifest::default()
            },
            &[],
            &[],
        );

        assert!(!output.make_conf.contains("VIDEO_CARDS="));
    }

    #[test]
    fn generated_make_conf_header_contains_checksum_line() {
        let output = generate_make_conf(&SystemManifest::default(), &[], &[]);

        assert!(output.make_conf.contains("# checksum: "));
        assert!(output
            .make_conf
            .starts_with("# Generated by Oxys — do not edit manually\n"));
    }

    #[test]
    fn plan_writer_emits_directory_backed_package_use_files(
    ) -> Result<(), Box<dyn std::error::Error>> {
        let root = test_root("plan_writer");
        let config_dir = root.join("etc/portage");
        let mut package_use = HashMap::new();
        package_use.insert("gui-wm/niri".to_owned(), vec!["wayland".to_owned()]);

        let plan = PortagePlan {
            targets: vec!["=gui-wm/niri-1.0.0".to_owned()],
            manifest: Oxys {
                packages: vec![
                    Package::new("www-client/firefox"),
                    Package::new("gui-wm/niri"),
                ],
                compiler: Compiler {
                    optimisation: BuildOptimisation::Balanced,
                    ..Compiler::default()
                },
                ..Oxys::default()
            },
            resolution: UseResolution {
                package_use,
                global_use: vec!["wayland".to_owned()],
                accept_keywords: vec!["=gui-wm/niri-1.0.0 ~amd64".to_owned()],
                accept_licenses: Vec::new(),
                conflicts: Vec::new(),
                warnings: Vec::new(),
                decisions: Vec::new(),
            },
            use_binpkgs: false,
        };

        super::write_portage_plan_config(&plan, &config_dir)?;

        assert_eq!(
            fs::read_to_string(config_dir.join("package.use").join("oxys"))?,
            concat!(
                "# generated by oxys - do not edit manually\n",
                "gui-wm/niri wayland\n"
            )
        );
        assert_eq!(
            fs::read_to_string(config_dir.join("package.use").join("pgo"))?,
            concat!(
                "# generated by oxys - do not edit manually\n",
                "www-client/firefox pgo\n"
            )
        );

        cleanup(&root)?;
        Ok(())
    }

    fn test_root(name: &str) -> std::path::PathBuf {
        let unique = format!(
            "oxys_portage_generate_{name}_{}_{}",
            std::process::id(),
            chrono::Utc::now().timestamp_nanos_opt().unwrap_or_default()
        );
        std::env::temp_dir().join(unique)
    }

    fn cleanup(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
        if path.exists() {
            fs::remove_dir_all(path)?;
        }
        Ok(())
    }
}
