use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::Path,
    thread,
};

use crate::manifest::{BuildOptimisation, Gpu, GpuVendor, InitSystem, Oxys};

use super::{
    PortagePlan, UseResolution, UseResolverError, path::split_versioned_package,
    util::sibling_temp_path,
};

const GENERATED_HEADER: &str = "# generated by oxys - do not edit manually\n";
const MAKE_CONF_HEADER_PREFIX: &str =
    "# Generated by Oxys — do not edit manually\n# oxys compile regenerates this file\n";
const ZERO_CHECKSUM: &str = "0000000000000000000000000000000000000000000000000000000000000000";
const BINHOST_BASELINE_COMMON_USE_FLAGS: &[&str] = &[
    "X",
    "wayland",
    "dbus",
    "policykit",
    "alsa",
    "pipewire",
    "pulseaudio",
    "vulkan",
    "opengl",
    "gtk",
    "jpeg",
    "png",
    "webp",
    "svg",
    "fontconfig",
    "harfbuzz",
    "udev",
    "ssl",
    "threads",
    "unicode",
];
const BINHOST_BASELINE_VIDEO_CARDS: &str = "intel radeon radeonsi amdgpu virgl";
const BINHOST_BASELINE_INPUT_DEVICES: &str = "libinput";
const BINHOST_BASELINE_LLVM_TARGETS: &str = "AMDGPU X86";

/// Packages where PGO provides meaningful runtime benefit.
/// Used by BuildOptimisation::Balanced to selectively enable PGO.
const HIGH_VALUE_PGO_PACKAGES: &[&str] = &[
    "www-client/firefox",
    "www-client/chromium",
    "sys-devel/llvm",
    "sys-devel/clang",
    "dev-lang/python",
    "dev-lang/rust",
];

/// Content for generated make.conf and related PGO package.use files.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MakeConfOutput {
    /// Content for /etc/portage/make.conf
    pub make_conf: String,
    /// Content for the active PGO-related package.use file.
    pub package_use_pgo: String,
}

/// Writes generated Portage configuration files for a resolved Portage plan.
mod write;

pub use write::{write_portage_config, write_portage_plan_config};

#[cfg(test)]
mod tests;

pub fn generate_make_conf(config: &Oxys, global_use: &[String]) -> MakeConfOutput {
    let mut use_flags = global_use.to_vec();
    if config.compiler.binhost.is_some() {
        use_flags.extend(
            BINHOST_BASELINE_COMMON_USE_FLAGS
                .iter()
                .map(|flag| (*flag).to_owned()),
        );
        for session_flag in binhost_session_use_flags(config.init_system) {
            let flag_name = session_flag.strip_prefix('-').unwrap_or(session_flag);
            use_flags.retain(|flag| flag.strip_prefix('-').unwrap_or(flag) != flag_name);
            use_flags.push(session_flag.to_owned());
        }
    }
    let negative_overrides = use_flags
        .iter()
        .filter_map(|flag| flag.strip_prefix('-'))
        .collect::<BTreeSet<_>>();
    let mut use_flags = dedupe_sorted(&use_flags);
    use_flags.retain(|flag| flag.starts_with('-') || !negative_overrides.contains(flag.as_str()));
    match config.compiler.optimisation {
        BuildOptimisation::Performance => {
            use_flags.push("pgo".to_owned());
            use_flags = dedupe_sorted(&use_flags);
        }
        BuildOptimisation::Fast | BuildOptimisation::Balanced => {}
    }

    // Unstable keywords are emitted for individual atoms in
    // package.accept_keywords. Promoting one package's ~amd64 exception to a
    // global keyword makes unrelated transitive dependencies jump to testing
    // versions (for example wayland-scanner 1.25 alongside Wayland 1.24).
    let accept_keywords_value = "amd64";

    let mut features = Vec::new();
    if config.compiler.ccache {
        features.push("ccache");
    }
    if config.compiler.binhost.is_some() {
        features.push("getbinpkg");
    }

    let mut lines = vec![
        format!("CFLAGS={}", shell_quote(&config.compiler.resolved_cflags())),
        format!(
            "CXXFLAGS={}",
            shell_quote(&config.compiler.resolved_cxxflags())
        ),
        format!("LDFLAGS={}", shell_quote(&config.compiler.ldflags)),
        format!(
            "MAKEOPTS={}",
            shell_quote(&format!(
                "-j{} -l{}",
                config.compiler.makeopts_jobs, config.compiler.makeopts_jobs
            ))
        ),
        format!(
            "EMERGE_DEFAULT_OPTS={}",
            shell_quote(&format!(
                "--jobs={} --load-average={} --binpkg-respect-use=y",
                config.compiler.emerge_jobs, config.compiler.emerge_jobs
            ))
        ),
        format!("FEATURES={}", shell_quote(&features.join(" "))),
    ];

    let resolved_video_cards = config.resolved_graphics().ok().and_then(|resolved| {
        let mut values = resolved
            .mesa_build_values()
            .into_iter()
            .map(str::to_owned)
            .collect::<Vec<_>>();
        if resolved.policy.nvidia.is_some() {
            values.push("nvidia".to_owned());
        }
        values.sort();
        values.dedup();
        (!values.is_empty()).then(|| values.join(" "))
    });

    if let Some(video_cards) = resolved_video_cards {
        lines.push(format!("VIDEO_CARDS={}", shell_quote(&video_cards)));
    } else if config.compiler.binhost.is_some() {
        lines.push(format!(
            "VIDEO_CARDS={}",
            shell_quote(BINHOST_BASELINE_VIDEO_CARDS)
        ));
        lines.push(format!(
            "INPUT_DEVICES={}",
            shell_quote(BINHOST_BASELINE_INPUT_DEVICES)
        ));
        lines.push(format!(
            "LLVM_TARGETS={}",
            shell_quote(BINHOST_BASELINE_LLVM_TARGETS)
        ));
    }

    if let Some(binhost) = &config.compiler.binhost {
        lines.push(format!("PORTAGE_BINHOST={}", shell_quote(binhost)));
    }

    lines.extend([
        format!("USE={}", shell_quote(&use_flags.join(" "))),
        format!("ACCEPT_KEYWORDS={}", shell_quote(accept_keywords_value)),
        format!("ACCEPT_LICENSE={}", shell_quote("* -@EULA")),
        format!("GRUB_PLATFORMS={}", shell_quote("efi-64")),
        format!("LC_MESSAGES={}", shell_quote("C")),
    ]);
    let body = format!("{}\n", lines.join("\n"));
    let make_conf = with_make_conf_checksum(&body);

    MakeConfOutput {
        make_conf,
        package_use_pgo: match config.compiler.optimisation {
            BuildOptimisation::Fast => package_use_no_pgo_contents(config),
            BuildOptimisation::Balanced => package_use_pgo_contents(config),
            BuildOptimisation::Performance => String::new(),
        },
    }
}

fn binhost_session_use_flags(init_system: InitSystem) -> [&'static str; 2] {
    match init_system {
        InitSystem::Openrc => ["-systemd", "elogind"],
        InitSystem::Systemd => ["systemd", "-elogind"],
    }
}

/// Maps detected GPU to Portage VIDEO_CARDS make.conf value.
pub fn gpu_to_video_cards(gpu: &Gpu) -> Option<&'static str> {
    match gpu {
        Gpu::Auto => None,
        Gpu::Single(GpuVendor::Nvidia) => None,
        Gpu::Single(vendor) => Some(video_cards_for_vendor(*vendor)),
        Gpu::Hybrid { igpu, dgpu } => match (igpu, dgpu) {
            // TODO: Consider exposing explicit hybrid policy instead of flattening to combined VIDEO_CARDS.
            (GpuVendor::Intel, GpuVendor::Nvidia) | (GpuVendor::Nvidia, GpuVendor::Intel) => {
                Some("intel i965")
            }
            (GpuVendor::Amd, GpuVendor::Nvidia) | (GpuVendor::Nvidia, GpuVendor::Amd) => {
                Some("amdgpu radeonsi")
            }
            (GpuVendor::Intel, GpuVendor::Amd) | (GpuVendor::Amd, GpuVendor::Intel) => {
                Some("intel i965 amdgpu radeonsi")
            }
            _ => None,
        },
    }
}

/// Returns true if PGO should be enabled for this package
/// given the current optimisation strategy.
pub fn should_enable_pgo(package: &str, optimisation: &BuildOptimisation) -> bool {
    match optimisation {
        BuildOptimisation::Fast => false,
        BuildOptimisation::Performance => true,
        BuildOptimisation::Balanced => HIGH_VALUE_PGO_PACKAGES
            .iter()
            .any(|candidate| package.starts_with(candidate)),
    }
}

fn video_cards_for_vendor(vendor: GpuVendor) -> &'static str {
    match vendor {
        GpuVendor::Nvidia => unreachable!("NVIDIA drivers are configured post-install"),
        GpuVendor::Amd => "amdgpu radeonsi",
        GpuVendor::Intel => "intel i965",
    }
}

fn package_use_pgo_contents(config: &Oxys) -> String {
    match config.compiler.optimisation {
        BuildOptimisation::Balanced => render_package_use_entries(
            config
                .packages
                .iter()
                .filter(|package| {
                    should_enable_pgo(&package.package, &config.compiler.optimisation)
                })
                .map(|package| format!("{} pgo", package.package)),
        ),
        _ => header_only_generated_file(),
    }
}

fn package_use_no_pgo_contents(config: &Oxys) -> String {
    match config.compiler.optimisation {
        BuildOptimisation::Fast => render_package_use_entries(
            config
                .packages
                .iter()
                .map(|package| format!("{} -pgo", package.package)),
        ),
        _ => header_only_generated_file(),
    }
}

fn render_package_use(package_use: &std::collections::HashMap<String, Vec<String>>) -> String {
    let normalized = package_use
        .iter()
        .map(|(package, flags)| (package.clone(), dedupe_sorted(flags)))
        .filter(|(_, flags)| !flags.is_empty())
        .collect::<BTreeMap<_, _>>();

    let mut output = String::from(GENERATED_HEADER);
    for (package, flags) in normalized {
        output.push_str(&package);
        output.push(' ');
        output.push_str(&flags.join(" "));
        output.push('\n');
    }

    output
}

fn render_accept_keywords(entries: &[String]) -> Result<String, UseResolverError> {
    let mut normalized = BTreeSet::new();

    for entry in entries {
        if let Some((keyword, package)) = normalize_accept_keyword_entry(entry)? {
            normalized.insert((package, keyword));
        }
    }

    let mut output = String::from(GENERATED_HEADER);
    for (package, keyword) in normalized {
        output.push_str(&package);
        output.push(' ');
        output.push_str(&keyword);
        output.push('\n');
    }

    Ok(output)
}

fn render_accept_licenses(entries: &[String]) -> Result<String, UseResolverError> {
    let mut normalized = BTreeSet::new();

    for entry in entries {
        if let Some((license, package)) = normalize_accept_keyword_entry(entry)? {
            normalized.insert((package, license));
        }
    }

    let mut output = String::from(GENERATED_HEADER);
    for (package, license) in normalized {
        output.push_str(&package);
        output.push(' ');
        output.push_str(&license);
        output.push('\n');
    }

    Ok(output)
}

fn normalize_accept_keyword_entry(
    entry: &str,
) -> Result<Option<(String, String)>, UseResolverError> {
    let trimmed = entry.trim();
    if trimmed.is_empty() {
        return Ok(None);
    }

    let mut parts = trimmed.split_whitespace();
    let first = if let Some(value) = parts.next() {
        value
    } else {
        return Ok(None);
    };
    let second = if let Some(value) = parts.next() {
        value
    } else {
        return Ok(None);
    };

    if first.starts_with('=') {
        let (package, _) = split_versioned_package(first.trim_start_matches('='))?;
        return Ok(Some((second.to_owned(), package)));
    }

    if second.starts_with('=') {
        let (package, _) = split_versioned_package(second.trim_start_matches('='))?;
        return Ok(Some((first.to_owned(), package)));
    }

    Ok(Some((first.to_owned(), second.to_owned())))
}

fn render_make_conf(global_use: &[String]) -> String {
    let flags = dedupe_sorted(global_use);
    let jobs = makeopts_jobs();

    let mut output = String::from(GENERATED_HEADER);
    output.push_str("USE=\"");
    output.push_str(&flags.join(" "));
    output.push_str("\"\n");
    output.push_str("MAKEOPTS=\"-j");
    output.push_str(&jobs.to_string());
    output.push_str(" -l");
    output.push_str(&jobs.to_string());
    output.push_str("\"\n");
    output
}

fn render_package_use_entries<I>(entries: I) -> String
where
    I: IntoIterator<Item = String>,
{
    let normalized = entries
        .into_iter()
        .map(|entry| entry.trim().to_owned())
        .filter(|entry| !entry.is_empty())
        .collect::<BTreeSet<_>>();

    let mut output = String::from(GENERATED_HEADER);
    for entry in normalized {
        output.push_str(&entry);
        output.push('\n');
    }
    output
}

fn header_only_generated_file() -> String {
    GENERATED_HEADER.to_owned()
}

fn dedupe_sorted(values: &[String]) -> Vec<String> {
    values
        .iter()
        .map(|value| value.trim())
        .filter(|value| !value.is_empty())
        .map(ToOwned::to_owned)
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect()
}

fn shell_quote(value: &str) -> String {
    crate::util::portage_quote(value)
}

fn with_make_conf_checksum(body: &str) -> String {
    let placeholder = format!("{MAKE_CONF_HEADER_PREFIX}# checksum: {ZERO_CHECKSUM}\n{body}");
    let checksum = sha256_hex(placeholder.as_bytes());
    placeholder.replacen(ZERO_CHECKSUM, &checksum, 1)
}

fn sha256_hex(bytes: &[u8]) -> String {
    crate::util::sha256_hex(bytes)
}

fn makeopts_jobs() -> usize {
    match thread::available_parallelism() {
        Ok(parallelism) => parallelism.get(),
        Err(_) => 1,
    }
}
