use std::{fs, path::Path};

mod boot;
mod exec;
mod filesystem;
mod host;
mod login;
mod plan;
mod portage;
mod services;
mod users;

pub use exec::apply_system_install_plan;
pub use plan::{
    plan_system_install, SystemInstallError, SystemInstallEvent, SystemInstallPlan,
    SystemInstallStep, SystemInstallStream,
};
pub(super) use host::{blkid_value, run_chroot, write_file, zfs_dataset_name, DiskPartitionMap};

/// The graphical autologin only makes sense when a Wayland compositor is
/// actually installed. Key off niri specifically, since that is what the
/// generated login-shell profile launches.
pub(super) fn write_wheel_sudoers(target_mount: &Path) -> Result<(), SystemInstallError> {
    use std::os::unix::fs::PermissionsExt;

    let path = target_mount.join("etc/sudoers.d/wheel");
    write_file(&path, "# generated by oxys\n%wheel ALL=(ALL:ALL) ALL\n")?;
    // sudo refuses to read drop-ins that are group/world writable.
    fs::set_permissions(&path, fs::Permissions::from_mode(0o440))?;
    Ok(())
}
