pub mod compile;
pub mod config_source;
pub mod defaults_report;
pub mod detect;
pub mod diff;
pub mod disk;
pub mod exec;
pub mod graphics;
pub mod install;
pub mod kernel_cmdline;
pub mod locales;
pub mod manifest;
pub mod package_check;
pub mod packages;
pub mod prelude;
pub mod runtime;
pub mod session;
pub mod summary;
pub mod timezones;
pub mod use_resolver;
pub mod util;

pub use detect::*;
pub use diff::*;
pub use disk::*;
pub use graphics::*;
pub use install::*;
pub use kernel_cmdline::*;
pub use manifest::*;
pub use runtime::*;
pub use session::*;
pub use summary::*;
use thiserror::Error;

/// The `#[oxys::config]` attribute: auto-fills `..Default::default()` in
/// struct literals and generates the config program's entry point.
pub use oxys_macros::config;

const GENERATED_TOML_HEADER: &str = "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n# Use `oxys compile` to regenerate this file\n";
const GENERATED_TOML_CHECKSUM_KEY: &str = "oxys_checksum_sha256";

#[derive(Debug, Error)]
pub enum GeneratedManifestError {
    #[error(
        "missing `{}` field; run `oxys compile` to regenerate manifest.toml",
        GENERATED_TOML_CHECKSUM_KEY
    )]
    MissingChecksum,
    #[error(
        "malformed `{}` field; run `oxys compile` to regenerate manifest.toml",
        GENERATED_TOML_CHECKSUM_KEY
    )]
    MalformedChecksum,
    #[error(
        "checksum mismatch in generated TOML; manual edit suspected. Run `oxys compile` to regenerate manifest.toml"
    )]
    ChecksumMismatch,
    #[error("failed to parse manifest TOML: {0}")]
    Parse(#[from] toml::de::Error),
}

pub fn manifest_to_toml(system: &manifest::SystemManifest) -> Result<String, toml::ser::Error> {
    let toml = toml::to_string(system)?;
    let body = inline_disk_subvolumes(&toml);
    Ok(wrap_generated_toml(&body))
}

pub fn parse_generated_manifest_toml(
    contents: &str,
) -> Result<manifest::SystemManifest, GeneratedManifestError> {
    let body = verified_generated_manifest_body(contents)?;
    Ok(toml::from_str(body)?)
}

/// Run a config function and write the checksummed `manifest.toml` to the
/// current directory. This is the entry point generated by `#[oxys::config]`
/// (and, for older configs, by `oxys::main!`).
pub fn run_config(config_fn: impl FnOnce() -> manifest::SystemManifest) {
    let system = config_fn();
    for warning in system.password_warnings() {
        eprintln!("warning: {warning}");
    }
    let toml = manifest_to_toml(&system).expect("failed to serialize manifest");
    std::fs::write("manifest.toml", toml).expect("failed to write manifest.toml");
    println!("manifest.toml written");
}

/// Legacy entry-point macro (`oxys::main!(config);`). Still fully supported;
/// new configs get the entry point from `#[oxys::config]` instead.
#[macro_export]
macro_rules! main {
    ($config_fn:ident) => {
        fn main() {
            $crate::run_config($config_fn);
        }
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! __services_apply_deltas {
    ($services:expr;) => {};
    ($services:expr; + $service:expr $(, $($rest:tt)*)?) => {
        {
            let service = $service.to_string();
            if !$services.iter().any(|candidate| candidate == &service) {
                $services.push(service);
            }
        }
        $($crate::__services_apply_deltas!($services; $($rest)*);)?
    };
    ($services:expr; - $service:expr $(, $($rest:tt)*)?) => {
        {
            let service = $service.to_string();
            $services.retain(|candidate| candidate != &service);
        }
        $($crate::__services_apply_deltas!($services; $($rest)*);)?
    };
}

#[macro_export]
macro_rules! services {
    (
        openrc: {
            boot_if: [$(($boot_condition:expr_2021, $conditional_boot:expr_2021)),* $(,)?],
            default: [$($default_deltas:tt)*] $(,)?
        } $(,)?
    ) => {
        {
            let mut openrc = $crate::manifest::OpenrcServices::recommended();
            $(if $boot_condition { openrc.boot.push($conditional_boot.to_string()); })*
            $crate::__services_apply_deltas!(openrc.default; $($default_deltas)*);
            $crate::manifest::Services {
                openrc,
                ..Default::default()
            }
        }
    };
    (
        openrc: {
            default: [$($default_deltas:tt)*] $(,)?
        } $(,)?
    ) => {
        {
            let mut openrc = $crate::manifest::OpenrcServices::recommended();
            $crate::__services_apply_deltas!(openrc.default; $($default_deltas)*);
            $crate::manifest::Services {
                openrc,
                ..Default::default()
            }
        }
    };
    (
        openrc: {
            sysinit: [$($sysinit:expr_2021),* $(,)?],
            boot: [$($boot:expr_2021),* $(,)?],
            boot_if: [$(($boot_condition:expr_2021, $conditional_boot:expr_2021)),* $(,)?],
            default: [$($default:expr_2021),* $(,)?],
            nonetwork: [$($nonetwork:expr_2021),* $(,)?],
            shutdown: [$($shutdown:expr_2021),* $(,)?] $(,)?
        } $(,)?
    ) => {
        $crate::manifest::Services {
            openrc: $crate::manifest::OpenrcServices {
                sysinit: vec![$($sysinit.to_string()),*],
                boot: {
                    // `mut` is unused when the caller's `boot_if:` list is empty
                    #[allow(unused_mut)]
                    let mut services = vec![$($boot.to_string()),*];
                    $(if $boot_condition { services.push($conditional_boot.to_string()); })*
                    services
                },
                default: vec![$($default.to_string()),*],
                nonetwork: vec![$($nonetwork.to_string()),*],
                shutdown: vec![$($shutdown.to_string()),*],
            },
            ..Default::default()
        }
    };
    (
        enabled: [$($enabled:expr_2021),* $(,)?],
        disabled: [$($disabled:expr_2021),* $(,)?] $(,)?
    ) => {
        $crate::manifest::Services {
            enabled: vec![$($enabled.to_string()),*],
            disabled: vec![$($disabled.to_string()),*],
            ..Default::default()
        }
    };
}

fn inline_disk_subvolumes(toml: &str) -> String {
    let mut output = Vec::new();
    let mut lines = toml.lines().peekable();
    let mut in_disk = false;
    let mut inline_entries = Vec::new();
    let mut inserted = false;

    while let Some(line) = lines.next() {
        if line == "[disk]" {
            in_disk = true;
            output.push(line.to_owned());
            continue;
        }

        if in_disk && line == "[[disk.subvolumes]]" {
            let mut name = None;
            let mut mount = None;

            while let Some(next_line) = lines.peek() {
                if next_line.is_empty() {
                    lines.next();
                    break;
                }
                if next_line.starts_with('[') {
                    break;
                }

                let entry_line = lines.next().unwrap_or_default();
                if let Some((key, value)) = entry_line.split_once(" = ") {
                    match key {
                        "name" => name = Some(value.to_owned()),
                        "mount" => mount = Some(value.to_owned()),
                        _ => {}
                    }
                }
            }

            if let (Some(name), Some(mount)) = (name, mount) {
                inline_entries.push(format!("{{ name = {name}, mount = {mount} }}"));
            }
            continue;
        }

        if in_disk && line.starts_with('[') {
            if !inserted && !inline_entries.is_empty() {
                output.push(format!("subvolumes = [{}]", inline_entries.join(", ")));
                inserted = true;
            }
            in_disk = false;
        }

        output.push(line.to_owned());
    }

    if in_disk && !inserted && !inline_entries.is_empty() {
        output.push(format!("subvolumes = [{}]", inline_entries.join(", ")));
    }

    let mut rendered = output.join("\n");
    rendered.push('\n');
    rendered
}

fn wrap_generated_toml(body: &str) -> String {
    let checksum = sha256_hex(body.as_bytes());
    format!("{GENERATED_TOML_HEADER}{GENERATED_TOML_CHECKSUM_KEY} = \"{checksum}\"\n{body}")
}

fn verified_generated_manifest_body(contents: &str) -> Result<&str, GeneratedManifestError> {
    let payload = contents
        .strip_prefix(GENERATED_TOML_HEADER)
        .unwrap_or(contents);
    let (checksum_line, body) = payload
        .split_once('\n')
        .ok_or(GeneratedManifestError::MissingChecksum)?;
    let checksum = checksum_line
        .strip_prefix(&format!("{GENERATED_TOML_CHECKSUM_KEY} = \""))
        .and_then(|value| value.strip_suffix('"'))
        .ok_or(GeneratedManifestError::MalformedChecksum)?;

    if checksum.len() != 64 || !checksum.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(GeneratedManifestError::MalformedChecksum);
    }

    if sha256_hex(body.as_bytes()) != checksum {
        return Err(GeneratedManifestError::ChecksumMismatch);
    }

    Ok(body)
}

use util::sha256_hex;

#[cfg(test)]
mod tests {
    use super::{GENERATED_TOML_HEADER, manifest_to_toml, parse_generated_manifest_toml};

    #[test]
    fn services_macro_builds_services_struct() {
        let services = crate::services! {
            enabled: ["NetworkManager", "sshd"],
            disabled: ["lvm2-monitor", "multipathd"],
        };

        assert_eq!(
            services.enabled,
            vec!["NetworkManager".to_owned(), "sshd".to_owned()]
        );
        assert_eq!(
            services.disabled,
            vec!["lvm2-monitor".to_owned(), "multipathd".to_owned()]
        );
    }

    #[test]
    fn openrc_services_macro_applies_conditional_boot_services() {
        let services = crate::services! {
            openrc: {
                sysinit: [],
                boot: ["modules"],
                boot_if: [(false, "disabled"), (true, "zram-init")],
                default: [],
                nonetwork: [],
                shutdown: [],
            },
        };

        assert_eq!(services.openrc.boot, vec!["modules", "zram-init"]);
    }

    #[test]
    fn openrc_services_macro_applies_deltas_to_recommended_services() {
        let services = crate::services! {
            openrc: {
                default: [+"sshd", -"modemmanager", +"sshd"],
            },
        };

        assert_eq!(
            services.openrc.default,
            ["local", "netmount", "nftables", "NetworkManager", "sshd"]
        );
        assert_eq!(
            services.openrc.sysinit,
            crate::manifest::OpenrcServices::recommended().sysinit
        );
    }

    #[test]
    fn openrc_services_delta_macro_applies_conditional_boot_services() {
        let services = crate::services! {
            openrc: {
                boot_if: [(false, "disabled"), (true, "zram-init")],
                default: [],
            },
        };

        assert_eq!(
            services.openrc.boot.last().map(String::as_str),
            Some("zram-init")
        );
        assert!(!services.openrc.contains("disabled"));
    }

    #[test]
    fn manifest_writer_inlines_disk_subvolumes() {
        // Subvolumes only belong to (and are only serialized for) a btrfs
        // layout; this exercises the inline-array formatting for that case.
        let manifest = crate::SystemManifest {
            disk: crate::Disk {
                layout: crate::manifest::DiskLayout::Btrfs,
                ..crate::Disk::default()
            },
            ..crate::SystemManifest::default()
        };

        let toml = manifest_to_toml(&manifest).expect("manifest should serialize");

        assert!(toml.contains(
            "subvolumes = [{ name = \"@\", mount = \"/\" }, { name = \"@home\", mount = \"/home\" }, { name = \"@snapshots\", mount = \"/.snapshots\" }, { name = \"@log\", mount = \"/var/log\" }, { name = \"@pkg\", mount = \"/var/cache/portage\" }]"
        ));
        assert!(!toml.contains("[[disk.subvolumes]]"));
        assert!(toml.starts_with(GENERATED_TOML_HEADER));
        assert!(toml.contains("oxys_checksum_sha256 = \""));
    }

    #[test]
    fn ext4_manifest_omits_zfs_and_subvolumes() {
        let manifest = crate::SystemManifest {
            disk: crate::Disk {
                layout: crate::manifest::DiskLayout::Ext4,
                ..crate::Disk::default()
            },
            ..crate::SystemManifest::default()
        };

        let toml = manifest_to_toml(&manifest).expect("manifest should serialize");

        assert!(toml.contains("[disk.ext4]"));
        assert!(!toml.contains("[disk.zfs]"));
        assert!(!toml.contains("disk.zfs.datasets"));
        assert!(!toml.contains("subvolumes ="));
    }

    #[test]
    fn generated_manifest_round_trips_through_checksum_verification() {
        let manifest = crate::SystemManifest::default();
        let toml = manifest_to_toml(&manifest).expect("manifest should serialize");

        // parse verifies the checksum; regenerating from the parsed manifest is
        // a fixed point. We assert TOML idempotency rather than in-memory struct
        // equality because `Disk::default()` carries btrfs subvolumes even in
        // ext4 mode, and those are intentionally not serialized for ext4.
        let parsed = parse_generated_manifest_toml(&toml).expect("manifest should verify");
        let reserialized = manifest_to_toml(&parsed).expect("parsed manifest should serialize");

        assert_eq!(reserialized, toml);
    }

    #[test]
    fn generated_manifest_rejects_manual_edits() {
        let manifest = crate::SystemManifest::default();
        let toml = manifest_to_toml(&manifest).expect("manifest should serialize");
        let edited = toml.replacen("[os]\n", "[os]\nhostname = \"tampered\"\n", 1);

        let error = parse_generated_manifest_toml(&edited).expect_err("checksum must fail");

        assert!(matches!(
            error,
            crate::GeneratedManifestError::ChecksumMismatch
        ));
        assert!(error.to_string().contains("oxys compile"));
        assert!(!error.to_string().contains("oxys build"));
    }
}
