pub mod compile;
pub mod detect;
pub mod diff;
pub mod disk;
pub mod exec;
pub mod install;
pub mod manifest;
pub mod prelude;
pub mod runtime;
pub mod summary;
pub mod use_resolver;
pub mod util;

pub use detect::*;
pub use diff::*;
pub use disk::*;
pub use install::*;
pub use manifest::*;
pub use runtime::*;
pub use summary::*;
use thiserror::Error;

const GENERATED_TOML_HEADER: &str =
    "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n# Use `oxys compile` to regenerate this file\n";
const GENERATED_TOML_CHECKSUM_KEY: &str = "oxys_checksum_sha256";

#[derive(Debug, Error)]
pub enum GeneratedManifestError {
    #[error(
        "missing `{}` field; run `oxys compile` to regenerate manifest.toml",
        GENERATED_TOML_CHECKSUM_KEY
    )]
    MissingChecksum,
    #[error(
        "malformed `{}` field; run `oxys compile` to regenerate manifest.toml",
        GENERATED_TOML_CHECKSUM_KEY
    )]
    MalformedChecksum,
    #[error(
        "checksum mismatch in generated TOML; manual edit suspected. Run `oxys compile` to regenerate manifest.toml"
    )]
    ChecksumMismatch,
    #[error("failed to parse manifest TOML: {0}")]
    Parse(#[from] toml::de::Error),
}

pub fn manifest_to_toml(system: &manifest::SystemManifest) -> Result<String, toml::ser::Error> {
    let toml = toml::to_string(system)?;
    let body = inline_disk_subvolumes(&toml);
    Ok(wrap_generated_toml(&body))
}

pub fn parse_generated_manifest_toml(
    contents: &str,
) -> Result<manifest::SystemManifest, GeneratedManifestError> {
    let body = verified_generated_manifest_body(contents)?;
    Ok(toml::from_str(body)?)
}

#[macro_export]
macro_rules! main {
    ($config_fn:ident) => {
        fn main() {
            let system = $config_fn();
            for warning in system.password_warnings() {
                eprintln!("warning: {}", warning);
            }
            let toml = $crate::manifest_to_toml(&system).expect("failed to serialize manifest");
            std::fs::write("manifest.toml", toml).expect("failed to write manifest.toml");
            println!("manifest.toml written");
        }
    };
}

#[macro_export]
macro_rules! services {
    (
        enabled: [$($enabled:expr_2021),* $(,)?],
        disabled: [$($disabled:expr_2021),* $(,)?] $(,)?
    ) => {
        $crate::manifest::Services {
            enabled: vec![$($enabled.to_string()),*],
            disabled: vec![$($disabled.to_string()),*],
        }
    };
}

fn inline_disk_subvolumes(toml: &str) -> String {
    let mut output = Vec::new();
    let mut lines = toml.lines().peekable();
    let mut in_disk = false;
    let mut inline_entries = Vec::new();
    let mut inserted = false;

    while let Some(line) = lines.next() {
        if line == "[disk]" {
            in_disk = true;
            output.push(line.to_owned());
            continue;
        }

        if in_disk && line == "[[disk.subvolumes]]" {
            let mut name = None;
            let mut mount = None;

            while let Some(next_line) = lines.peek() {
                if next_line.is_empty() {
                    lines.next();
                    break;
                }
                if next_line.starts_with('[') {
                    break;
                }

                let entry_line = lines.next().unwrap_or_default();
                if let Some((key, value)) = entry_line.split_once(" = ") {
                    match key {
                        "name" => name = Some(value.to_owned()),
                        "mount" => mount = Some(value.to_owned()),
                        _ => {}
                    }
                }
            }

            if let (Some(name), Some(mount)) = (name, mount) {
                inline_entries.push(format!("{{ name = {name}, mount = {mount} }}"));
            }
            continue;
        }

        if in_disk && line.starts_with('[') {
            if !inserted && !inline_entries.is_empty() {
                output.push(format!("subvolumes = [{}]", inline_entries.join(", ")));
                inserted = true;
            }
            in_disk = false;
        }

        output.push(line.to_owned());
    }

    if in_disk && !inserted && !inline_entries.is_empty() {
        output.push(format!("subvolumes = [{}]", inline_entries.join(", ")));
    }

    let mut rendered = output.join("\n");
    rendered.push('\n');
    rendered
}

fn wrap_generated_toml(body: &str) -> String {
    let checksum = sha256_hex(body.as_bytes());
    format!("{GENERATED_TOML_HEADER}{GENERATED_TOML_CHECKSUM_KEY} = \"{checksum}\"\n{body}")
}

fn verified_generated_manifest_body(contents: &str) -> Result<&str, GeneratedManifestError> {
    let payload = contents
        .strip_prefix(GENERATED_TOML_HEADER)
        .unwrap_or(contents);
    let (checksum_line, body) = payload
        .split_once('\n')
        .ok_or(GeneratedManifestError::MissingChecksum)?;
    let checksum = checksum_line
        .strip_prefix(&format!("{GENERATED_TOML_CHECKSUM_KEY} = \""))
        .and_then(|value| value.strip_suffix('"'))
        .ok_or(GeneratedManifestError::MalformedChecksum)?;

    if checksum.len() != 64 || !checksum.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(GeneratedManifestError::MalformedChecksum);
    }

    if sha256_hex(body.as_bytes()) != checksum {
        return Err(GeneratedManifestError::ChecksumMismatch);
    }

    Ok(body)
}

use util::sha256_hex;

#[cfg(test)]
mod tests {
    use super::{manifest_to_toml, parse_generated_manifest_toml, GENERATED_TOML_HEADER};

    #[test]
    fn services_macro_builds_services_struct() {
        let services = crate::services! {
            enabled: ["NetworkManager", "sshd"],
            disabled: ["lvm2-monitor", "multipathd"],
        };

        assert_eq!(
            services.enabled,
            vec!["NetworkManager".to_owned(), "sshd".to_owned()]
        );
        assert_eq!(
            services.disabled,
            vec!["lvm2-monitor".to_owned(), "multipathd".to_owned()]
        );
    }

    #[test]
    fn manifest_writer_inlines_disk_subvolumes() {
        // Subvolumes only belong to (and are only serialized for) a btrfs
        // layout; this exercises the inline-array formatting for that case.
        let manifest = crate::SystemManifest {
            disk: crate::Disk {
                layout: crate::manifest::DiskLayout::Btrfs,
                ..crate::Disk::default()
            },
            ..crate::SystemManifest::default()
        };

        let toml = manifest_to_toml(&manifest).expect("manifest should serialize");

        assert!(toml.contains(
            "subvolumes = [{ name = \"@\", mount = \"/\" }, { name = \"@home\", mount = \"/home\" }, { name = \"@snapshots\", mount = \"/.snapshots\" }, { name = \"@log\", mount = \"/var/log\" }, { name = \"@pkg\", mount = \"/var/cache/portage\" }]"
        ));
        assert!(!toml.contains("[[disk.subvolumes]]"));
        assert!(toml.starts_with(GENERATED_TOML_HEADER));
        assert!(toml.contains("oxys_checksum_sha256 = \""));
    }

    #[test]
    fn ext4_manifest_omits_zfs_and_subvolumes() {
        let manifest = crate::SystemManifest {
            disk: crate::Disk {
                layout: crate::manifest::DiskLayout::Ext4,
                ..crate::Disk::default()
            },
            ..crate::SystemManifest::default()
        };

        let toml = manifest_to_toml(&manifest).expect("manifest should serialize");

        assert!(toml.contains("[disk.ext4]"));
        assert!(!toml.contains("[disk.zfs]"));
        assert!(!toml.contains("disk.zfs.datasets"));
        assert!(!toml.contains("subvolumes ="));
    }

    #[test]
    fn generated_manifest_round_trips_through_checksum_verification() {
        let manifest = crate::SystemManifest::default();
        let toml = manifest_to_toml(&manifest).expect("manifest should serialize");

        // parse verifies the checksum; regenerating from the parsed manifest is
        // a fixed point. We assert TOML idempotency rather than in-memory struct
        // equality because `Disk::default()` carries btrfs subvolumes even in
        // ext4 mode, and those are intentionally not serialized for ext4.
        let parsed = parse_generated_manifest_toml(&toml).expect("manifest should verify");
        let reserialized = manifest_to_toml(&parsed).expect("parsed manifest should serialize");

        assert_eq!(reserialized, toml);
    }

    #[test]
    fn generated_manifest_rejects_manual_edits() {
        let manifest = crate::SystemManifest::default();
        let toml = manifest_to_toml(&manifest).expect("manifest should serialize");
        let edited = toml.replacen("[os]\n", "[os]\nhostname = \"tampered\"\n", 1);

        let error = parse_generated_manifest_toml(&edited).expect_err("checksum must fail");

        assert!(matches!(
            error,
            crate::GeneratedManifestError::ChecksumMismatch
        ));
        assert!(error.to_string().contains("oxys compile"));
        assert!(!error.to_string().contains("oxys build"));
    }
}
