use std::{
    fs,
    os::unix::fs::PermissionsExt,
    path::{Path, PathBuf},
};

use thiserror::Error;

use crate::manifest::{Gpu, GpuVendor, SystemManifest};
const PRIME_ENV_PATH: &str = "etc/environment.d/90-oxys-prime-offload.conf";
const PRIME_PROFILE_PATH: &str = "etc/profile.d/oxys-prime-offload.sh";
const PRIME_MODPROBE_PATH: &str = "etc/modprobe.d/oxys-nvidia-prime.conf";
const PRIME_RUN_PATH: &str = "usr/local/bin/prime-run";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RuntimeConfigOutcome {
    pub prime_offload_configured: bool,
}

#[derive(Debug, Error)]
pub enum RuntimeConfigError {
    #[error("failed to create directory {path}: {source}")]
    CreateDir {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to write runtime config {path}: {source}")]
    WriteFile {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to set permissions on {path}: {source}")]
    SetPermissions {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to remove stale runtime config {path}: {source}")]
    RemoveFile {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
}

pub fn sync_runtime_config(
    manifest: &SystemManifest,
    root: &Path,
) -> Result<RuntimeConfigOutcome, RuntimeConfigError> {
    let mode = prime_mode(&manifest.hardware.gpu);
    let files = [
        GeneratedFile {
            path: root.join(PRIME_ENV_PATH),
            contents: mode.map(render_prime_environment),
            mode: 0o644,
        },
        GeneratedFile {
            path: root.join(PRIME_PROFILE_PATH),
            contents: mode.map(render_prime_profile),
            mode: 0o644,
        },
        GeneratedFile {
            path: root.join(PRIME_MODPROBE_PATH),
            contents: mode.map(render_prime_modprobe),
            mode: 0o644,
        },
        GeneratedFile {
            path: root.join(PRIME_RUN_PATH),
            contents: mode.map(render_prime_run),
            mode: 0o755,
        },
    ];

    let mut configured = false;
    for file in files {
        match file.contents {
            Some(contents) => {
                configured = true;
                write_generated_file(&file.path, contents, file.mode)?;
            }
            None => remove_if_exists(&file.path)?,
        }
    }

    Ok(RuntimeConfigOutcome {
        prime_offload_configured: configured,
    })
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum PrimeMode {
    IntelNvidia,
    AmdNvidia,
}

struct GeneratedFile {
    path: PathBuf,
    contents: Option<&'static str>,
    mode: u32,
}

fn prime_mode(gpu: &Gpu) -> Option<PrimeMode> {
    match gpu {
        Gpu::Hybrid {
            igpu: GpuVendor::Intel,
            dgpu: GpuVendor::Nvidia,
        } => Some(PrimeMode::IntelNvidia),
        Gpu::Hybrid {
            igpu: GpuVendor::Amd,
            dgpu: GpuVendor::Nvidia,
        } => Some(PrimeMode::AmdNvidia),
        _ => None,
    }
}

fn render_prime_environment(mode: PrimeMode) -> &'static str {
    match mode {
        PrimeMode::IntelNvidia => concat!(
            "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
            "# Update your OXYS config and rerun `oxys apply` to regenerate this file\n",
            "# Intel iGPU + NVIDIA dGPU PRIME render offload defaults\n",
            "__NV_PRIME_RENDER_OFFLOAD=1\n",
            "__GLX_VENDOR_LIBRARY_NAME=nvidia\n",
            "__VK_LAYER_NV_optimus=NVIDIA_only\n",
            "LIBVA_DRIVER_NAME=nvidia\n"
        ),
        PrimeMode::AmdNvidia => concat!(
            "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
            "# Update your OXYS config and rerun `oxys apply` to regenerate this file\n",
            "# AMD iGPU + NVIDIA dGPU PRIME render offload defaults\n",
            "__NV_PRIME_RENDER_OFFLOAD=1\n",
            "__GLX_VENDOR_LIBRARY_NAME=nvidia\n",
            "__VK_LAYER_NV_optimus=NVIDIA_only\n",
            "LIBVA_DRIVER_NAME=nvidia\n"
        ),
    }
}

fn render_prime_profile(mode: PrimeMode) -> &'static str {
    match mode {
        PrimeMode::IntelNvidia => concat!(
            "#!/bin/sh\n",
            "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
            "# Intel iGPU + NVIDIA dGPU PRIME render offload defaults\n",
            "export __NV_PRIME_RENDER_OFFLOAD=1\n",
            "export __GLX_VENDOR_LIBRARY_NAME=nvidia\n",
            "export __VK_LAYER_NV_optimus=NVIDIA_only\n",
            "export LIBVA_DRIVER_NAME=nvidia\n"
        ),
        PrimeMode::AmdNvidia => concat!(
            "#!/bin/sh\n",
            "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
            "# AMD iGPU + NVIDIA dGPU PRIME render offload defaults\n",
            "export __NV_PRIME_RENDER_OFFLOAD=1\n",
            "export __GLX_VENDOR_LIBRARY_NAME=nvidia\n",
            "export __VK_LAYER_NV_optimus=NVIDIA_only\n",
            "export LIBVA_DRIVER_NAME=nvidia\n"
        ),
    }
}

fn render_prime_modprobe(mode: PrimeMode) -> &'static str {
    match mode {
        PrimeMode::IntelNvidia => concat!(
            "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
            "# Update your OXYS config and rerun `oxys apply` to regenerate this file\n",
            "# Intel iGPU + NVIDIA dGPU PRIME requires DRM KMS on the NVIDIA stack\n",
            "options nvidia-drm modeset=1\n"
        ),
        PrimeMode::AmdNvidia => concat!(
            "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
            "# Update your OXYS config and rerun `oxys apply` to regenerate this file\n",
            "# AMD iGPU + NVIDIA dGPU PRIME requires DRM KMS on the NVIDIA stack\n",
            "options nvidia-drm modeset=1\n"
        ),
    }
}

fn render_prime_run(mode: PrimeMode) -> &'static str {
    match mode {
        PrimeMode::IntelNvidia => concat!(
            "#!/bin/sh\n",
            "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
            "# Intel iGPU + NVIDIA dGPU PRIME wrapper\n",
            "export __NV_PRIME_RENDER_OFFLOAD=1\n",
            "export __GLX_VENDOR_LIBRARY_NAME=nvidia\n",
            "export __VK_LAYER_NV_optimus=NVIDIA_only\n",
            "export LIBVA_DRIVER_NAME=nvidia\n",
            "exec \"$@\"\n"
        ),
        PrimeMode::AmdNvidia => concat!(
            "#!/bin/sh\n",
            "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
            "# AMD iGPU + NVIDIA dGPU PRIME wrapper\n",
            "export __NV_PRIME_RENDER_OFFLOAD=1\n",
            "export __GLX_VENDOR_LIBRARY_NAME=nvidia\n",
            "export __VK_LAYER_NV_optimus=NVIDIA_only\n",
            "export LIBVA_DRIVER_NAME=nvidia\n",
            "exec \"$@\"\n"
        ),
    }
}

fn write_generated_file(path: &Path, contents: &str, mode: u32) -> Result<(), RuntimeConfigError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| RuntimeConfigError::CreateDir {
            path: parent.to_path_buf(),
            source,
        })?;
    }

    fs::write(path, contents).map_err(|source| RuntimeConfigError::WriteFile {
        path: path.to_path_buf(),
        source,
    })?;
    fs::set_permissions(path, fs::Permissions::from_mode(mode)).map_err(|source| {
        RuntimeConfigError::SetPermissions {
            path: path.to_path_buf(),
            source,
        }
    })?;
    Ok(())
}

fn remove_if_exists(path: &Path) -> Result<(), RuntimeConfigError> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(source) => Err(RuntimeConfigError::RemoveFile {
            path: path.to_path_buf(),
            source,
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn writes_prime_files_for_amd_nvidia_hybrid() -> Result<(), Box<dyn std::error::Error>> {
        let root = test_root("amd_nvidia_prime");
        let manifest = SystemManifest {
            hardware: crate::manifest::Hardware {
                gpu: Gpu::Hybrid {
                    igpu: GpuVendor::Amd,
                    dgpu: GpuVendor::Nvidia,
                },
                ..crate::manifest::Hardware::default()
            },
            ..SystemManifest::default()
        };

        let outcome = sync_runtime_config(&manifest, &root)?;

        assert!(outcome.prime_offload_configured);
        assert!(fs::read_to_string(root.join(PRIME_ENV_PATH))?.contains("AMD iGPU + NVIDIA dGPU"));
        assert!(fs::read_to_string(root.join(PRIME_MODPROBE_PATH))?.contains("modeset=1"));
        assert!(fs::read_to_string(root.join(PRIME_RUN_PATH))?.contains("exec \"$@\""));

        cleanup(&root)?;
        Ok(())
    }

    #[test]
    fn removes_prime_files_when_gpu_is_not_nvidia_hybrid() -> Result<(), Box<dyn std::error::Error>>
    {
        let root = test_root("prime_cleanup");
        let hybrid = SystemManifest {
            hardware: crate::manifest::Hardware {
                gpu: Gpu::Hybrid {
                    igpu: GpuVendor::Intel,
                    dgpu: GpuVendor::Nvidia,
                },
                ..crate::manifest::Hardware::default()
            },
            ..SystemManifest::default()
        };
        let single = SystemManifest {
            hardware: crate::manifest::Hardware {
                gpu: Gpu::Single(GpuVendor::Intel),
                ..crate::manifest::Hardware::default()
            },
            ..SystemManifest::default()
        };

        sync_runtime_config(&hybrid, &root)?;
        let outcome = sync_runtime_config(&single, &root)?;

        assert!(!outcome.prime_offload_configured);
        assert!(!root.join(PRIME_ENV_PATH).exists());
        assert!(!root.join(PRIME_PROFILE_PATH).exists());
        assert!(!root.join(PRIME_MODPROBE_PATH).exists());
        assert!(!root.join(PRIME_RUN_PATH).exists());

        cleanup(&root)?;
        Ok(())
    }

    #[test]
    fn does_not_configure_prime_for_non_nvidia_hybrid() -> Result<(), Box<dyn std::error::Error>> {
        let root = test_root("intel_amd_hybrid");
        let manifest = SystemManifest {
            hardware: crate::manifest::Hardware {
                gpu: Gpu::Hybrid {
                    igpu: GpuVendor::Intel,
                    dgpu: GpuVendor::Amd,
                },
                ..crate::manifest::Hardware::default()
            },
            ..SystemManifest::default()
        };

        let outcome = sync_runtime_config(&manifest, &root)?;

        assert!(!outcome.prime_offload_configured);
        assert!(!root.join(PRIME_ENV_PATH).exists());

        cleanup(&root)?;
        Ok(())
    }

    fn test_root(name: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time should move forward")
            .as_nanos();
        std::env::temp_dir().join(format!("oxys_runtime_{name}_{nanos}"))
    }

    fn cleanup(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
        if path.exists() {
            fs::remove_dir_all(path)?;
        }
        Ok(())
    }
}
