use std::{
    fs,
    os::unix::fs::PermissionsExt,
    path::{Path, PathBuf},
};

use thiserror::Error;

use crate::manifest::{
    Firewall, FirewallValidationError, Graphics, InitSystem, MB, NvidiaDriver,
    PrimeMode as GraphicsPrimeMode, ResolvedSwap, SwapResolveError, SystemManifest, VideoCard,
    VideoCards,
};
const PRIME_ENV_PATH: &str = "etc/environment.d/90-oxys-nvidia-primary.conf";
const PRIME_PROFILE_PATH: &str = "etc/profile.d/oxys-nvidia-primary.sh";
const LEGACY_PRIME_ENV_PATH: &str = "etc/environment.d/90-oxys-prime-offload.conf";
const LEGACY_PRIME_PROFILE_PATH: &str = "etc/profile.d/oxys-prime-offload.sh";
const PRIME_MODPROBE_PATH: &str = "etc/modprobe.d/oxys-nvidia-prime.conf";
const NVIDIA_BLACKLIST_PATH: &str = "etc/modprobe.d/oxys-nvidia-stack.conf";
const PRIME_RUN_PATH: &str = "usr/local/bin/prime-run";
const GRAPHICS_DIAGNOSTICS_PATH: &str = "usr/local/bin/oxys-graphics-diagnostics";
const SWAP_SYSCTL_PATH: &str = "etc/sysctl.d/90-oxys-swap.conf";
const ZRAM_CONF_PATH: &str = "etc/conf.d/zram-init";
const ZRAM_INIT_PATH: &str = "etc/init.d/zram-init";
/// Where Gentoo's OpenRC `nftables` service loads the ruleset from at boot.
pub const NFTABLES_RULES_PATH: &str = "var/lib/nftables/rules-save";
pub const NFTABLES_CONF_PATH: &str = "etc/conf.d/nftables";
const GENERATED_FILE_MARKER: &str = "AUTO-GENERATED BY OXYS";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RuntimeConfigOutcome {
    pub prime_offload_configured: bool,
    pub prime_primary_configured: bool,
    pub graphics_diagnostics_configured: bool,
    pub swap_configured: bool,
    pub firewall_configured: bool,
}

#[derive(Debug, Error)]
pub enum RuntimeConfigError {
    #[error("failed to create directory {path}: {source}")]
    CreateDir {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to write runtime config {path}: {source}")]
    WriteFile {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to set permissions on {path}: {source}")]
    SetPermissions {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to remove stale runtime config {path}: {source}")]
    RemoveFile {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("zram is requested but {0} is missing; install sys-block/zram-init")]
    MissingZramInit(PathBuf),
    #[error("zram runtime provisioning requires OpenRC (configured init system: {0:?})")]
    UnsupportedZramInit(InitSystem),
    #[error("failed to create runtime symlink {path}: {source}")]
    CreateSymlink {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error(transparent)]
    InvalidSwap(#[from] SwapResolveError),
    #[error(transparent)]
    InvalidFirewall(#[from] FirewallValidationError),
    #[error("failed to run nft to validate {path}: {source}")]
    FirewallCheckExec {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("generated nftables ruleset {path} failed `nft -c -f`: {stderr}")]
    FirewallRulesInvalid { path: PathBuf, stderr: String },
}

pub fn sync_runtime_config(
    manifest: &SystemManifest,
    root: &Path,
) -> Result<RuntimeConfigOutcome, RuntimeConfigError> {
    let resolved_swap = manifest.resolved_swap()?;
    if resolved_swap.zram.is_some() && manifest.init_system != InitSystem::Openrc {
        return Err(RuntimeConfigError::UnsupportedZramInit(
            manifest.init_system,
        ));
    }
    let mut outcome = sync_graphics_runtime_config(manifest, root)?;
    sync_swap_config(&resolved_swap, root)?;
    outcome.swap_configured = resolved_swap.zram.is_some() || resolved_swap.disk.is_some();
    outcome.firewall_configured = sync_firewall_config(manifest, root)?;
    Ok(outcome)
}

pub fn sync_graphics_runtime_config(
    manifest: &SystemManifest,
    root: &Path,
) -> Result<RuntimeConfigOutcome, RuntimeConfigError> {
    let mode = prime_mode(&manifest.hardware.graphics);
    let proprietary_modeset = manifest
        .hardware
        .graphics
        .nvidia
        .is_some_and(|nvidia| nvidia.driver == NvidiaDriver::Proprietary && nvidia.modeset);
    let files = [
        GeneratedFile {
            path: root.join(PRIME_ENV_PATH),
            contents: (mode == Some(PrimeMode::Primary)).then_some(render_prime_environment()),
            mode: 0o644,
        },
        GeneratedFile {
            path: root.join(PRIME_PROFILE_PATH),
            contents: (mode == Some(PrimeMode::Primary)).then_some(render_prime_profile()),
            mode: 0o644,
        },
        GeneratedFile {
            path: root.join(PRIME_MODPROBE_PATH),
            contents: proprietary_modeset.then_some(render_prime_modprobe()),
            mode: 0o644,
        },
        GeneratedFile {
            path: root.join(PRIME_RUN_PATH),
            contents: mode.and_then(|mode| match mode {
                PrimeMode::OffloadIntel | PrimeMode::OffloadAmd => Some(render_prime_run(mode)),
                PrimeMode::Primary => None,
            }),
            mode: 0o755,
        },
        GeneratedFile {
            path: root.join(NVIDIA_BLACKLIST_PATH),
            contents: render_nvidia_blacklist(&manifest.hardware.graphics),
            mode: 0o644,
        },
        GeneratedFile {
            path: root.join(GRAPHICS_DIAGNOSTICS_PATH),
            contents: Some(GRAPHICS_DIAGNOSTICS),
            mode: 0o755,
        },
    ];

    for file in files {
        match file.contents {
            Some(contents) => {
                write_generated_file(&file.path, contents, file.mode)?;
            }
            None => remove_if_exists(&file.path)?,
        }
    }
    remove_if_exists(&root.join(LEGACY_PRIME_ENV_PATH))?;
    remove_if_exists(&root.join(LEGACY_PRIME_PROFILE_PATH))?;

    Ok(RuntimeConfigOutcome {
        prime_offload_configured: matches!(
            mode,
            Some(PrimeMode::OffloadIntel | PrimeMode::OffloadAmd)
        ),
        prime_primary_configured: mode == Some(PrimeMode::Primary),
        graphics_diagnostics_configured: true,
        swap_configured: false,
        firewall_configured: false,
    })
}

pub fn sync_swap_config(
    resolved_swap: &ResolvedSwap,
    root: &Path,
) -> Result<(), RuntimeConfigError> {
    write_generated_file(
        &root.join(SWAP_SYSCTL_PATH),
        &format!(
            "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\nvm.swappiness = {}\n",
            resolved_swap.swappiness
        ),
        0o644,
    )?;

    let zram_conf = root.join(ZRAM_CONF_PATH);
    let Some(zram) = &resolved_swap.zram else {
        remove_if_exists(&zram_conf)?;
        return Ok(());
    };

    let init_script = root.join(ZRAM_INIT_PATH);
    if !init_script.is_file() {
        return Err(RuntimeConfigError::MissingZramInit(init_script));
    }

    let size_mib = zram.size.div_ceil(MB).max(1);
    let config = format!(
        concat!(
            "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
            "load_on_start=yes\n",
            "unload_on_stop=yes\n",
            "num_devices=1\n",
            "type0=swap\n",
            "size0={}\n",
            "flag0={}\n",
            "algo0={}\n"
        ),
        size_mib,
        zram.priority,
        zram.algorithm.kernel_name()
    );
    write_generated_file(&zram_conf, &config, 0o644)?;

    Ok(())
}

/// Render and stage the manifest's firewall policy under `root`.
///
/// Enabled: validates the manifest (package + OpenRC service must be
/// declared), renders the ruleset deterministically, stages it next to the
/// live file, checks it with `nft -c -f` when nft is available (the ISO build
/// asserts nft exists there; dev machines without it skip the check), and only
/// then renames it into place with mode 0600. The `/etc/conf.d/nftables`
/// policy is pinned to `SAVE_ON_STOP="no"` so an OpenRC shutdown can never
/// overwrite Oxys-managed rules with transient runtime state.
///
/// Disabled: removes both files, but only if Oxys generated them — a
/// hand-managed rules-save is never deleted.
///
/// This never loads rules into the running kernel, so installing to a mounted
/// target cannot disturb the live host's ruleset; `oxys apply` performs the
/// reload separately after this succeeds.
pub fn sync_firewall_config(
    manifest: &SystemManifest,
    root: &Path,
) -> Result<bool, RuntimeConfigError> {
    manifest.validate_firewall()?;
    let rules_path = root.join(NFTABLES_RULES_PATH);
    let conf_path = root.join(NFTABLES_CONF_PATH);
    let Some(rules) = render_nftables_rules(&manifest.firewall) else {
        remove_if_generated_by_oxys(&rules_path)?;
        remove_if_generated_by_oxys(&conf_path)?;
        return Ok(false);
    };

    let staged_path = rules_path.with_extension("oxys-staged");
    write_generated_file(&staged_path, &rules, 0o600)?;
    if let Err(error) = check_nftables_rules(&staged_path) {
        let _ = fs::remove_file(&staged_path);
        return Err(error);
    }
    fs::rename(&staged_path, &rules_path).map_err(|source| RuntimeConfigError::WriteFile {
        path: rules_path.clone(),
        source,
    })?;
    write_generated_file(&conf_path, NFTABLES_CONF_CONTENTS, 0o644)?;
    Ok(true)
}

/// Deterministically render the nftables ruleset for a firewall policy.
/// Returns `None` when the firewall is disabled. The output starts with
/// `flush ruleset`, so loading the file with `nft -f` atomically replaces any
/// previous ruleset.
pub fn render_nftables_rules(firewall: &Firewall) -> Option<String> {
    let Firewall::Nftables {
        incoming,
        forwarding,
        outgoing,
        allow_icmp,
        tcp_ports,
        udp_ports,
    } = firewall
    else {
        return None;
    };

    let mut rules = String::from(concat!(
        "#!/sbin/nft -f\n",
        "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
        "# Rendered from the Oxys manifest firewall policy.\n",
        "\n",
        "flush ruleset\n",
        "\n",
        "table inet oxys {\n",
    ));
    rules.push_str(&format!(
        "\tchain input {{\n\t\ttype filter hook input priority filter; policy {};\n",
        incoming.keyword()
    ));
    rules.push_str("\t\tiif \"lo\" accept\n");
    rules.push_str("\t\tct state established,related accept\n");
    rules.push_str("\t\tct state invalid drop\n");
    if *allow_icmp {
        rules.push_str("\t\tmeta l4proto { icmp, ipv6-icmp } accept\n");
    }
    // DHCP client replies: broadcast/relayed DHCPv4 offers and DHCPv6
    // advertisements are not always matched by conntrack as replies, so allow
    // them explicitly (server port -> client port).
    rules.push_str("\t\tudp sport 67 udp dport 68 accept\n");
    rules.push_str("\t\tudp sport 547 udp dport 546 accept\n");
    if let Some(ports) = render_port_set(tcp_ports) {
        rules.push_str(&format!("\t\ttcp dport {ports} accept\n"));
    }
    if let Some(ports) = render_port_set(udp_ports) {
        rules.push_str(&format!("\t\tudp dport {ports} accept\n"));
    }
    rules.push_str("\t}\n");
    rules.push_str(&format!(
        "\tchain forward {{\n\t\ttype filter hook forward priority filter; policy {};\n\t}}\n",
        forwarding.keyword()
    ));
    rules.push_str(&format!(
        "\tchain output {{\n\t\ttype filter hook output priority filter; policy {};\n\t}}\n",
        outgoing.keyword()
    ));
    rules.push_str("}\n");
    Some(rules)
}

/// Canonical (sorted, deduplicated) nftables port set, or `None` when empty.
fn render_port_set(ports: &[u16]) -> Option<String> {
    if ports.is_empty() {
        return None;
    }
    let mut ports = ports.to_vec();
    ports.sort_unstable();
    ports.dedup();
    let rendered = ports
        .iter()
        .map(|port| port.to_string())
        .collect::<Vec<_>>()
        .join(", ");
    Some(format!("{{ {rendered} }}"))
}

const NFTABLES_CONF_CONTENTS: &str = concat!(
    "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
    "# /var/lib/nftables/rules-save is rendered from the Oxys manifest. Never\n",
    "# let `rc-service nftables stop` overwrite it with whatever transient rules\n",
    "# (NetworkManager, containers) happened to be loaded at shutdown.\n",
    "SAVE_ON_STOP=\"no\"\n",
);

/// Check a staged ruleset with `nft -c -f` before it replaces the live file.
///
/// Skipped without root: even in check mode nft opens a netlink socket, which
/// needs CAP_NET_ADMIN, so an unprivileged run (unit tests, dev machines)
/// would fail with EPERM on a perfectly valid ruleset. Every real consumer —
/// the installer, `oxys apply`, and the ISO fsscript assertion — runs as root.
/// A missing nft binary is also not an error: the ISO build asserts nft is
/// present on any image that enables the firewall, and rules are re-validated
/// there.
fn check_nftables_rules(path: &Path) -> Result<(), RuntimeConfigError> {
    if !rustix::process::geteuid().is_root() {
        return Ok(());
    }
    let output = match std::process::Command::new("nft")
        .arg("-c")
        .arg("-f")
        .arg(path)
        .output()
    {
        Ok(output) => output,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(source) => {
            return Err(RuntimeConfigError::FirewallCheckExec {
                path: path.to_path_buf(),
                source,
            });
        }
    };
    if !output.status.success() {
        return Err(RuntimeConfigError::FirewallRulesInvalid {
            path: path.to_path_buf(),
            stderr: String::from_utf8_lossy(&output.stderr).trim().to_owned(),
        });
    }
    Ok(())
}

/// Remove a file only when Oxys generated it (per its header marker), so a
/// disabled firewall never deletes hand-managed nftables state.
fn remove_if_generated_by_oxys(path: &Path) -> Result<(), RuntimeConfigError> {
    let Ok(contents) = fs::read_to_string(path) else {
        return Ok(());
    };
    if contents
        .lines()
        .take(2)
        .any(|line| line.contains(GENERATED_FILE_MARKER))
    {
        remove_if_exists(path)?;
    }
    Ok(())
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum PrimeMode {
    Primary,
    OffloadIntel,
    OffloadAmd,
}

struct GeneratedFile {
    path: PathBuf,
    contents: Option<&'static str>,
    mode: u32,
}

fn prime_mode(graphics: &Graphics) -> Option<PrimeMode> {
    let nvidia = graphics.nvidia?;
    if nvidia.driver != NvidiaDriver::Proprietary {
        return None;
    }
    if nvidia.prime == GraphicsPrimeMode::Primary {
        return Some(PrimeMode::Primary);
    }
    if nvidia.prime != GraphicsPrimeMode::Offload {
        return None;
    }
    match &graphics.mesa.video_cards {
        VideoCards::Explicit(cards) if cards.contains(&VideoCard::Intel) => {
            Some(PrimeMode::OffloadIntel)
        }
        VideoCards::Explicit(cards) if cards.contains(&VideoCard::Amdgpu) => {
            Some(PrimeMode::OffloadAmd)
        }
        _ => None,
    }
}

fn render_prime_environment() -> &'static str {
    concat!(
        "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
        "# NVIDIA owns the primary rendering path\n",
        "__NV_PRIME_RENDER_OFFLOAD=1\n",
        "__GLX_VENDOR_LIBRARY_NAME=nvidia\n",
        "__VK_LAYER_NV_optimus=NVIDIA_only\n",
        "LIBVA_DRIVER_NAME=nvidia\n"
    )
}

fn render_prime_profile() -> &'static str {
    concat!(
        "#!/bin/sh\n",
        "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
        "# NVIDIA owns the primary rendering path\n",
        "export __NV_PRIME_RENDER_OFFLOAD=1\n",
        "export __GLX_VENDOR_LIBRARY_NAME=nvidia\n",
        "export __VK_LAYER_NV_optimus=NVIDIA_only\n",
        "export LIBVA_DRIVER_NAME=nvidia\n"
    )
}

fn render_prime_modprobe() -> &'static str {
    concat!(
        "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
        "# Proprietary NVIDIA DRM KMS policy\n",
        "options nvidia-drm modeset=1\n"
    )
}

fn render_prime_run(mode: PrimeMode) -> &'static str {
    match mode {
        PrimeMode::OffloadIntel => concat!(
            "#!/bin/sh\n",
            "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
            "# Intel iGPU + NVIDIA dGPU PRIME wrapper\n",
            "export __NV_PRIME_RENDER_OFFLOAD=1\n",
            "export __GLX_VENDOR_LIBRARY_NAME=nvidia\n",
            "export __VK_LAYER_NV_optimus=NVIDIA_only\n",
            "export LIBVA_DRIVER_NAME=nvidia\n",
            "exec \"$@\"\n"
        ),
        PrimeMode::OffloadAmd => concat!(
            "#!/bin/sh\n",
            "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
            "# AMD iGPU + NVIDIA dGPU PRIME wrapper\n",
            "export __NV_PRIME_RENDER_OFFLOAD=1\n",
            "export __GLX_VENDOR_LIBRARY_NAME=nvidia\n",
            "export __VK_LAYER_NV_optimus=NVIDIA_only\n",
            "export LIBVA_DRIVER_NAME=nvidia\n",
            "exec \"$@\"\n"
        ),
        PrimeMode::Primary => unreachable!("primary mode does not generate prime-run"),
    }
}

fn render_nvidia_blacklist(graphics: &Graphics) -> Option<&'static str> {
    match graphics.nvidia?.driver {
        NvidiaDriver::Proprietary => Some(concat!(
            "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
            "blacklist nouveau\n",
            "options nouveau modeset=0\n"
        )),
        NvidiaDriver::Nouveau => Some(concat!(
            "# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY\n",
            "blacklist nvidia\n",
            "blacklist nvidia_drm\n",
            "blacklist nvidia_modeset\n",
            "blacklist nvidia_uvm\n"
        )),
    }
}

const GRAPHICS_DIAGNOSTICS: &str = r#"#!/bin/sh
# THIS FILE IS AUTO-GENERATED BY OXYS - DO NOT EDIT MANUALLY
echo "LIBSEAT_BACKEND=${LIBSEAT_BACKEND:-auto}"
echo "DRM nodes:"
ls -l /dev/dri/card* /dev/dri/renderD* 2>/dev/null || echo "  none"
echo "DRM modules:"
lsmod 2>/dev/null | grep -E '^(i915|xe|amdgpu|radeon|nouveau|virtio_gpu|vmwgfx|nvidia)' || echo "  none detected"
if command -v glxinfo >/dev/null 2>&1; then
    glxinfo -B 2>/dev/null | grep -E 'OpenGL vendor|OpenGL renderer' || true
elif command -v vulkaninfo >/dev/null 2>&1; then
    vulkaninfo --summary 2>/dev/null | sed -n '/Devices:/,$p'
else
    echo "Mesa renderer: install glxinfo or vulkaninfo for userspace diagnostics"
fi
"#;

fn write_generated_file(path: &Path, contents: &str, mode: u32) -> Result<(), RuntimeConfigError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| RuntimeConfigError::CreateDir {
            path: parent.to_path_buf(),
            source,
        })?;
    }

    fs::write(path, contents).map_err(|source| RuntimeConfigError::WriteFile {
        path: path.to_path_buf(),
        source,
    })?;
    fs::set_permissions(path, fs::Permissions::from_mode(mode)).map_err(|source| {
        RuntimeConfigError::SetPermissions {
            path: path.to_path_buf(),
            source,
        }
    })?;
    Ok(())
}

fn remove_if_exists(path: &Path) -> Result<(), RuntimeConfigError> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(source) => Err(RuntimeConfigError::RemoveFile {
            path: path.to_path_buf(),
            source,
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::{
        Compression, GIB, GpuVendor, RamFraction, ResolvedDiskSwap, ResolvedZram, Swap,
        SwapStrategy,
    };
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn offload_writes_only_launcher_and_modeset_not_global_environment()
    -> Result<(), Box<dyn std::error::Error>> {
        let root = test_root("amd_nvidia_prime");
        let manifest = SystemManifest {
            hardware: crate::manifest::Hardware {
                graphics: Graphics::from(crate::manifest::Gpu::Hybrid {
                    igpu: GpuVendor::Amd,
                    dgpu: GpuVendor::Nvidia,
                }),
                ..crate::manifest::Hardware::default()
            },
            ..SystemManifest::default()
        };

        let outcome = sync_graphics_runtime_config(&manifest, &root)?;

        assert!(outcome.prime_offload_configured);
        assert!(!outcome.prime_primary_configured);
        assert!(!root.join(PRIME_ENV_PATH).exists());
        assert!(!root.join(PRIME_PROFILE_PATH).exists());
        assert!(fs::read_to_string(root.join(PRIME_MODPROBE_PATH))?.contains("modeset=1"));
        let launcher = fs::read_to_string(root.join(PRIME_RUN_PATH))?;
        assert!(launcher.contains("__NV_PRIME_RENDER_OFFLOAD=1"));
        assert!(launcher.contains("exec \"$@\""));
        assert!(root.join(GRAPHICS_DIAGNOSTICS_PATH).exists());

        cleanup(&root)?;
        Ok(())
    }

    #[test]
    fn primary_writes_global_environment_without_offload_launcher()
    -> Result<(), Box<dyn std::error::Error>> {
        let root = test_root("nvidia_primary");
        let manifest = SystemManifest {
            hardware: crate::manifest::Hardware {
                graphics: Graphics {
                    nvidia: Some(crate::manifest::Nvidia {
                        prime: GraphicsPrimeMode::Primary,
                        ..crate::manifest::Nvidia::default()
                    }),
                    ..Graphics::default()
                },
                ..crate::manifest::Hardware::default()
            },
            ..SystemManifest::default()
        };

        let outcome = sync_graphics_runtime_config(&manifest, &root)?;

        assert!(outcome.prime_primary_configured);
        assert!(!outcome.prime_offload_configured);
        assert!(
            fs::read_to_string(root.join(PRIME_ENV_PATH))?.contains("__NV_PRIME_RENDER_OFFLOAD=1")
        );
        assert!(!root.join(PRIME_RUN_PATH).exists());

        cleanup(&root)?;
        Ok(())
    }

    #[test]
    fn removes_prime_files_when_gpu_is_not_nvidia_hybrid() -> Result<(), Box<dyn std::error::Error>>
    {
        let root = test_root("prime_cleanup");
        let hybrid = SystemManifest {
            hardware: crate::manifest::Hardware {
                graphics: Graphics::from(crate::manifest::Gpu::Hybrid {
                    igpu: GpuVendor::Intel,
                    dgpu: GpuVendor::Nvidia,
                }),
                ..crate::manifest::Hardware::default()
            },
            ..SystemManifest::default()
        };
        let single = SystemManifest {
            hardware: crate::manifest::Hardware {
                graphics: Graphics::from(crate::manifest::Gpu::Single(GpuVendor::Intel)),
                ..crate::manifest::Hardware::default()
            },
            ..SystemManifest::default()
        };

        sync_graphics_runtime_config(&hybrid, &root)?;
        let outcome = sync_graphics_runtime_config(&single, &root)?;

        assert!(!outcome.prime_offload_configured);
        assert!(!root.join(PRIME_ENV_PATH).exists());
        assert!(!root.join(PRIME_PROFILE_PATH).exists());
        assert!(!root.join(PRIME_MODPROBE_PATH).exists());
        assert!(!root.join(PRIME_RUN_PATH).exists());

        cleanup(&root)?;
        Ok(())
    }

    #[test]
    fn does_not_configure_prime_for_non_nvidia_hybrid() -> Result<(), Box<dyn std::error::Error>> {
        let root = test_root("intel_amd_hybrid");
        let manifest = SystemManifest {
            hardware: crate::manifest::Hardware {
                graphics: Graphics::from(crate::manifest::Gpu::Hybrid {
                    igpu: GpuVendor::Intel,
                    dgpu: GpuVendor::Amd,
                }),
                ..crate::manifest::Hardware::default()
            },
            ..SystemManifest::default()
        };

        let outcome = sync_graphics_runtime_config(&manifest, &root)?;

        assert!(!outcome.prime_offload_configured);
        assert!(!root.join(PRIME_ENV_PATH).exists());

        cleanup(&root)?;
        Ok(())
    }

    #[test]
    fn writes_and_removes_openrc_zram_policy() -> Result<(), Box<dyn std::error::Error>> {
        let root = test_root("swap_runtime");
        fs::create_dir_all(root.join("etc/init.d"))?;
        fs::write(root.join(ZRAM_INIT_PATH), "#!/sbin/openrc-run\n")?;
        let hybrid = ResolvedSwap {
            zram: Some(ResolvedZram {
                size: 8 * GIB,
                algorithm: Compression::Zstd,
                priority: 100,
            }),
            disk: Some(ResolvedDiskSwap {
                size: 4 * GIB,
                priority: 10,
            }),
            swappiness: 180,
        };

        sync_swap_config(&hybrid, &root)?;
        let config = fs::read_to_string(root.join(ZRAM_CONF_PATH))?;
        assert!(config.contains("size0=8192"));
        assert!(config.contains("flag0=100"));
        assert!(config.contains("algo0=zstd"));
        assert!(fs::read_to_string(root.join(SWAP_SYSCTL_PATH))?.contains("vm.swappiness = 180"));

        sync_swap_config(
            &ResolvedSwap {
                zram: None,
                disk: None,
                swappiness: 180,
            },
            &root,
        )?;
        assert!(!root.join(ZRAM_CONF_PATH).exists());
        assert!(root.join(SWAP_SYSCTL_PATH).exists());

        cleanup(&root)?;
        Ok(())
    }

    #[test]
    fn firewall_rules_render_deterministic_locked_down_policy() {
        let firewall = Firewall::Nftables {
            incoming: crate::manifest::FirewallPolicy::Drop,
            forwarding: crate::manifest::FirewallPolicy::Drop,
            outgoing: crate::manifest::FirewallPolicy::Accept,
            allow_icmp: true,
            tcp_ports: vec![80, 22, 80],
            udp_ports: vec![],
        };

        let rules = render_nftables_rules(&firewall).expect("enabled firewall renders");

        assert!(rules.starts_with("#!/sbin/nft -f\n"));
        assert!(rules.contains("flush ruleset"));
        assert!(rules.contains("type filter hook input priority filter; policy drop;"));
        assert!(rules.contains("type filter hook forward priority filter; policy drop;"));
        assert!(rules.contains("type filter hook output priority filter; policy accept;"));
        assert!(rules.contains("iif \"lo\" accept"));
        assert!(rules.contains("ct state established,related accept"));
        assert!(rules.contains("meta l4proto { icmp, ipv6-icmp } accept"));
        assert!(rules.contains("udp sport 67 udp dport 68 accept"));
        assert!(rules.contains("udp sport 547 udp dport 546 accept"));
        // Ports are canonicalised: sorted and deduplicated.
        assert!(rules.contains("tcp dport { 22, 80 } accept"));
        assert!(!rules.contains("udp dport {"));
        assert_eq!(
            render_nftables_rules(&firewall),
            render_nftables_rules(&firewall.clone())
        );
        assert_eq!(render_nftables_rules(&Firewall::Disabled), None);
    }

    fn firewalled_manifest(firewall: Firewall) -> SystemManifest {
        SystemManifest {
            firewall,
            packages: vec![crate::manifest::Package::new("net-firewall/nftables")],
            services: crate::services! {
                openrc: {
                    sysinit: [],
                    boot: [],
                    boot_if: [],
                    default: ["nftables"],
                    nonetwork: [],
                    shutdown: [],
                },
            },
            ..SystemManifest::default()
        }
    }

    fn locked_down(tcp_ports: Vec<u16>) -> Firewall {
        Firewall::Nftables {
            incoming: crate::manifest::FirewallPolicy::Drop,
            forwarding: crate::manifest::FirewallPolicy::Drop,
            outgoing: crate::manifest::FirewallPolicy::Accept,
            allow_icmp: true,
            tcp_ports,
            udp_ports: vec![],
        }
    }

    #[test]
    fn firewall_sync_writes_rules_0600_and_conf_save_on_stop_no()
    -> Result<(), Box<dyn std::error::Error>> {
        let root = test_root("firewall_sync");
        let manifest = firewalled_manifest(locked_down(vec![22]));

        let configured = sync_firewall_config(&manifest, &root)?;

        assert!(configured);
        let rules_path = root.join(NFTABLES_RULES_PATH);
        let mode = fs::metadata(&rules_path)?.permissions().mode() & 0o777;
        assert_eq!(mode, 0o600, "rules-save must not be world readable");
        assert!(fs::read_to_string(&rules_path)?.contains("tcp dport { 22 } accept"));
        assert!(!rules_path.with_extension("oxys-staged").exists());
        let conf = fs::read_to_string(root.join(NFTABLES_CONF_PATH))?;
        assert!(conf.contains("SAVE_ON_STOP=\"no\""));

        cleanup(&root)?;
        Ok(())
    }

    #[test]
    fn firewall_disable_removes_generated_files_but_keeps_foreign_rules()
    -> Result<(), Box<dyn std::error::Error>> {
        let root = test_root("firewall_transition");
        let enabled = firewalled_manifest(locked_down(vec![]));
        sync_firewall_config(&enabled, &root)?;

        // Enabled -> disabled: our generated files are removed.
        let disabled = SystemManifest::default();
        assert!(!sync_firewall_config(&disabled, &root)?);
        assert!(!root.join(NFTABLES_RULES_PATH).exists());
        assert!(!root.join(NFTABLES_CONF_PATH).exists());

        // A hand-managed rules-save (no Oxys marker) is never deleted.
        let foreign = root.join(NFTABLES_RULES_PATH);
        fs::create_dir_all(foreign.parent().expect("parent"))?;
        fs::write(&foreign, "table inet mine {}\n")?;
        assert!(!sync_firewall_config(&disabled, &root)?);
        assert_eq!(fs::read_to_string(&foreign)?, "table inet mine {}\n");

        cleanup(&root)?;
        Ok(())
    }

    #[test]
    fn firewall_sync_rejects_port_zero_and_missing_package_or_service() {
        let root = test_root("firewall_invalid");

        let zero_port = firewalled_manifest(locked_down(vec![0]));
        assert!(matches!(
            sync_firewall_config(&zero_port, &root).unwrap_err(),
            RuntimeConfigError::InvalidFirewall(
                crate::manifest::FirewallValidationError::ZeroPort { protocol: "tcp" }
            )
        ));

        let mut no_package = firewalled_manifest(locked_down(vec![]));
        no_package.packages.clear();
        assert!(matches!(
            sync_firewall_config(&no_package, &root).unwrap_err(),
            RuntimeConfigError::InvalidFirewall(
                crate::manifest::FirewallValidationError::MissingPackage
            )
        ));

        let mut no_service = firewalled_manifest(locked_down(vec![]));
        no_service.services.openrc.default.clear();
        assert!(matches!(
            sync_firewall_config(&no_service, &root).unwrap_err(),
            RuntimeConfigError::InvalidFirewall(
                crate::manifest::FirewallValidationError::MissingService
            )
        ));

        let mut systemd = firewalled_manifest(locked_down(vec![]));
        systemd.init_system = InitSystem::Systemd;
        assert!(matches!(
            sync_firewall_config(&systemd, &root).unwrap_err(),
            RuntimeConfigError::InvalidFirewall(
                crate::manifest::FirewallValidationError::UnsupportedInit(InitSystem::Systemd)
            )
        ));

        // Nothing was written by any failed sync.
        assert!(!root.join(NFTABLES_RULES_PATH).exists());
        cleanup(&root).unwrap();
    }

    #[test]
    fn runtime_rejects_zram_for_systemd_before_writing_files() {
        let root = test_root("systemd_zram_runtime");
        let manifest = SystemManifest {
            init_system: InitSystem::Systemd,
            swap: Swap {
                strategy: SwapStrategy::ZramOnly {
                    algorithm: Compression::Zstd,
                    fraction: RamFraction::HALF,
                },
                swappiness: 180,
            },
            ..SystemManifest::default()
        };

        let error = sync_runtime_config(&manifest, &root).unwrap_err();
        assert!(matches!(
            error,
            RuntimeConfigError::UnsupportedZramInit(InitSystem::Systemd)
        ));
        assert!(!root.join(GRAPHICS_DIAGNOSTICS_PATH).exists());

        cleanup(&root).unwrap();
    }

    fn test_root(name: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time should move forward")
            .as_nanos();
        std::env::temp_dir().join(format!("oxys_runtime_{name}_{nanos}"))
    }

    fn cleanup(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
        if path.exists() {
            fs::remove_dir_all(path)?;
        }
        Ok(())
    }
}
